README.md, packages/tiptap/src/components/editor.js
In order to use debug tool [prosemirror-dev-tools](https://github.com/d4rkr00t/prosemirror-dev-tools) we need access to ProseMirror view object. This PR add Editor component event `init` with this variable.
=> add init event

package.json
This let's me start the dev server under windows 10.
But I can't test this under macOS or linux currently.
This will fix #43 but without the need for cross-env as in #42
=> added windows support for build

examples/Components/Routes/CodeHighlighting/examples.js, examples/Components/Routes/CodeHighlighting/index.vue, packages/tiptap-extensions/src/nodes/CodeBlockHighlight.js
**BREAKING CHANGE**: `CodeBlockHighlight` was importing the full `lowlight` libraries, including _all_
syntax highlighting definitions from `highlight.js`. The new behavior changes the signature of
`CodeBlockHighlight` to accept an object with all syntax highlighting definitions. This means that
now the user of the library __MUST__ import languages themselves and tiptap will no longer
bundle the full `highlight.js` in itself.
---
* Given that you have a working copy from the test repo[1]
* Run `npm run build` in the test repo and check if the highlight.js library is bundled with it.
* Checkout this branch and run `yarn build:packages`
* Copy[2] the contents of `tiptap-extensions` to the test repo:
```
cp -R packages/tiptap-extensions /path/to/test/repo/node_modules/tiptap-extensions
```
* …
=> refactor(tiptap-extensions): Do not import the full `lowlight` library.

README.md
Love the project. I'm pretty new to javascript and github so this is the only thing I felt I could contribute to right now.
The construction "What means x?" asks the same as "what other word(s) have the meaning of x?".
"What does x mean?" asks for the definition of x. I think this is more fitting for the title of the renderless section.
Additional reference: https://www.englishforums.com/English/WhatMeansWhatDoesMean/bgzpcx/post.htm
=> Change renderless section title in readme

packages/tiptap-commands/src/commands/nodeInputRule.js, packages/tiptap-commands/src/index.js, packages/tiptap-extensions/src/nodes/HorizontalRule.js
This allows to use `---` as an alias for a `<hr />`
Also `___` and `***` are supprted but must be terminated with a space to take effect, otherwise __bold__ and _italic_ won't work at start of line.
=> added markdown rule for horizontal line

packages/tiptap-commands/src/commands/markPasteRule.js, packages/tiptap-commands/src/index.js, packages/tiptap-extensions/src/marks/Bold.js, packages/tiptap-extensions/src/marks/Code.js, packages/tiptap-extensions/src/marks/Italic.js, packages/tiptap-extensions/src/marks/Strike.js, packages/tiptap/src/Editor.js, packages/tiptap/src/Utils/Extension.js
Allow pasting of markdown in editor via pasteRules.
Also I am unable to get nested marks to work like:
`___bold and italic___` ___bold and italic___
This should fix #182
=> Markdown paste support.

packages/tiptap/src/Editor.js
Because sometimes you maybe just want to handle drop events 😅
This will however break if someone uses `onPaste` to stop drop events.
=> seperate handleDrop from handlePaste

examples/Components/Routes/Links/index.vue, packages/tiptap/src/Components/EditorMenuBubble.js
Currently the link example is a little bit confusing from a user perspective. 
Clicking on one link and editing it and then clicking on another link keeps the old link in memory.
This **PR** introduced `hide` and `show` events on the menu-bubble component
=> Fix link example

README.md, examples/Components/Routes/Placeholder/index.vue, packages/tiptap-extensions/src/extensions/Placeholder.js, packages/tiptap/src/Editor.js, packages/tiptap/src/Utils/Extension.js, packages/tiptap/src/Utils/ExtensionManager.js
This allows something like this which will call the update method of that extensions.
```js
this.editor.extensions.options.placeholder.emptyNodeText = newValue
```
This will close #153 
~~If the content is **not** empty the state get's mismatched, and everything is screwed up 😩~~ fixed with 89e6436 and 0f44e74
=> Reactive extension options

README.md, packages/tiptap/src/Editor.js, packages/tiptap/test/Editor.spec.js
As requested in #168, I added the possibility to pass `parserOptions` to both the `Editor` constructor and when calling `.setContent()`.  Passing to the constructor was necessary for loading content that contains whitespaces which need to be preserved.
=> allow parseOptions to be passed to setContent and Editor constructor

packages/tiptap/src/Utils/ComponentView.js
This PR addresses #217 
While the modifications linked in that issue describes a solution to fix drag events in general, this PR lets you just override it completely. This way, if you really need to change the behavior, go for it.
=> Allow extensions to override stopEvent

.travis.yml, package.json, yarn.lock
The only exception is `webpack-svgstore-plugin` that still points to some older package versions
with `low` severity vulnerabilities and apparently, the repo is not active that [the actual fix](https://github.com/mrsum/webpack-svgstore-plugin/pull/172)
could be merged. Because of that, I'm limiting the scope to just `high` severity issues.
Note: I decided to include `audit-ci` because `yarn` does not provide (yet) a way to filter
violations by severity level.
=> fix(deps): remove high severity vulnerability and add extra travis check for PRs

examples/Components/Routes/MenuBubble/index.vue, packages/tiptap/src/Components/EditorMenuBubble.js, packages/tiptap/src/Plugins/MenuBubble.js
`EditorView.cordsAtPos`  returns wrong cordinates if we are at a linebreak.
This will fix #215
=> Fix Menu bubble position

packages/tiptap-utils/src/utils/nodeIsActive.js
this fixes isActive.image() mentioned in #225
nodeIsActive was only checking parent nodes and missed the node
currently selected.
=> fix nodeIsActive()

examples/Components/Routes/Placeholder/index.vue
The watcher is actually unnecessary.
So using v-model with `editor.extensions.options.placeholder.emptyNodeText` directly is far more convenient.
=> Placeholder Example: replace watcher with v-model only

packages/tiptap-utils/src/utils/getMarkRange.js
reverting fixes for #156 and trying to fix the detection of endPos.
**ATTENTION**
since i cannot reproduce #156 in the first place please verify that this will not reintroduce the issue from #156..
**what use case gets fixed by this?**
having marks like `<a>aaa<b>bbb</b>ccc</a>` will always select `aaa` even if clicking on `ccc`
expected behaviour: when clicking `ccc` `aaabbbcc` will be selected.
=> Fix getMarkRange

README.md, examples/Components/Routes/Basic/index.vue, examples/Components/Routes/Export/index.vue, examples/Components/Routes/FloatingMenu/index.vue, examples/Components/Routes/HidingMenuBar/index.vue, examples/Components/Routes/History/index.vue, examples/Components/Routes/Images/index.vue, examples/Components/Routes/Links/index.vue, examples/Components/Routes/MenuBubble/index.vue, examples/Components/Routes/Suggestions/index.vue, examples/Components/Routes/Tables/index.vue, examples/Components/Routes/TodoList/index.vue
Directive `slot-scope` is deprecated as of Vue v2.6.0. See [here](https://vuejs.org/v2/guide/components-slots.html) for details. Currently tiptap depends on Vue ^2.6.10. So this commit introduces new directive `v-slot` on README.md and examples.
=> change deprecated `slot-scope` to `v-slot`

packages/tiptap/src/Utils/Emitter.js
- Make flow of logic more compact. It reduces 12 code lines.
- Use `filter` for simple element removal. Unless there are lots of elements, breaking a loop at the middle of iteration doesn't actually have practical benefit, so replaced it with `filter`.
- More flexible. It would be easier to refactor even when argument is changed
to option pack (json).
=> refactor src/Utils/Emitter.js

examples/Components/Routes/Links/index.vue, packages/tiptap-commands/src/commands/markPasteRule.js
this skips links in markPasteRules (Bold, Italic, Code, Strike, Underline)
fixes #258
works only if link extension is added before mark extensions
extensions: [
...
new Link(),
...
new Italic(),
new Bold(),
new Code(),
new Strike(),
new Underline(),
...
]
=> do not transform text of pasted links

packages/tiptap/src/Editor.js, packages/tiptap/src/Utils/ExtensionManager.js
This ads two new options to the editor class to allow input/paste rules to be disabled, by their extension name (`bold`, `italic`, `code_block`, etc.) 
```js
new Editor({
disabledInputRules: ['bold'],
disabledPasteRules: ['bold'],
})
```
Fixes #271
_Maybe I'm wrong and this is alredy possible via another setting ([autoInput](https://prosemirror.net/docs/ref/version/0.3.0.html#autoInput)???)_
=> add option to disable input/pasterules

examples/Components/Routes/Search/index.vue, examples/Components/Subnavigation/index.vue, examples/assets/sass/menubar.scss, examples/main.js, packages/tiptap-extensions/src/extensions/Search.js, packages/tiptap-extensions/src/index.js, packages/tiptap/src/Editor.js
Working on a search and replace plugin:
Known Bugs:
This will close #224
=> add text search and replace

packages/tiptap-extensions/src/nodes/Image.js
This PR implements `inputRules` on Image node, as proposed in #338
=> Feature: Support `inputRules` in Image node

packages/tiptap/src/Plugins/MenuBubble.js
Thank you for great software tiptap!!
Menu Bubble show menu when I select text but I think showing is not needed when I'm selecting Japanese character and I think using browser composing function user agree with me.
bad
good
I add small composing handler.
Please check them when you have time.
Thank you.
=> Handle composition state in MenuBubble

packages/tiptap-extensions/src/extensions/History.js
Only Windows uses Mod+y, this avoids adding the shortcut to other operating systems (such as Linux or iOS).
This adds better support for spoofed user-agents when testing mobile sites on desktop devices.
You could also add `|| /Pocket/.test(navigator.platform)` but it really is optional
=> Switch check from !isMac to isWindows for specificity.

README.md
Improved the documentation for NodeView prop types by adding a table with the Prop name, type, and description. 
#392
=> Added NodeView Prop Types documentation

packages/tiptap/src/Utils/ComponentView.js
I've been implementing CodeMirror within ProseMirror per the [ProseMirror example](https://prosemirror.net/examples/codemirror/). However, the example redefines the behaviour of setSelection on the NodeView so that it focuses the CodeMirror instance. This PR allows Extensions to define a new setSelection function.
=> Allow Extensions to redefine the behaviour of setSelection

packages/tiptap/src/Plugins/MenuBubble.js
closes #473
possible solution for menu bubble not hiding when you focus away to a control element (input, etc.)
check the parent node of the menu bubble.
usually a container that contains both the menu and the editor-content
if the relatedTarget (where we are focusing to) is a child of the parent, we don't hide
if it is not we can hide the bubble menu
=> fix(menu-bubble-hide): only send hide update, target not child of editor

packages/tiptap/src/Plugins/MenuBubble.js
This adds a top property to the menu so that you can have the MenuBubble render below the selection instead of above it. Set `top: ${menu.top}` in the MenuBubble styles to render below.
=> MenuBubbles below the selection

packages/tiptap-extensions/src/extensions/History.js
I realized that tiptap does not have support for historical paths, and Prosemirror has implemented this feature.Used to control the state of the button.
=> Add support for historical paths

packages/tiptap/src/Utils/ComponentView.js
Since prosemirror-view 1.9.13 the dom event handler will call a node view's ignoreMutation() to determine if the node selection should be updated. This causes custom leaf nodes (with no contentDOM) to become unselectable. This patch will allow selection events to go through without restrictions.
=> Fix leaf nodes not selectable

packages/tiptap/src/Plugins/FloatingMenu.js
Sometimes the hide event throws an error since the element of the option does not have a parent node. I added a check if the parent node is not null to the hide event. 
```javascript
tiptap.esm.js?cd42:1849 Uncaught TypeError: Cannot read property 'contains' of null
at Menu.hide (tiptap.esm.js?cd42:1849)
at Editor.eval (tiptap.esm.js?cd42:1778)
at eval (tiptap.esm.js?cd42:461)
at Array.forEach (<anonymous>)
at Editor.emit (tiptap.esm.js?cd42:460)
at Plugin.blur (tiptap.esm.js?cd42:1184)
at eval (index.es.js?576a:3113)
at EditorView.someProp (index.es.js?576a:4567)
at runCustomHandler (index.es.js?576a:3111)
at HTMLDivElement.view.dom.addEventListener.view.eventHandlers.<computed> (index.es.js?576a:3076)
```
=> Fix error in hide event

packages/tiptap/src/Plugins/MenuBubble.js
Sometimes the hide event throws an error since the element of the option does not have a parent node. I added a check if the parent node is not null to the hide event. 
```javascript
tiptap.esm.js?cd42:1849 Uncaught TypeError: Cannot read property 'contains' of null
at Menu.hide (tiptap.esm.js?cd42:1849)
at Editor.eval (tiptap.esm.js?cd42:1778)
at eval (tiptap.esm.js?cd42:461)
at Array.forEach (<anonymous>)
at Editor.emit (tiptap.esm.js?cd42:460)
at Plugin.blur (tiptap.esm.js?cd42:1184)
at eval (index.es.js?576a:3113)
at EditorView.someProp (index.es.js?576a:4567)
at runCustomHandler (index.es.js?576a:3111)
at HTMLDivElement.view.dom.addEventListener.view.eventHandlers.<computed> (index.es.js?576a:3076)
```
=> Fix error on hide event

README.md
The readme was missing a few props that are passed to node components. It took me a while to figure out that they were there, so I thought I might as well make it easier for someone else.
=> Added node components props to readme

packages/tiptap/src/Utils/ComponentView.js
This PR allows extensions to define their own [update](https://prosemirror.net/docs/ref/#view.NodeView.update) behavior. Similar to the pr from #419, in that it's needed to implement a CodeMirror Node in TipTap based off [the ProseMirror example](https://prosemirror.net/examples/codemirror/). From the ProseMirror page,
> When an update comes in from the editor, for example because of an undo action, we kind of have to do the inverse of what valueChanged did—check for text changes, and if present, propagate them from the outer to the inner editor.
An example of usage:
```js
import CodeMirror from "codemirror"
export default class CodeBlock extends Node {
...
update(node) {
if (node.type != this.vm.node.type) return false
this.vm.node = node
let change = …
```
=> Allow extensions to define update behavior.

packages/tiptap-extensions/src/plugins/Highlight.js
This PR applies [decorations](https://prosemirror.net/docs/ref/#view.Decorations) in the [Highlight Plugin](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/plugins/Highlight.js) if there is a change in the number of nodes. This is useful for cases when new nodes are programmatically created such that the current selection is not within the new nodes. 
An example of of this is with collaborative editing: another user may create a new CodeBlock node that's updated into the main user's editor. Without this PR, the new CodeBlock is created but is not highlighted.
=> Apply decorations in HighlightPlugin if change in named nodes.

examples/Components/Routes/Suggestions/index.vue, package.json, yarn.lock
This PR:
- updates tippy.js dendency to version 6
- provides updated example code for the suggestion/mention extension
As pointed out in https://github.com/scrumpy/tiptap/issues/523:
> The new API of tippy.js does not have instance.popperInstance.scheduleUpdate method anymore.
So we use the proposed _sticky_ plugin to make tippy.js update itself, when content changes.
=> Make suggestions work with tippy.js v6

README.md, packages/tiptap/src/Editor.js
This commit changes `registerPlugin` by 1. adding the new plugin to `this.plugins` and 2. updating `this.plugins` within `this.state.plugins` by splicing with the new `this.plugins` length. Previously, new plugins were simply added to the end of `this.state.plugins` and were not appended to `this.plugins`.
By placing registered plugins at this new location within `this.state.plugins`, we prioritize registered plugins over default ProseMirror plugins such as `keymap(baseKeymap)`. This will allow new plugins to have precedence over props such as `handleKeyDown`. A use case of this defining a floating Editor Menu that's navigable with arrow and enter keys.
=> Change registerPlugin to add plugin after Extensions plugins

.gitignore, package-lock.json, packages/tiptap/src/Editor.js
Referencing issue: 
https://github.com/scrumpy/tiptap/issues/724
Solution proposed here:
https://github.com/scrumpy/tiptap/issues/713
**Describe the bug**
When using the editor and importing data which was stored as raw HTML string (usually by getHTML() function) it is possible to inject javascript code there and create a stored XSS in the application using the editor.
The code that is causing the issue seems to be that one [Editor.js:274-276]
```
if (typeof content === 'string') {
const element = document.createElement('div')
element.innerHTML = content.trim()
```
Most javascript code cannot be injected through .innerHTML property, but by using events of <img> tag it is possible. Simplest payload that can be used is `<img src=x onerror=alert(1)>`
The code is executed in the moment of …
=> XSS bug fix issue #724: XSS issue when importing through getHTML() function 

packages/tiptap-commands/src/commands/toggleWrap.js
When creating a custom node of type wrapper you cannot pass attributes as you could with a classic block type.
Simply fixed by adding a second parameter to the _toggleWrap_ function for attributes, and by passing them to _isNodeActive_ and _wrapIn_ methods.
Then we can use attributes the same way we do with _toggleBlockType_
```javascript
commands ({ type, schema }) {
return attrs => toggleWrap(type, attrs)
}
```
By the way, thanks for the amazing work !!
=> Allow attributes for wrappers

packages/tiptap-commands/src/commands/markPasteRule.js
check parent exists
currently seeing the following error a lot on paste
`Cannot read property 'type' of undefined`
function arguments only contain the fragment and no parent
```js
[{
currentTarget: div._1hgD7 > div._2HMtf._1da_S > div.ProseMirror.ProseMirror - focused,
isTrusted: [object ClipboardEvent],
target: div.ProseMirror.ProseMirror - focused > div._2v_ft.is - editor - empty > br,
type: paste
}]
```
=> fix(markpasterule): parent is undefined for mark

packages/tiptap-extensions/src/marks/Link.js
This adds an option to put a **target** attribute to the generated link. 
By default, no attribute is generated.
Usage is as follows.
`
new Link({
target: '_blank'
})
`
=> Add option to put target for the created link

packages/tiptap-extensions/src/nodes/TodoItem.js
This is in reference to https://github.com/scrumpy/tiptap/issues/69, which is closed but is still relevant for any project that requires a strict CSP (content security policy), such as a Chrome Extension or many enterprise apps.
Having both a render function and the template is required, as having only a render(h) causes errors with converting the node to JSON. It also makes the render(h) function more legible, as you have something to reference when reading the render(h) function. 
In that file, I added a comment that should further document why the render(h) function is embedded.
=> render(h) function support for TodoItem

packages/tiptap/src/Editor.js
see details in #747:
>This PR implements my suggestion at #713 however, it left out a crucial part where we get the parsed DOM first element as the root element.
>This PR parses the HTML string using the browser's native DOMParser and passes the body as the root DOM node. However, in order to parse the HTML string, we wrapped the content in a single div root node. This makes Tiptap break on certain occasions when using custom extensions. I have yet to understand why it happens, but it seems like that just passing the body.firstElementChild as the root DOM solves this issue effortlessly.
=> Fix an issue with with parsing custom extensions

packages/tiptap-extensions/src/marks/Link.js
This PR improves the pasteRules for the Link mark. It allows domains to be a single letter (e. g. https://t.me) or uppercase (e. g. https://GOOGLE.COM).
Fixes #745
=> Improve pasteRules for Link mark

README.md, packages/tiptap/src/Editor.js
The title says it all :)
It's very important that tiptap **suggests**, but doesn't **enforce** plugins, so optional enable / disable parameters must exist.
=> Add options to enable / disable dropCursor and gapCursor

packages/tiptap-extensions/src/nodes/Blockquote.js
Closes #803
The unwrapping is limited to the current Node, so if you have multiple nodes (2 Paragraphs or in this case a Paragraph and a Heading) only the selected node gets lifted...
=> fix: blockquote unwrap not working

packages/tiptap-extensions/src/marks/Link.js
Currently there seems to be no way to use `target="value"` on some Link marks and `target="other"` on another Link mark, because in `toDOM` the value of `node.attrs.target` will always be overwritten with `defaultOptions.target`. 
I think this was introduced in #619.
With the PR, the individual values are preferred and the `defaultOptions.target` will only be used as a fallback.
=> Allow Links to use their individual attrs.target

packages/tiptap-extensions/src/nodes/Table.js
The `setCellAttr` command has no use if we can't pass parameters to it. My issue was setting the background color of a cell in a table.
Fixes #862.
=> SetCellAttr in prosemirror-tables needs parameters

examples/Components/Routes/Suggestions/index.vue
A fix for: When the user scrolled or resize the screen, the tooltip position didn't update
=> Fix tippy position incorrect after resize or scroll

packages/tiptap/src/Plugins/MenuBubble.js
Fix #954
There is an issue where `document.createRange()` is being called with negative values which throws an error.
This pull request constrains it to be always greater than 0, so the error doesn't happen any more.  I've tested this and it seems to work okay.
I'm not sure why the `from` variable is being returned as -1 sometimes, so perhaps this is an underlying issue that needs to be fixed too.
=> Constrain `from` to non-negative numbers

packages/tiptap-extensions/src/plugins/Highlight.js
Prosemirror does not handle emptystring classes well for decorations when the decoration applies to a range that has other decorations. For example, both a spellchecking plugin and the tiptap highlighting plugin.
See this debugger screenshot in prosemirror showing the code that merges decorations together before they're applied. There are two decorations - one from a spellchecker, and one from the Highlight plugin that has no class because the specific range did not receive any specific highlight:
The above results in a string like `"spellcheck-error "`, which is then re-split by prosemirror into an array `["spellcheck-error", ""]`. This is in turn fed into `HTMLElement.classList.add(...)`, which throws an error when it receives emptystring:
However, there's no reason to send an empty …
=> Fix sending of emptystring class for Prosemirror decoration

docs/src/docPages/overview/upgrade-guide.md
This makes it easier than having to navigate over to the `installation` page.
=> Add install instructions

packages/extension-horizontal-rule/src/horizontal-rule.ts
The Typography extension automatically converts two hyphens `--` into an em dash `–`, which means typing three hyphens in a row results in an em dash and a hyphen `–-`, instead of triggering an hr. 
I propose adding the `–-` pattern to this extension‘s `nodeInputRule` so typing three hyphens in a row will still trigger an hr, even if 'smart dashes' are enabled via the Typography extension or otherwise.
=> Make Horizontal Rule compatible with Typography extension

packages/core/src/CommandManager.ts
I think this was previously meant to return a function in the proxy object getter, but now it's a standalone function and should return the result of the callbacks.
=> Fix returning true/false in can().chain().run()

docs/src/docPages/installation/livewire.md
The current draft works fine when integrated into "static" Livewire components, however, it doesn't work in cases where the Livewire component reloads its data, be it due to a component method, lifecycle hook or simply because the flow for the component includes an option to reset its data. Old data will be cached into TipTap and new data will not come.
I re-wrote the example to work in these cases, and also for it to be more aligned to [Alpine's example](https://www.tiptap.dev/installation/alpine), with the only difference that we'll now use Alpine as a proxy for Livewire<->TipTap communication.
If there are any questions, suggestions or jokes, feel free to let me know :smile:
=> [Docs] Improve example integration with Laravel Livewire

packages/vue-2/src/BubbleMenu.ts, packages/vue-2/src/EditorContent.ts, packages/vue-2/src/FloatingMenu.ts, packages/vue-2/src/NodeViewContent.ts, packages/vue-2/src/NodeViewWrapper.ts
=> feat: better types for Vue 2

packages/vue-3/src/VueRenderer.ts
I created a version of the Mention extension, heavily based on the example code when I noticed an issue, the keydown handler didn't work.
(Sample repo of the code not working: https://github.com/thechrisoshow/tiptap-mentions
Running at: https://determined-minsky-6136aa.netlify.app/ )
This was because of how we're sending messages from the parent component to the child using the VueRenderer's `ref`. 
e.g.
```ts
onKeyDown(props) {
// this fails with error on production like:
// "Uncaught TypeError: Cannot read property '3573854894' of undefined"
return component.ref?.onKeyDown(props);
},
```
It would work perfectly on development, but it looks like on production the underlying `ctx` object has the $refs stripped away, so the following wouldn't work (from VueRenderer.ts)
```ts
get ref(): any …
```
=> VueRenderer's ref is undefined when in production mode

docs/src/docPages/guide/custom-extensions.md
The current url have a missing `s`
=> Fix text-align extension url

packages/react/src/useEditor.ts
in case the options depend on props of the consuming component, it would be nice to be able to pass a dependencylist to `useEditor`. Unless there's a better way to handle dependency updates
=> Allow passing of DependencyList to useEditor

docs/src/docPages/installation/cdn.md
You were missing an `<html>`-starter tag,  so users who copy-pasted the code would have experienced errors - not a very good first impression…
(Furthermore, I changed `<!doctype html>` to `<!DOCTYPE html>`since that's just more common)
=> Make HTML in docs valid

packages/core/src/utilities/createStyleTag.ts
Code sandbox example [here](https://codesandbox.io/s/objective-glitter-mj9t0?file=/src/App.vue)
When using multiple Editor instances on the same page with `injectCSS` (which defaults to true), you get duplicate style that apply the same styles in the head.
This prevents those duplicate entries
=> Prevent tiptap from creating duplicate style tags when injecting css

docs/src/demos/Marks/Subscript/index.spec.js, docs/src/demos/Marks/Subscript/index.vue, docs/src/demos/Marks/Superscript/index.spec.js, docs/src/demos/Marks/Superscript/index.vue, docs/src/docPages/api/marks.md, docs/src/docPages/api/marks/subscript.md, docs/src/docPages/api/marks/superscript.md, docs/src/links.yaml, packages/extension-subscript/README.md, packages/extension-subscript/package.json, packages/extension-subscript/src/index.ts, packages/extension-subscript/src/subscript.ts, packages/extension-superscript/README.md, packages/extension-superscript/package.json, packages/extension-superscript/src/index.ts, packages/extension-superscript/src/superscript.ts
I've built the subscript and superscript extensions for tiptap v1, as an example of how community extensions could work.
It seems more and more people port the code to tiptap v2, so it’s probably worth to add them to the officially provided marks to save people some time.
What do you think?
Based on @jelleroorda, who ported my code and shared it in #819. 😅
=> New extensions: add subscript and superscript extensions (including docs and tests)

packages/extension-subscript/src/subscript.ts, packages/extension-superscript/src/superscript.ts
Shortcuts based on how Google Docs handles superscript and subscript keyboard shortcuts: https://support.google.com/docs/answer/179738.
=> Add keyboard shortcuts to toggle superscript and subscript marks.

packages/extension-dropcursor/src/dropcursor.ts
Currently drop cursor defaults to black rather than the text color, which is what normal carets default to. Using `currentcolor` should provide a better default value.
=> Make drop cursor default to regular caret color

packages/react/src/NodeViewContent.tsx, packages/react/src/NodeViewWrapper.tsx
These changes allow developers to get a ref to the Tag rendered by NodeViewContent / NodeViewWrapper. E.g., now this is possible:
```
<NodeViewWrapper ref={myRef} />
```
and myRef would be hooked up to the div
=> use forwardRef for react wrappers

packages/extension-mention/src/mention.ts
This PR allows you to change the text that is to be rendered in the DOM when a selection is made from the suggestion.
This is so that you may want the `data-mention` attribute to use a user's ID but the user's name would be displayed instead of the ID e.g. "@JohnSmith" instead of "@1".
=> Mention: Add text attribute

packages/extension-text-style/src/text-style.ts
I built some extensions based on the textStyle extension but whenever I reset a style/attribute, the whole textStyle mark gets removed when there are still other styles defined in the mark.
=> Fix removal of textStyle mark when any style resets

docs/src/docPages/api/extensions/dropcursor.md
I forgot to update the docs for previous pull request: https://github.com/ueberdosis/tiptap/pull/1444
=> Correct default for dropcursor color in docs

docs/src/docPages/guide/custom-extensions.md
PR to check my understanding, has this API changed?
Live doc: https://www.tiptap.dev/guide/custom-extensions#events
Edit: typescript doesn't like `{editor}` as the argument, though it seems to work in practice.
```
Type '({ editor }: { editor: any; }) => void' is not assignable to type '(this: { name: string; options: unknown; editor: Editor; parent: ... | null | undefined; }) => void'.ts(2322)
(property) onSelectionUpdate?: ((this: {
name: string;
options: unknown;
editor: Editor;
parent: ... | null | undefined;
}) => void) | null | undefined
```
=> doc update: onSelection → onSelectionUpdate

packages/extension-task-item/src/task-item.ts
#1566 
Another alternative would be to remove the label wrapper element so the nodeview output is
```html
<li data-checked="true" class="">
<input type="checkbox">
<div><p>A list item</p></div>
</li>
```
This would allow people to style the content of the todo-item with a sibling css selector:
```css
ul[data-type=taskList] > li > input[type=checkbox] + div { 
text-decoration: line-through;
}
```
=> update task-item.ts nodeview to update data-checked

docs/package.json, docs/src/demos/Experiments/Embeds/index.vue, yarn.lock
The deprecation warning shown in the console is triggered by using the "old" way to divide to values.
https://sass-lang.com/documentation/breaking-changes/slash-div
`node-sass` was replace by `sass` at it's recommended to upgrade to the maintained version. The [readme](https://github.com/sass/node-sass) of the `node-sass` says:
> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.
=> Replace node-sass with dart sass and fix deprecation warning

docs/src/demos/Examples/MarkdownShortcuts/Vue/index.spec.js, docs/src/demos/Extensions/History/index.spec.js, docs/src/demos/Nodes/HardBreak/index.spec.js, packages/extension-history/src/history.ts
This readds the shortcuts introduced in Tiptap v1 and fixes the history tests.
+ this removes the skipped flags of all remaining tests
=> Readd russian history shortcuts

packages/core/src/NodeView.ts, packages/core/src/types.ts
Export NodeViewRendererOptions. This avoids adding a dependency/peerDependency for `promsemirror/{view,model}` for packages like `svelte-tiptap` and `ngx-tiptap`.
Core packages can make use of this as well.
=> Export NodeViewRendererOptions

packages/html/package.json, tests/cypress/integration/html/generateJSON.spec.ts, yarn.lock
Fixes #1601
Fixed by https://github.com/holtwick/hostic-dom/pull/5
=> Update hostic-dom to fix style attributes

packages/extension-text-align/src/text-align.ts
Text align extension`s options were not exported as for other extensions.
=> fix: export text align extension options

packages/starter-kit/src/index.ts
Starter kit extension options were not exported.
Without this change, we have to import types from the dist directory:
```typescript
import { StarterKitOptions } from "@tiptap/starter-kit/dist/packages/starter-kit/src/starter-kit";
```
=> fix: export starter kit extension options

packages/extension-text-align/src/text-align.ts
TextAlignOptions is not being exported correctly. Other extensions have their options defined as an interface not a type, so I assume changing this to match will fix the problem.
eg
```ts
export interface BlockquoteOptions {
HTMLAttributes: Record<string, any>,
}
```
=> Change TextAlignOptions to interface (not type)

packages/core/src/pasteRules/markPasteRule.ts
For example: you are matching URLs with a Regex but want to make additional checks on the match array before deciding if you want to apply the mark or not. Returning null or false won't attempt to apply the mark. 
Currently the return value of getAttributes is applied unconditionally. So this is somewhere between a feature request and a bug fix.
=> Allow a rule to be skipped from the getAttributes callback

packages/suggestion/src/findSuggestionMatch.ts
When using suggestions with multi-characters it currently fails.
eg. char = '@@'
=> Fix multi character suggest

packages/extension-code/src/code.ts
Bug fix 👍 
`markPasteRule` has been using the `inputRegex` which is terminated with $ so it's only being applied to when the pasted text is _only_ code, not when it _contains_ code.
=> Apply the correct regex in markPasteRule

packages/suggestion/src/suggestion.ts
There is a bug in suggestion plugin since Tiptap v1 when you use Collaboration and Mention together. It is bit edge case, but we actually ran into it in prod.
Open 2 editors (using collab)
Editor1 (user1): type some text and then enter Mention
Editor2 (user2): type/paste text anywhere before user1’s position
Editor1 (user1): confirms mention
Mention is at wrong position (replaces text at wrong position)
Reason: 
When you use mention locally, from variables “handleStart, handleChange, handleExit“ only 1 is true (as it goes: start->change->...->change->exit).
When text in front of mention is changed in collab, it is not considered change (handleChange==false) as query is the same. Instead of it handleExit==true, handleStart==true and handleChange==false which cause that onStart is called …
=> fix: use correct state when doc changed externally

docs/src/demos/Examples/Tables/React/index.jsx, docs/src/docPages/api/commands/insert-content.md, packages/core/src/commands/insertContent.ts, packages/core/src/commands/insertContentAt.ts
`insertContent` for HTML with table on it, doesn't work well due to `preserveWhitespace: 'full',` when `false` it work well.
- Add the possibility to make it false.
- Update the doc
compare to 
for this HTML
```
<table style="width:100%">
<tr>
<th>Firstname</th>
<th>Lastname</th> 
<th>Age</th>
</tr>
<tr>
<td>Jill</td>
<td>Smith</td>
<td>50</td>
</tr>
<tr>
<td>Eve</td>
<td>Jackson</td>
<td>94</td>
</tr>
<tr>
<td>John</td>
<td>Doe</td>
<td>80</td>
</tr>
</table>
```
=> ✨ Add CreateNodeFromContentOptions to insertContent

packages/core/src/Editor.ts, tests/cypress/integration/core/editorProps.spec.ts
This change ensures that `Editor.options.editorProps` correctly references the ProseMirror View props `this.view.props`.It enables users to read and manipulate the props as expected. Additionally calls `view.setProps(...)` when `editor.setOptions(...)` is being called with `editorProps` so they can be set and updated through this method as well.
Includes tests, closes https://github.com/ueberdosis/tiptap/issues/1518
=> Use correct reference for options.editorProps

docs/src/docPages/api/extensions/bubble-menu.md, docs/src/docPages/api/extensions/floating-menu.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-bubble-menu/src/bubble-menu.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu.ts, packages/react/src/BubbleMenu.tsx, packages/react/src/FloatingMenu.tsx, packages/vue-2/src/BubbleMenu.ts, packages/vue-2/src/FloatingMenu.ts, packages/vue-3/src/BubbleMenu.ts, packages/vue-3/src/FloatingMenu.ts
This PR adds two features to the bubble menu and floating menu extension
- add `shouldShow` option to overwrite the logic for showing the menu (fixes #1480, fixed #1043, fixes #1268, related to #1313)
- add `key` option to use multiple menus (related to #1480)
Bugfixes
- fixes a bug where the floating menu is visible within code blocks (fixed #1503)
=> Menu improvements

docs/src/demos/Extensions/History/index.spec.js, docs/src/demos/Extensions/History/index.vue
Related https://github.com/ueberdosis/tiptap/issues/531
I think this is a common usecase and also a good demo of `can()`
=> Docs: Disable history demo buttons when commands are not available

docs/src/docPages/installation/alpine.md
Update alpine docs
Closes #1584
=> Update alpine docs

docs/src/demos/Extensions/Color/index.spec.js, docs/src/demos/Extensions/Color/index.vue
A color picker is commonly used to change text color. This PR adds such example to the docs. This is also a good example of `getAttributes('textStyle')`.
Added tests for color extension
=> docs: add color picker to color extension demo

packages/suggestion/src/findSuggestionMatch.ts, packages/suggestion/src/suggestion.ts
Currently `suggestion` extension only allows triggering the suggestions dropdown if the suggestion character is prefixed by space. This of course makes sense for @mentions but for some other use cases it is desirable to also trigger suggestions dropdown if suggestions character is not prefixed by space (e.g. with variables inside the text).
Already requested in:
* https://github.com/ueberdosis/tiptap/issues/1384
* https://github.com/ueberdosis/tiptap/issues/329
=> Allow triggering suggestions without prefix space

packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
This PR defers the initialization of the tippy library in the bubble and floating menu extensions to the moment when the `update` hook is first invoked by ProseMirror. The goal of this change is initializing the tippy library only when the Editor’s element is attached to the document. The `update` hook provides a convenient place to check whether the aforementioned condition is met. 
We are implementing a WYSIWYG Editor using Tiptap’s Vue 2 extension. We ran into a problem where the `requestAnimationFrame` call is executed without delay right after the bubble menu plugin is initialized. This behavior causes a race condition where tippy is initialized before the Vue component is fully mounted. 
I can’t explain why `requestAnimationFrame` is invoked differently from the demos you provide in …
=> Fix: Don’t initialize tippy on requestAnimationFrame to avoid race conditions

packages/react/src/ReactRenderer.tsx
- Allow us to pass Ref to a function ForwardRef component in reactRenderer (useful for mention)
=> ✨ Follow Ref on ForwardRef component in reactRenderer

packages/core/src/commands/toggleMark.ts, packages/core/src/commands/unsetMark.ts, packages/extension-link/src/link.ts
This PR adds an option `extendEmptyMarkRange` to the `unsetMark` and `toggleMark` commands. This defaults to `false` now (until now it was `true`). This options is useful for the link mark, to remove a link even if there is an empty selection but it’s rather confusing for other marks.
Thanks for @isubasti for the main idea (#1650).
=> feat: add extendEmptyMarkRange option to mark commands

packages/extension-placeholder/src/placeholder.ts
Adds an option to the placeholder plugin to include children in the search for empty nodes.
Consider the use case in which there is a `header` node with `title` and `subtitle` nodes. Currently, the header node will be the only one that receives the `.is-empty` class. Therefore, typing something into the title node makes the subtitle placeholder disappear, which is confusing to users. With the modifications in this PR, the search for empty nodes can be continued to children. Therefore, the subtitle node would retain its placeholder until modified.
I'd like to get some feedback on this before updating the docs and such.
=> Include children in placeholder plugin

packages/extension-code-block-lowlight/src/code-block-lowlight.ts, tests/cypress/integration/extensions/codeBlockLowlight.spec.ts
This MR fixes a bug in the Code Block Lowlight extension that doesn’t allow extending the extension further. When we extend `CodeBlockLowlight`, the code in the child extension is not highlighted. We discovered that the root cause of this problem is a hard coded extension named provided to the `LowlightPlugin`. Passing the extension name fixes this problem. 
This PR also contains a failing test.
=> Fix: code-block-lowlight child extensions do not highlight code

packages/extension-highlight/src/highlight.ts
Seems like inputRegex was used in addPasteRules by mistake (?)
=> Use pasteRegex in addPasteRules

docs/api/editor.md, docs/guide/custom-extensions.md
Related: https://github.com/ueberdosis/tiptap/issues/943
It was difficult to find and understand Editor props, I tried to make docs more easy to unederstand
=> Docs: Clear up Prosemirror EditorProps usage

docs/overview/upgrade-guide.md
The commands toggleHardBreak(), toggleHorizontalRule(), toggleParagraph() do not exist. 
Updating the documentation to reflect the existing commands setHardBreak(), setHorizontalRule(), setParagraph().
=> Docs: Update command names in upgrade guide

packages/core/src/inputRules/nodeInputRule.ts
Fixes in nodeInputRule()
- add support for "first group match, if any" similar to https://prosemirror.net/docs/ref/#inputrules
- fix issue where rewriting includes extra unnecessary character from the match
=> Fix: nodeInputRule() support for group match

packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
Update `destory` methods on BubbleMenu and FloatingMenu plugins to correctly remove event listeners.
=> Fix "destory" method in view plugins.

demos/preview/Demo.vue
Fixes the link to vie the examle directly on Github
=> Fix 'Edit on Github' link url for examples in docs

.gitignore, packages/core/src/Editor.ts, packages/core/src/EventEmitter.ts, packages/core/src/types.ts
Fixes #1898
+ Made the `EventEmitter` generic to be able to specifically type the events
+ Created an interface `EditorEvents` for the event types
+ Updated the types in `EditorOptions` to use the types provided by the new `EditorEvents` interface
=> Added better types for event emitter

packages/react/src/NodeViewContent.tsx, packages/react/src/ReactNodeViewRenderer.tsx, packages/react/src/useReactNodeView.ts
Instead of calling `maybeMoveContentDOM` manually, we are using a `ref`.
fixes #1942, which was broken because of[ this patch](https://github.com/ueberdosis/tiptap/commit/b15a8a8683bafbc9fd57dc64d60329f9ab08ecfd) (which was a fix for #1747). #1747 is still fixed with this PR.
@YousefED I had to remove `forwardRef` for `NodeViewContent` (which was a [merged PR from you](https://github.com/ueberdosis/tiptap/pull/1452)) for that so I would like to hear you thoughts about this change. I’m still not quite sure what you needed this ref for. Can you give me an example?
=> Use ref to move contentDOM

packages/extension-code-block-lowlight/src/lowlight-plugin.ts
`.value` is changed to `.children` in lowlight v2
=> fix: compatibility with lowlight v2

packages/core/src/commands/insertContentAt.ts, packages/extension-horizontal-rule/src/horizontal-rule.ts
With this PR we try to improve the behavior of `insertContent` in some cases.
1. When content is inserted into an empty text block, we try to replace the text block instead of inserting the content after the text block. This prevents empty paragraphs for example.
2. After inserting, the cursor is placed at the end of the inserted content instead of after it (fix #1673)
3. Prevent multiple nodes after inserting a horizontal rule to an empty document (see #1964)
4. Fix error when inserting horizontal rule at the end of the document (fix #2117)
=> Improve behavior when using insertContent

packages/core/src/Editor.ts
Just a small typescript tweak to the `getJSON` return type.
If there is a reason it wasn't this way, feel free to close and I'll know not to type my onUpdate handlers with it. 😄
=> update getJSON return type to JSONContent

packages/extension-floating-menu/src/floating-menu-plugin.ts
I did some more debugging on #1994 and found out that the problem (floating menu does not hide when you type) happens when composition is true (https://firefox-source-docs.mozilla.org/editor/IMEHandlingGuide.html).
The common cases I found:
- Japanese keyboard on both IOS and Android (https://github.com/ueberdosis/tiptap/issues/1994#issuecomment-961598567)
- Typing on Android before you insert space as it uses autocomplete and autocorrect (https://github.com/ueberdosis/tiptap/issues/1994#issuecomment-957025857)
- Interestingly, I have autocomplete and autocorrect on IOS and it does not go to composition
This PR simply removes check if composition is true. I use floating menu for both menu on empty line (as Tiptap example does) and menu attached at the end of the current line as you type. …
=> Floating menu - remove composition check

packages/extension-code-block-lowlight/src/lowlight-plugin.ts
This MR removes a console.log statement from the `lowlight-plugin.ts` file that appears in testing and production environments.
=> Remove console.log statement from codeblock-lowlight-plugin file

packages/core/src/NodeView.ts
We're running into a weird bug where NodeViews get stuck an infinite loop of mounting and unmounting when they contain an iframe. This causes a React [maximum update depth exceeded](https://reactjs.org/docs/error-decoder.html/?invariant=185) crash, and also causes the content of some of those nodeviews to be wiped out. 
To reproduce, try visiting https://9hgxv.csb.app/ on an iPhone. The same code works fine on a desktop.
We believe the issue is related to the default `ignoreMutation` method, which returns false when contenteditable nodes are added on iOS. I don't understand all the context of this function, but we found that patching this function to add a check for `this.editor.isFocused` (to narrow the if statement to only apply when triggered by the user's keyboard) fixed it in our …
=> Ignore iOS mutations when unfocused

packages/core/src/ExtensionManager.ts, packages/core/src/helpers/isExtensionRulesEnabled.ts, packages/core/src/types.ts
In multiple project I wan't to enable only input / paste rules I need but there is no easy way to do it. (e.g I only want to paste links)
Allow to pass an array of extension or extension name for `enableInputRules` and `enablePasteRules` editor options:
```js
new Editor({
extensions: [
StarterKit,
Link,
 ],
enablePasteRules: [Link],
enableInputRules: ['horizontalRule'],
})
```
I will update docs if it's ok for you 👍
=> feat: Allow array of extensions for `enableInputRules` and `enablePasteRules`

docs/api/editor.md
I was looking for an option to toggle edit ability on the editor and only found `setOptions` in the docs. Was surprised by code completion with the option of setting `editable` directly this way.
=> Add `setEditable` to the Editor documentation

packages/react/src/ReactNodeViewRenderer.tsx
Right now, `ReactNodeViewRenderer` renders as a `<div class="react-renderer">` wrapper. We'd like to be able to pass an `as` prop to specify what kind of top-level HTMLElement corresponds with our node content. This could give people are a more granular control over how their elements get added (i.e. instead of just `div` or `span`, we could let people render an `img` or `li` directly).
At Gamma, our main use case is to allow us to have `li` elements adjacent to each other (rather than nested inside the div produced by ReactNodeViewRenderer). 
Additionally, (and for a separate PR), we like being able to pass the top-level `<li>` an `indent` attribute to dynamically do counter-resets. Right now there's no flexibility to add arbitrary attributes to the outermost wrapper when you use …
=> feat(ReactNodeViewRenderer): Add `as` option and pass through to ReactRenderer

packages/core/src/Editor.ts, packages/core/src/commands/focus.ts, packages/core/src/helpers/resolveFocusPosition.ts
Right now, the initial selection because it is undefined in `EditorState.create` is equal to [`Selection.atStart`](https://github.com/ProseMirror/prosemirror-state/blob/61bb964783b20800f6abc18dad855bd3bbf8cdd7/src/state.js#L25). 
Expected behavior is that if `autofocus` is defined, it is equal to the selection created on first focus. 
Example use-case is if `autofocus='end'`, then within a ProseMirror plugin `init` method: `state.doc.selection` should equal `Selection.atEnd` instead of `Selection.atStart`.
=> initialize autofocus selection in `createView`

docs/installation/svelte.md
This example doesn't compile because in Svelte 3 there is no `type="context"`, there is only `context="module"`. Even if you use `context="module"` it is supposed to give an error because there is no `onMount` and `onDestroy` in module context.  Removing this tag from the Script element will fix the issue.
=> Svelte Example: remove wrong `type="context"` tag

demos/src/Examples/Community/React/index.jsx, demos/src/Examples/Community/Vue/index.vue, demos/src/Extensions/CharacterCount/React/index.jsx, demos/src/Extensions/CharacterCount/Vue/index.vue, docs/api/editor.md, docs/api/extensions/character-count.md, packages/core/src/Editor.ts, packages/extension-character-count/src/character-count.ts
With this PR we introduce the redesigned `CharacterCount` extension. It’s a full re-write and fixes some bugs.
You can now choose between `textSize` and `nodeSize` for calculating the character size. Defaults to `textSize`.
```js
CharacterCount.configure({
mode: 'nodeSize',
})
```
Get the number of characters for the current document with this new storage method. This deprecates `editor.getCharacterCount()`.
```js
editor.storage.characterCount.characters()
// Get the size of a specific node.
editor.storage.characterCount.characters({ node: someCustomNode })
// Overwrite the default `mode`.
editor.storage.characterCount.characters({ mode: 'nodeSize' })
```
Get the number of words for the current document with this new storage method.
```js
editor.storage.characterCount.words()
// Get the …
```
=> A brand new `CharacterCount` extension

packages/core/src/commands/toggleList.ts
With this PR we try to join lists if possible on `toggleList`.
https://user-images.githubusercontent.com/2500670/145576288-26314d76-49fc-4b70-b2a6-c0aebee3294b.mp4
https://user-images.githubusercontent.com/2500670/145576322-0bae810b-68bd-4c08-875e-10cc4bc2a906.mp4
fixes #1329
=> join lists on toggleList

packages/extension-floating-menu/src/floating-menu-plugin.ts
Right now, if any extension updates the editor state the `FloatingMenu` will become visible. In my opinion the `FloatingMenu` should only be visible when the user actually focuses the editor. I know that I can pass a custom `shouldShow` function to change the behaviour but I think it should also be the default behaviour.
=> fix: show FloatingMenu by default only if focused

packages/core/src/extensions/keymap.ts, packages/extension-code-block/src/code-block.ts
With this PR we try to improve backspace handling in two cases
1. Convert an empty node to the default node when pressing backspace at the start of the document.
2. After pressing `cmd+a` and `backspace` the node is converted to the default node
fixes #2281
preview: https://deploy-preview-2284--tiptap-embed.netlify.app/preview/Examples/Default
=> Improve backspace handling

packages/react/src/useEditor.ts
This is a fix for #2182 - it makes sure that the editor is available on the first render of `useEditor` in the react package.
The reason for this fix is that the first render never has an editor and that causes the page's content to jump and flash. First render has no editor, so nothing is rendered. Then the second render has the editor and the WYSIWYG editor is rendered causing all the content on the page to shift down.
The effect will also re-create the editor if anything in the deps list changes.
cc @philippkuehn
=> Make sure editor is available on first render

packages/react/src/BubbleMenu.tsx, packages/react/src/FloatingMenu.tsx
Changes to the `element.current` don't trigger `useEffect` rerender and shouldn't be used in the dependency array.
One discussion about this is for example here: https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom
It's also causing some subtle bugs when mounting and unmounting editors.
=> Remove `element.current` from `useEffect` in `BubbleMenu` and `FloatingMenu`

demos/src/Nodes/Mention/Vue/suggestion.js
A comment clarifying the difference between using vue 2 and 3 when passing props to VueRenderer in Mention plugin
A reason - it tooks me hours to realize that I need not only use this:
```
parent: this,
propsData: props,
```
for vue 2 but remove that as well:
```
props,
editor: props.editor,
```
It led to a performance issue - a tab freezed in my case when adding some mentions
=> Using vue 2 and 3 when passing props to VueRenderer in Mention plugin

docs/guide/typescript.md
=> Fix typos in typescript.md

docs/installation/vue3.md
Another newly added feature to Vue 3 has been the addition of the [setup script syntax](https://v3.vuejs.org/api/sfc-script-setup.html). Feels like it might be good to add this as another possible installation method.
=> Added setup script syntax to Vue 3 install docs

packages/react/src/ReactRenderer.tsx
This PR modifies the ReactRenderer types so that they are no longer tied to the `mention` example.
#2011 makes the `ComponentType` require `items[]` and a `command` in the props, but the ReactRenderer does not make the same assumption. 
I think this should also make it possible to change the type of `props` in the `ReactRenderer` class to `P`, and similarly in the function definition for `ReactRenderer.updateProps`. But I wanted this to be a minimal change so I just fixed the issue in the `ComponentType` type definition.
=> change reactrenderer component type definition

docs/installation/vue3.md
npm run dev --> npm run serve
"dev" used to be in the CLI for Vue 2 but has since been removed with Vue 3
see: https://stackoverflow.com/questions/51664680/how-to-solve-npm-err-missing-script-dev/52694160
=> Vue3 CLI doesn't have "npm run dev"

packages/extension-heading/src/heading.ts
Export type `Level` to externally work with levels that are passed to the `setHeading` and `toggleHeading` commands, instead of only being able to pass literal numbers.
Example:
```
// where `selectedHeadingLevel` shall be of type `Level` and changes as part of other logic
this.editor.commands.toggleHeading({ level: this.selectedHeadingLevel })
```
=> fix: export type `Level` for external use

packages/core/src/ExtensionManager.ts, packages/core/src/InputRule.ts, packages/core/src/PasteRule.ts, packages/core/src/inputRules/markInputRule.ts, packages/core/src/inputRules/nodeInputRule.ts, packages/core/src/inputRules/textInputRule.ts, packages/core/src/inputRules/textblockTypeInputRule.ts, packages/core/src/inputRules/wrappingInputRule.ts, packages/core/src/pasteRules/markPasteRule.ts, packages/core/src/pasteRules/textPasteRule.ts
With this PR it’s possible to cancel inputRules and pasteRules. The issue is also described in #2225.
```js
new InputRule({
handler: ({ state, range, match }) => {
// cancel input rule when returning `null`
if (true) {
return null
}
const tr = state.tr
// otherwise always return a transaction
return tr
}
})
```
Pasterules work slightly differently because a match can appear in several nodes at the same time. When returning `null`, the rule for all occurrences is not applied.
fixes #2348
=> add way to cancel inputrules and pasterules

packages/core/package.json, packages/react/package.json
Hi Tiptap people! 👋
I created a PR directly instead of an issue because the diff is quite small. Feel free to close this if undesired. 😊
As far as I understand, Tiptap doesn't rely on global side effects anywhere within the packages `@tiptap/core` and `@tiptap/react` (I didn't check the other packages). I added `sideEffects: false` to both package.jsons to indicate to app bundlers (primarily webpack and rollup) that unused exports within those packages can be removed safely from the final bundle. That's especially useful for large packages like `@tiptap/react` and `@tiptap/core`.
More info: https://webpack.js.org/guides/tree-shaking
=> Mark `@tiptap/react` and `@tiptap/core` as side effect free

docs/installation/nuxt.md
Minor adjustments so that the example doesn't need tinkering to run in latest default Nuxt installation.
Line 38: Nuxt does not use a src folder by default & convert name to multi-word to avoid naming convention errors.
Line 83: Removed id attribute from page container div. Nuxt adds its own id="app" to the app root container.
Line 85:  Convert name to multi-word to avoid naming convention errors.
Line 89: Import component before use, component autoload occasionally fails.
Line 91: Fix typo client-only
=> Nuxt specific corrections

packages/extension-table/src/table.ts
This PR will update the tables extension to use the `toggleHeader` command instead of the deprecated `toggleHeaderColumn` and `toggleHeaderRow` commands from `prosemirror-tables`. This is a **breaking change** because the commands will now only change the first column or row, respectively, instead of the row(s) or column(s) in the current selection. See the attached videos for examples.
The exception to the changes is `toggleHeaderCell`. I'm not sure what we'd like to be done with it and am looking for some feedback. Currently, it toggles any cell(s) in the selection to be "header cells". This is the deprecated behavior in `prosemirror-tables`. If we change it to use `toggleHeader`, then it will only toggle cells that are within the first row or column and, even then, it will only …
=> fix: use toggleHeader from prosemirror-tables

docs/api/commands/focus.md
A pretty small fix. The word `boolean` was misspelled.
=> Fix: Typo in Focus Command Documentation of Editor

packages/extension-placeholder/src/placeholder.ts
I propose passing hasAnchor to custom placeholder callbacks. In this way, custom placeholder functions can show placeholders for some nodes only when the cursor is in there, and for other nodes always show the placeholder
=> expose hasAnchor to custom placeholder function

packages/extension-bold/src/bold.ts, packages/extension-italic/src/italic.ts, packages/extension-underline/src/underline.ts
This way, key bindings 'Mod-B', 'Mod-I' and 'Mod-U' with active caps
lock have the same effect as their lowercase siblings.
Prosemirror examples did the same, see ProseMirror/prosemirror#895
Fixes: #2426
Signed-off-by: Jonas <jonas@freesources.org>
=> Add key bindings for uppercase letters for bold, italic and underline

docs/api/extensions/typography.md, packages/extension-typography/src/typography.ts
The Typography extension is a great extension, but it's not very customizable. It's all or nothing for the included input rules, and this doesn't really work for us. We want some rules enabled, but all of them. I thought it would be nice if the extension could be fully configurable, allowing one to disable specific rules if one desires.
Hopefully this is something you agree with including in the official extension, otherwise we'll have to maintain our own version of this. Which is not a big deal, but it would be awesome if this could be integrated 😀
=> Allow individual Typography rules to be disabled

packages/core/src/extensions/keymap.ts
Fixes https://github.com/ueberdosis/tiptap/issues/2685 by removing the Home/End keybindings in the PC keymap.
This was similarly removed in Prosemirror at https://github.com/ProseMirror/prosemirror-commands/commit/20371c58, to favour default browser / OS behaviour.
Note: This behaviour continues to be preserved on Mac under the `Ctrl-a` and `Ctrl-e` keys
For users who wish to preserve this behaviour, they can achieve this via a custom extension:
```javascript
const CustomKeyboardBehaviour = Extension.create({
addKeyboardShortcuts() {
return {
['Home']: () => this.editor.commands.selectTextblockStart(),
['End']: () => this.editor.commands.selectTextblockEnd(),
}
}
})
const editor = new Editor({
extensions: [
// Register your custom extension with the editor.
CustomKeyboardBehaviour,
]
}); …
```
=> fix: don't override behaviour of Home / End in pc keymap

packages/extension-bubble-menu/package.json, packages/extension-floating-menu/package.json
This is very similar to https://github.com/ueberdosis/tiptap/pull/2361, but also adds `sideEffects: false` to `@tiptap/extension-bubble-menu` and `@tiptap/extension-floating-menu`, which are `@tiptap/react` dependencies.
Without this change, importing anything from the `@tiptap/react` pulls and bundles the whole package, even if we are not using the `BubbleMenu` or the `FloatingMenu` components.
For reference: https://webpack.js.org/guides/tree-shaking
=> fix: Mark the bubble/floating menu extensions as side effect free

packages/suggestion/src/suggestion.ts
The suggestions extension will continue to react to selection changes even when the editable is "readonly", which can lead to it showing a pop-up for text that start with the trigger character. This was discovered in https://github.com/ueberdosis/tiptap/issues/2680.
See the demo below:
https://user-images.githubusercontent.com/38820281/162368119-7b98076b-af09-47e6-a301-fffdbbb11570.mov
We need to ensure we don't attempt to detect a suggestion at the current selection when isEditable is false. The attached commit will fail-fast and cleanup any active suggestion state. Demo:
https://user-images.githubusercontent.com/38820281/162368748-50c49488-8749-485b-98e6-eab2ffe37da7.mov
=> fix: prevent suggestions from being active when editor is readonly

packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
Problem: The bubble menu's position currently depends on prosemirror selection, which works well for inline elements. But for block level elements, like code blocks, if we want to show a bubble menu to do things like change the language of the code block or to delete the code block, it would be ideal to have the bubble menu stick to the top left of the code block, for example. 
Solution: Allowing overriding `getReferenceClientRect` along with other `tippyOptions` solves this problem and allows customizing the position of tippy outside of the plugin.
=> fix: Allow tippyOptions.getReferenceClientRect in bubble menu to be overridden

packages/extension-task-item/src/task-item.ts
This PR fixes #2688 by updating the input rule for task items.
=> fix: allow [] as a prefix for task items

packages/vue-2/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueNodeViewRenderer.ts
This PR add `as const` to every `required` options in `nodeViewProps`.
Resolved #2654 
1. run `yarn rollup -c --scope @tiptap/vue-2` and `yarn rollup -c --scope @tiptap/vue-3`
2. Then verify the typing is
```typescript
export declare const nodeViewProps: {
editor: {
type: PropType<import("@tiptap/core").Editor>;
required: true;
};
// ...
}
```
instead of:
```typescript
export declare const nodeViewProps: {
editor: {
type: PropType<import("@tiptap/core").Editor>;
required: boolean;
};
// ...
}
```
=> fix: improve Vue nodeViewProps typing

packages/extension-character-count/package.json
Remove the `@tiptap/extension-text-style` peer depencies from `@tiptap/extension-character-count`, the code of character-count does not seems to use it.
I noticed the issue when I added the `@tiptap/extension-character-count` to my project I saw the following log printed by pnpm:
```
├─┬ @tiptap/extension-character-count
│ └── ✕ missing peer @tiptap/extension-text-style@^2.0.0-beta.1
```
=> fix: remove extension-text-style from character-cout peer dependencies

packages/extension-link/src/link.ts
Currently editors using the link extension are vulnerable to XSS using `insertContent` and `insertContentAt`. It allows attackers to run arbitrary javascript code on a victims machine when they click a given link.
```js
editor.commands.insertContent('<a href="javascript:alert(1)" target="_self" rel="">Malicious link</a>')
```
This issue can be avoided by not parsing `javascript:` pseudo-protocol.
=> fix(extension-link): prevent parsing `javascript:` pseudo-protocol

packages/vue-3/src/VueNodeViewRenderer.ts
With this PR it’s possible to use CSS Modules (`<style module>` in SFC).
=> Add support for CSS Modules

packages/suggestion/src/suggestion.ts
This simple change provides `onBefore*` handlers to the render function, allowing one to start rendering a loading spinner, for instance, while waiting for async items to be received from a backend service.
A working demo can be found here:
* https://codesandbox.io/s/tiptap-pr-2628-k7yure
---
With this change, the meaning of each handler now becomes:
* `onBeforeStart`: Invoked **once** as soon as the user types the suggestion trigger character
* **Async:** This is where a dropdown would be first rendered with a loading spinner
* **Not-async:** There's no use for this handler in this situation (can be omitted)
* `onStart`: Invoked **once** as soon as the first results from the async call are received
* **Async:** This is where a dropdown would be updated with the first results (replacing …
=> feat: Add `onBeforeStart` and `onBeforeUpdate` handlers to the render function

packages/suggestion/src/suggestion.ts
Provides a generic type for suggestion items, defaulting to `any` as before (no breaking change).
=> feat: Add a generic type for suggestion items

packages/extension-table/package.json
This PR declares the `prosemirror-model`, and `prosemirror-state` packages as dependencies of the `@tiptap/extension-table` package. Doing this indicates to rollup that it should not build these dependencies into the distribution files of the `@tiptap/extension-table` package.
In turn, this change dramatically reduces the build size of the `@tiptap/extension-table` package. 
I noticed that the esm build of the table extension is 214kb, and most of the code is contributed by the prosemirror dependencies. You can see here: https://unpkg.com/browse/@tiptap/extension-table@2.0.0-beta.48/dist/tiptap-extension-table.esm.js
After applying this change, the esm build is only 11kb 🎉
=> Reduce bundle size of @tiptap/extension-table package

packages/suggestion/package.json
Fixes usage with Yarn v3
Currently getting the following error with Yarn v3:
```
../../.yarn/__virtual__/@tiptap-suggestion-virtual-e0732a477f/0/cache/@tiptap-suggestion-npm-2.0.0-beta.91-99c28c4aaa-cc6919a224.zip/node_modules/@tiptap/suggestion/dist/packages/suggestion/src/findSuggestionMatch.d.ts:2:29 - error TS7016: Could not find a declaration file for module 'prosemirror-model'. '/Users/dylanhuang/Git/beatthemarket/.yarn/cache/prosemirror-model-npm-1.16.1-61853f0125-76718aafbf.zip/node_modules/prosemirror-model/dist/index.js' implicitly has an 'any' type.
If the 'prosemirror-model' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prosemirror-model'
2 import { ResolvedPos } from …
```
=> Update Suggestion package.json

packages/suggestion/src/findSuggestionMatch.ts
Problem: @tiptap/suggestion's `findSuggestionMatch` only works when inline nodes are leaves. When you have an inline node with content, in our case a footnote modeled off of https://prosemirror.net/examples/footnote/, suggestions after that node are broken.
This happens because the current logic relies on `textBetween` returning a string whose length exactly matches the absolute position range of the node. This is true with text nodes, as well as leaf nodes like a mention, but not a content node like footnote because its opening/close take up position spaces.
Solution: I don't think textBetween on the entire parent node is actually needed here. Just looking at the text node immediately before the suggestion fixes the problem and seems simpler as well.
=> fix: Support inline nodes with content in @tiptap/suggestion

packages/extension-link/src/link.ts
While you can set a default value for the Link extensions class attribute using 
```javascript
Link.configure({
HTMLAttributes: {
class: 'my-custom-class',
},
})
```
It is currently not possible to dynamically set the class attribute when calling setLink() e.g. 
```javascript
this.editor.chain().focus().extendMarkRange('link').setLink({href: url, class: 'this class should be added'}).run();
```
This change allows for that by default, without needing to extend the Link extension. E.g. https://github.com/ueberdosis/tiptap/issues/72#issuecomment-1118287785
=> Allow class attribute through setLink()

packages/core/src/NodeView.ts
NodeView's onDragStart assumes the event is a DragEvent.
In React, the event is usually a SyntheticBaseEvent, which doesn't have offsetX/offsetY properties.
To get the offsetX/offsetY properties, have to use event.nativeEvent, which is the DragEvent.
Without this fix, x and y become NaN in React.
=> fix: properly calculate setDragImage position

packages/vue-2/src/VueNodeViewRenderer.ts
Currently, if you attempt to register a component via `Vue.component()` with a different global instance of Vue (this can happen if you are building plugins for an existing application and the plugin and application exist in separate bundles) the component will not be found via the `Vue` imported into VueNodeViewRenderer.
In an ideal world, when attempting to `Vue.extend()` a component via the VueNodeViewRenderer.. (for example):
```
Node.create({
addNodeView() {
return VueNodeViewRenderer(uiForNodeComponent)
}
})
```
then the provided `uiForNodeComponent` will be `Vue.extend()`ed by a Global Vue that has access to any previously registered (`Vue.component(...)`) components.  The only way to ensure this in a situation where there might be multiple Global views (multiple bundles with Vue), …
=> Ensure VueNodeViewRenderer will use Editor's Global Vue Instance

docs/api/editor.md, packages/core/src/Editor.ts, packages/core/src/types.ts, packages/core/src/utilities/createStyleTag.ts
Hi,
I noticed that tiptap injects a style element into the page's `head`. This breaks when using a Content Security Policy that disallows `unsafe-inline`, as there is currently no way to add a `nonce` to the dynamic style element.
As the injected CSS is in a typescript file and not a CSS file, there is no easy way to include it in the application bundle, and it differs from the default `prosemirror.css`. 
To resolve this, I added an option called `injectNonce` to tiptap which, when set, adds a `nonce` attribute to the dynamic style element.
Another solution would of course be to refactor the style into a CSS file which can be imported alongside tiptap, avoiding the dynamic element entirely, but that would probably require more code changes. 
Additionally, the `injectNonce` option could be …
=> add support for CSP nonces in createStyleTag

packages/core/src/helpers/getTextBetween.ts, packages/core/src/types.ts
This PR gives `TextSerializer` access to the range that is being serialized.
Rationale: Without it, custom text nodes can't serialize partial content (based on selection).
=> Expose "range" to textSerializer. Used in "getTextBetween"

packages/core/src/helpers/getAttributesFromExtensions.ts, packages/core/src/types.ts
Problem: When using Tiptap, there's no way to mark a Node/Mark attribute as required. Tiptap sets `default: null` for every attribute, and there's no way to clear this if you want an attr to be required. This causes downstream issues - for example, ProseMirror's `joinBackward` command may try to create a wrapping with a node that has a required attribute, without knowing how to fill it in. ProseMirror tries to guard against this using the NodeType's [hasRequiredAttrs](https://prosemirror.net/docs/ref/#model.NodeType.hasRequiredAttrs) method, but when using Tiptap it will always return `false`.
Solution: Add a new, optional, `isRequired` option on attrs. If an attr is set up with this property, and no default, then the `default: null` will be deleted and then ProseMirror's …
=> feat: Required attributes

packages/extension-image/src/image.ts
This only allows the image input rule to be triggered:
* At the start of a paragraph/line
* If it has a preceding space
This prevents the rule from triggering when one is typing the image Markdown syntax inside an inline code mark.
https://user-images.githubusercontent.com/96476/170526204-0fb7681d-a416-484e-9d9b-69982cf6c39a.mp4
https://user-images.githubusercontent.com/96476/170525738-02364be4-3823-4228-8ad5-52fe12b6b73d.mp4
=> fix: Only trigger image input rule at the start or with a preceding space

packages/vue-2/src/VueRenderer.ts
Problem: Extending a VueConstructor / Vue constructor function in development will throw a Vue.warning of `Do not use built-in or reserved HTML elements as component id a`.
More details: This particular constructor is called via `VueNodeView.mount()`, this is the only place it is called from. That particular method ensures that a `VueComponent` function (constructor) is passed to the `VueRenderer`.
see: https://github.com/ueberdosis/tiptap/blob/main/packages/vue-2/src/VueNodeViewRenderer.ts#L103-L106
=> In Vue 2 VueRenderer, only Vue.extend() non-VueConstructor arguments

demos/src/Examples/Community/React/suggestion.js, demos/src/Examples/Community/Vue/suggestion.js, demos/src/Experiments/Commands/Vue/suggestion.js, demos/src/Nodes/Mention/React/suggestion.js, demos/src/Nodes/Mention/Vue/suggestion.js, packages/suggestion/src/suggestion.ts
This commit makes the clientRect prop optional - this means that this value can be null. This allows developers using the suggestion extension to know that they have to implement a check for the clientRect before using it.
I think this is the correct way to handle this issue. Instead of building around it, we let the developer know that a clientRect **could** be potentially not defined, specially when the rendering is to slow and the DOM element for example does not exist.
See #2795 for more information.
=> fix(suggestion): :bug: make clientrect prop optional

docs/api/marks/link.md, packages/extension-link/src/link.ts
This pull request adds custom protocols to extension-link. Previously, only urls beginning with http & https are recognized. Now it is possible to do the following:
```javascript
Link.configure({
protocols: ['ftp']
})
```
And ftp:// links will be automatically recognized and turned into hyperlinks.
The registration of custom protocols uses the builtin function `registerCustomProtocol` of linkifyjs, which is already used by the extension. 
Docs are updated as well.
=> Add support for custom protocols in extension-link

packages/extension-color/src/color.ts, packages/extension-font-family/src/font-family.ts
When having another extension reusing textStyle base extension (like one we use for text size) and we just use textSize on a node without color class, it fails at parsing it back to JSON at the color extension (we really need both, and many others in case of future contribution extensions to Tiptap).
Example HTML to send into `generateJSON(html)`:
```html
<p>Take a pictures <span style="font-size: 1.25rem;line-height: 1.75rem">hello world, this won't work</span> </p>
```
Example code of the extension we've (I'll open source it soon):
```ts
import { Extension } from '@tiptap/core'
import '@tiptap/extension-text-style'
export type TextSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl'
export const TEXT_SIZE_CLASS_MAP: Record<TextSize, string> = {
sm: 'font-size: …
```
=> fix(textStyle): Null-safe parseHTML getting no color/fontFamily from HTMLElement styles

demos/package.json, docs/api/nodes/code-block-lowlight.md, package-lock.json, packages/extension-code-block-lowlight/package.json, packages/extension-code-block-lowlight/src/code-block-lowlight.ts, packages/extension-code-block-lowlight/src/lowlight-plugin.ts, tests/cypress/integration/extensions/codeBlockLowlight.spec.ts
This PR declares the `lowlight` package as a peerDependency and removes the direct import statement in the `@tiptap/extension-code-block-lowlight` package. 
The client application can’t control which version of `lowlight` is bundled into the final product even when the client application provides its own lowlight instance. A consequence of this situation is that using a newer major version of lowlight ends up forcing the client application to bundle two versions of lowlight/highlight.js/fault in the final distribution build. That‘s a lot of dead JavaScript code. 
The main purpose of this change is reducing the bundle size of this extension by removing the duplication of lowlight versions in the codebase.
=> Declare lowlight as a peerDependency in `@tiptap/extension-code-block-lowlight`

packages/react/src/NodeViewContent.tsx, packages/react/src/NodeViewWrapper.tsx
=> Allow setting `whiteSpace` style for `NodeViewWrapper` & `NodeViewContent`

docs/installation/php.md
The `->wire('...')` alone will output the entire attribute string. We only want
the `->value()` portion.
=> docs: fix livewire attribute

packages/core/src/helpers/getTextContentFromNodes.ts
Hopefully this PR fixes https://github.com/ueberdosis/tiptap/issues/2937
Since `node.textContent` always looks at the entire text of the node, the desired behavior worked out well at the end but not once the position is somewhere else within the text.
I replaced it with [nodeBefore](https://prosemirror.net/docs/ref/#model.ResolvedPos.nodeBefore) 
> Get the node directly before the position, if any. **If the position points into a text node, only the part of that node before the position is returned.**
=> fix(core): only respect text of node before current position (#2937)

packages/core/src/commands/setContent.ts
closes #2846
prosemirror added a new warning when a selection is created that is not pointing into an inline node. This PR is fixing that warning on `commands.setContent` via not using a new Selection replacement but just replacing the current documents content from `0` to `document.content.size` with the new Document created.
=> fix(core): dont use selection for setContent replacement

docs/installation/alpine.md
The docs about the installation with Alpine.js is not compatible with version 3.
Should help with https://github.com/ueberdosis/tiptap/issues/1515
Also the default [Vite port](https://vitejs.dev/config/server-options.html#server-port) changed.
Thanks to @EasterPeanut
=> docs: update alpine installation

packages/core/src/PasteRule.ts
This is a fix for #2939
PasteRule's appendTransaction plugin method looks for a changed range by comparing the before/after state using `findDiffStart` and `findDiffEnd`.
The range is passed to `state.doc.nodesBetween` and then `node.textBetween`. findDiffStart/end appear to handle node positions differently.
This is already accounted for in the `from` argument (using `Math.max(from - 1, 0)`), but there was no such offset for `to`, so all paste rules receive one extra character at the end, unless the content was pasted at the end of a node (so this also can't be solved in userspace easily).
=> Fix pasteRulesPlugin always adding one extra character to text range

packages/core/src/CommandManager.ts
Fixes #3025 — see that issue for all the details.
=> fix(core): createCan command props shouldn't try dispatch (#3025)

packages/core/src/commands/setNodeSelection.ts
Fixes #3090.
This doesn't regress #1588, as that bug was only in the `focus` command.
=> fix(core): setNodeSelection should not clamp pos by Selection.atStart/atEnd

packages/suggestion/src/suggestion.ts
Current use of ```document.querySelector``` breaks the extension when using the editor in shadow dom.
=> Make Suggestion extension use view.dom instead of document

packages/core/src/Editor.ts
This emits the onUpdate function when the editable state of the editor is changed via `setEditable`
should help with #2850
=> fix(core): make setEditable trigger onUpdate function

packages/react/src/ReactRenderer.tsx
After switching to `React 18 createRoot() API`, we met the selection bug for the block using react custom node view.
https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.ts#L420
When prosemirror wants to update the dom selection, if the `anchorNode` points to a react portal dom, it is still not mounted (`anchorNode.isConnect` equals false). This will cause the selection to stay in the position before when create a new block with the react node view. 
For example, extending the paragraph with react node view and pressing Enter at the end of the document will reproduce this bug.
After digging the code, I think the bug comes from https://github.com/ueberdosis/tiptap/blob/main/packages/react/src/ReactRenderer.tsx#L80-L88
After React 18 updates inside of timeouts, promises, …
=> fix: fix React Node View render problem in React 18

packages/core/src/Editor.ts
Followup to https://github.com/ueberdosis/tiptap/pull/2935#issuecomment-1231009792. This makes `setEditable` fire an `update` event through the `EventEmitter` API, rather than calling `options.onUpdate` directly. This is more consistent with the rest of the code, and allows things like node views to use `.on('update', ...)` to start watching the status of `isEditable` after the editor has been created.
=> fix(core): make setEditable trigger all 'update' listeners

packages/extension-subscript/README.md
Adjustment of the subscript extension documentation from `superscript` to `subscript`.
=> docs: fix naming

packages/extension-bubble-menu/src/bubble-menu-plugin.ts
Before the bubble menu would flicker when selecting styles
---------
Afterwards the bubble menu stays visible when selecting styles
=> Include bubble menu element when checking if the editor view still has focus

demos/package.json, demos/src/Examples/CodeBlockLanguage/React/index.jsx, demos/src/Examples/CodeBlockLanguage/Vue/index.vue, demos/src/Experiments/All/Vue/index.vue, demos/src/Nodes/CodeBlockLowlight/React/index.jsx, demos/src/Nodes/CodeBlockLowlight/Vue/index.vue, package-lock.json, packages/extension-code-block-lowlight/package.json
Closes https://github.com/ueberdosis/tiptap/issues/2880
Lowlight now has TS types in the package itself. This PR bumps to latest 2.7.0, and removes the @types package which is very out of date and actively prevents developers from using current version of lowlight (because @types always takes precedence over built in types, causing TS to throw errors, see https://github.com/ueberdosis/tiptap/issues/2880
We may also choose to leave lowlight at 1.2.0, but without @types built-in, it would add friction to devs who want to plug-and-play the CodeBlockLowlight extension. IMO updating to 2.7.0 preserves this single npm install experience.
FWIW the docs are a little confusing, the currently claim that:
> You should provide the lowlight module to this extension. Decoupling the lowlight package …
=> fix(extension-code-block-lowlight): Bump lowlight to 2.7.0, remove outdated @types

packages/core/src/pasteRules/nodePasteRule.ts
This PR is meant to fix #2942
Using `nodePasteRule` the Node would be added at the end of the editor.
This PR replaces `insertContent` with `insertContentAt` to insert the Node at the matched position instead.
=> fix(core): insert PasteRule Node at matched position (#2942)

packages/extension-placeholder/src/placeholder.ts
Cover case where doc is empty but no descendants (custom doc that mimics an input). Add `emptyEditorClass` to the ProseMirror dom element instead.
Also not required to call `this.editor.isEmpty` repeatedly in descendants, or call it multiple times. Instead, cache empty top node and use ProseMirror `diffStart` to do a quick compare.
=> add-empty-editor-class-to-root-div

packages/react/src/ReactRenderer.tsx
To avoid seeing the `Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.` error, we need to move the `flushSync()` code that avoids automatic batching to a microtask to not fire a lifecycle event `setState()` during rendering.
Fixes warning introduced in #2985
=> fix: move React `flushSync` to microtask

demos/src/Extensions/BubbleMenu/React/index.jsx, demos/src/Extensions/BubbleMenu/React/styles.scss, demos/src/Extensions/BubbleMenu/Vue/index.vue, demos/src/Extensions/FloatingMenu/React/index.jsx, demos/src/Extensions/FloatingMenu/Vue/index.vue, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
=> Fix bubble menu and floating menu being available when editor is not editable

packages/extension-code-block-lowlight/src/lowlight-plugin.ts
Lowlight's `lowlight.listLanguages` does not support `alias`.
So, for example, if you use `alias` called `js`, it is not parsed properly.
Currently, a method called `registered` exists in the lowlight 2 version, but it does not exist in the 1 version, so this part is directly implemented.
Please check and merge.
=> feat: Add alias condition to code-block-lowlight

demos/src/Examples/AutolinkValidation/React/index.jsx, demos/src/Examples/AutolinkValidation/React/index.spec.js, demos/src/Examples/AutolinkValidation/Vue/index.spec.js, packages/extension-link/src/helpers/autolink.ts
Made a change to the autolink plugin for extension-link to only autolink after hitting space, which is a more common behavior on WYSIWYG editors. I wanted to also remove the auto-"unlinking" feature, as this is also not a common behavior, but I figured I wouldn't change this in this PR unless requested
Fix #3225
=> feat(extension-link): Change autolink to only apply after breaking a word

package-lock.json, packages/core/package.json, packages/extension-bubble-menu/package.json, packages/extension-character-count/package.json, packages/extension-code-block-lowlight/package.json, packages/extension-code-block/package.json, packages/extension-collaboration/package.json, packages/extension-floating-menu/package.json, packages/extension-focus/package.json, packages/extension-gapcursor/package.json, packages/extension-history/package.json, packages/extension-horizontal-rule/package.json, packages/extension-link/package.json, packages/extension-mention/package.json, packages/extension-placeholder/package.json, packages/extension-table/package.json, packages/extension-task-item/package.json, packages/html/package.json, packages/react/package.json, packages/suggestion/package.json, packages/vue-2/package.json, packages/vue-3/package.json
This PR updates all prosemirror packages to the most recent version + also brings back fixed versions at the minor level.
If we see increased problems with minor versions breaking Tiptap again - we'll consider to go more strict with the version fixing again.
=> chore(maintainment): :rocket: update prosemirror packages

demos/src/Examples/Default/React/index.jsx, demos/src/Examples/Default/React/index.spec.js, demos/src/Examples/Default/Svelte/index.svelte, demos/src/Examples/Default/Vue/index.vue, packages/core/src/commands/setMark.ts, tests/cypress/integration/core/can.spec.ts
Previously, setting marks did no schema validation checks for dry runs (like the `.can()` command). The `setMark` raw command will now properly check if the mark is possible to be set given the editor node/mark schema.
The logic was added is similar to the private `markApplies` method used internally by ProseMirror's `toggleMark` command but with additional functionality to support stored cursor marks and mark exclusions.
fix #3057
=> fix(core): Can() does not work for setting marks

packages/extension-link/src/helpers/autolink.ts
=> Ensure text blocks exist before referencing them

packages/core/src/helpers/getAttributesFromExtensions.ts
This PR avoids a runtime error that happened when an attribute was set as undefined or null, as highlighted in issue #3032 .
=> fix(core) - support attributes being null/undefined 

packages/suggestion/src/suggestion.ts
=> fix: set default allowedPrefixes null

packages/extension-link/src/helpers/autolink.ts
This PR fixes the lastWordBeforeSpace value to not be passed through the autolink plugin when it is undefined. This can happen, when the filtered `wordBeforeWhitespace` array has a length of 0 since `lastWordBeforeSpace` is set to `wordsBeforeWhitespace.length - 1` which would result in an index of -1.
=> fix(extension/link): fix last word value being undefined

docs/api/nodes.md
The source code link of the YouTube node in the list of supported nodes linked to the wrong page.
=> docs: link YouTube node docs to proper GitHub url

docs/examples/drawing.md
Fixed typo in drawing.md docs, want -> wanted
=> fix: typo in docs

packages/extension-link/src/link.ts
I'm was getting these warnings after pasting links and then destroying and creating a new editor again:
```
linkifyjs: already initialized - will not register custom protocol "ftp" until you manually call linkify.init(). 
To avoid this warning, please register all custom protocols before invoking linkify the first time.
```
With the extension being called like this:
```
Link.configure({
protocols: ['ftp', 'mailto']
})
```
Resetting linkifyjs when the editor is destroyed fixes this.
=> Cleanup linkifyjs when the editor is destroyed

README.md
The links were broken. This should also be handled from the DNS point of view, but for now this should fix the links.
=> Fix installation and examples link

packages/extension-placeholder/src/placeholder.ts
Fix #3360
The issue seems to be caused by this line in `placeholder.ts`:
https://github.com/ueberdosis/tiptap/blob/2b69f344c713befecd4ec606df5e9ba680aa2ce8/packages/extension-placeholder/src/placeholder.ts#L54
`isEmpty` is NOT a simple operation, but uses JSON stringify on the entire document to verify emptiness compared to the default of the given node type.
This wouldn't be too bad on it's own, but it's called for every descendent, causing noticeable performance issues if more than a few empty paragraphs exist on a large document (even on the Moby Dick large text example).
The issue was actually fixed with https://github.com/ueberdosis/tiptap/pull/2665 but was then reverted by https://github.com/ueberdosis/tiptap/commit/10248924541d7b9414087a7369dad24b24fe9b11 for an unknown reason …
=> fix(extension/placeholder): Resolve placeholder performance issues

demos/src/Extensions/BubbleMenu/React/index.jsx, demos/src/Extensions/BubbleMenu/Vue/index.vue, docs/api/extensions/bubble-menu.md, package-lock.json, packages/extension-bubble-menu/package.json, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-bubble-menu/src/bubble-menu.ts, packages/react/src/BubbleMenu.tsx, packages/vue-2/src/BubbleMenu.ts, packages/vue-3/src/BubbleMenu.ts
This pull requests implements a debounce to the BubbleMenu plugin which allows developers to control how the bubble menu is shown.
It includes the `debounce` function from lodash which is imported directly without importing the whole lodash package which should keep the bundle size low.
See #1493 
Closes #1493
Closes #1313
=> refactor(extension/bubble-menu): add debounce to bubble menu updates

CHANGELOG.md
This PR fixes a variety of typos in [CHANGELOG.md](https://github.com/rvrvrv/tiptap/blob/bf37a5919d906dbd8359e4815f1df159979bd106/CHANGELOG.md).
=> docs: Fix typos in CHANGELOG.md

packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
Fixes: #3365 
We are adding event listener for blur on tippy element but we aren't removing it during `destroy`
This PR adds the invocation to remove the said event listener.
=> fix: remove blur event listener from tippy element (#3365)

docs/installation/svelte.md
While going through the docs, I noticed the Svelte docs linked to the Vue docs on how to get started.
I've also updated the commands to create a new SvelteKit project, according to the official docs.
=> docs(svelte): fix link to get started with svelte

packages/react/src/Editor.ts, packages/react/src/EditorContent.tsx, packages/react/src/ReactRenderer.tsx
This fixes the cursor problem described in #3200.
Node views need to be rendered immediately when they're created so that the editor can correctly position the cursor inside them. That's achieved using `flushSync` whenever a new node view renderer is added.
However, `flushSync` cannot be used from inside a React component lifecycle method. Thus #3188 moved the `flushSync` call into a microtask. This delays the `flushSync`, and so the editor can't correctly position the cursor inside the new node view, because it doesn't exist in the DOM yet.
By keeping an instance variable to determine if initialization has happened, we can avoid using `flushSync` from inside the `componentDidMount` and `componentDidUpdate` methods, and still call it whenever a new node view is created afterwards.
I added …
=> Fix cursor not following to new node when using a react node view

packages/extension-link/src/link.ts
=> fix(link): allow to unset target attribute

packages/core/src/helpers/generateText.ts
Fixes https://github.com/ueberdosis/tiptap/issues/3538
=> Fix: custom text serializers should override text serializers defined in the schema

docs/api/extensions/placeholder.md
It was previously not clear that additional CSS was required to display placeholders, as discussed in #2659.
=> Added CSS Required for Setup

packages/core/src/pasteRules/nodePasteRule.ts
Hello team!
First off, thank you for building and maintaining `tiptap`, it is truly a pleasure to work with.
While working on our editor, we ran across `nodePasteRule` which we wanted to use with a non-regexp pattern.
The specs in `PasteRule.ts` doe also allow functions as argument for `find`, and functions actually work perfectly with `nodePasteRule` as well, but there will be a type error.
This PR changes the type of `nodePasteRule`'s `find` to the most general type it can accept.
I hope it's  OK to open a PR directly for this two-line change.
=> Extend `nodePasteRule` `find` type to most generic `PasteRuleFinder`

packages/extension-link/src/helpers/clickHandler.ts
Fixes a bug in which under certain conditions where multiple links are present, clicking one link will instead open a different link. Specifically, when the editor state shows one link as selected, clicking a different link will open the "selected" link instead.
See also https://github.com/ParabolInc/parabol/issues/7524 where this issue was initially reported for our web app.
The specific conditions in which editor state does not reflect the clicked link are:
* `openOnClick` is true
* Content is read-only - `editable` is false
As such, I recommend reviewers test with the following patch applied:
```
diff --git a/demos/src/Marks/Link/React/index.jsx b/demos/src/Marks/Link/React/index.jsx
index 53b3134a9..4cfb9b4f3 100644
--- a/demos/src/Marks/Link/React/index.jsx
+++ …
```
=> fix(extension-link): Click handler opens selected link instead of clicked link

packages/extension-typography/src/typography.ts
This PR should fix #3674 by implementing more strict regex expressions to catch only fractions with a whitespace char or the start of a newline.
closes #3674
=> fix(typography): dont create fractions in the middle of a string

packages/core/src/Editor.ts
Fixes https://github.com/ueberdosis/tiptap/issues/3670
=> fix: override schema text serializers if provided in getText options

docs/api/marks/link.md
The documentation mentions being able to override the `rel` on links but doesn't explain how. It also doesn't tell you how to remove the rel if needed(set to null).
Add an example of removing a default attribute and overriding one to a different value.
=> document removing or overriding link attributes

packages/react/src/EditorContent.tsx
Do the same thing as https://github.com/ueberdosis/tiptap/pull/3188 - confirmed this got rid of the warning locally
=> fix: Queue flushSync call

docs/installation/php.md
Changes are based on reading this thread https://github.com/ueberdosis/tiptap/issues/1515#issuecomment-896477157
The documentation example for Livewire relies on AlpineJS, which currently causes the editor property to be wrapped in an observable/reactive layer. Moving the editor out of the returned object means it doesn't become a proxy object; otherwise, `editor.commands.setContent(content, false)` will already trigger an error `Range Error: Applying a mismatched transaction` and not work.
=> Docs Update for Installation instructions for PHP Livewire

demos/src/Commands/InsertContent/Vue/index.spec.js, demos/src/Commands/InsertContent/Vue/index.vue, packages/core/src/commands/insertContentAt.ts
This PR fixes #2770 by checking the inserted text content if it's of type array. If so we can be sure that the content will be an array of text content.
=> fix(core): allow insertContentAt and insertContent text node arrays

demos/src/GuideNodeViews/ReactComponentContent/React/Extension.js, demos/src/GuideNodeViews/ReactComponentContent/React/index.jsx, packages/react/src/EditorContent.tsx
Inside the `ReactComponentContent` node view demo there was no way to add new components to test cursor behavior. This adds this functionality by using `Mod+Enter`.
This is related to #3781 as it was used to test the functionality this way.
=> chore: allow new ReactComponentContent components to be created

packages/core/src/NodeView.ts, packages/core/src/types.ts, packages/react/src/ReactNodeViewRenderer.tsx, packages/vue-2/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueNodeViewRenderer.ts
This PR should close #3772 by adding a new type called `DecorationWithType` which includes the default `Decoration` type coming from `@tiptap/pm/view` but includes the NodeType.
This way people can access the `decoration.type` property without experiencing typing issues.
=> fix: update typings for node view decorations

demos/src/Experiments/DestroyingEditor/Vue/index.vue, packages/core/src/Editor.ts
This PR should fix the issue #3798 
There should be no errors anymore if the view is not existent anymore.
close #3798
=> Fix destroyed view causing errors on dispatchTransaction

packages/core/src/extensions/keymap.ts
Currently Tiptap checks if the document is empty on almost every transaction using `doc.textBetween` which is quite expensive. This is not required most of the time because Select all + delete is a rare case. This PR moves the `doc.textBetween` based check after the other checks to it only runs when it is 100% that user has actually selected all the text.
=> Optimize empty document detection in `documentClear` plugin

demos/src/Experiments/Tailwind/JS/index.html
Heya,
I figured that using `sm:prose-base` makes more sense since the `prose` class is already set beforehand
=> fix: use prose-base class for sm screens 

docs/api/commands/toggle-list.md, packages/core/src/commands/toggleList.ts
When dealing with different variants of bullet lists, I wanted to adopt the same technique I used for different paragraph variants. Since `wrapInList` is capable of receiving attributes, just like `setNode` is, I don't see any reason why `toggleList` should not be capable of the same. 
Here's my bullet list extension in action that is in need of attributes support.
```js
export const CustomBulletList = BulletList.extend({
content: 'listItem*',
addAttributes() {
return {
variant: {
default: DEFAULT_LIST,
renderHTML: attributes => {
return {
class: `list-${attributes.variant}`,
};
},
},
};
},
addCommands() {
return {
toggleBulletList: attributes => (c) => {
return c.commands.toggleList(this.name, this.options.itemTypeName, true, attributes);
},
};
},
});
```
=> Adds attributes to toggleList

packages/react/src/ReactNodeViewRenderer.tsx, packages/react/src/ReactRenderer.tsx
This PR closes #2502 by adding the option to assign attributes to the React Renderer HTML Element.
=> feat(react): allow html attrs in react renderer

demos/src/Experiments/OnUpdateRerender/React/index.jsx, demos/src/Experiments/OnUpdateRerender/React/styles.scss, demos/src/Experiments/OnUpdateRerender/Vue/TiptapComponent.vue, demos/src/Experiments/OnUpdateRerender/Vue/index.vue, packages/react/src/useEditor.ts
This PR should solve issue #2403 by updating the editors event handlers when the event handlers are updated.
closes #2403
=> fix(react): allow updating event handlers on editor

packages/core/src/helpers/getAttributesFromExtensions.ts
> Sorry if you'd really prefer that I raise this as an issue first - it just seemed like a simple enough idea to demonstrate in a PR. If I've missed something in the public API that would otherwise solve the same problem, I'd appreciate some input. 
Resolve a `default` attribute thunk once when a node is created, in order to compute a default value dynamically.
I'd like to be able assign an attribute to a node that uniquely identifies it. 
```javascript
Node.create({
// ...
addAttributes() {
return {
id: {
default: () => generate_uuid(),
parseHTML: element => element.getAttribute('id')
}
}
}
})
```
=> [PROPOSAL] dynamic default attributes

demos/src/Extensions/BubbleMenu/React/index.jsx, package-lock.json, packages/extension-bubble-menu/package.json, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
This PR should close #1313.
Before this PR, the position for the bubble menu was always determined by the currently selected element (either the text positions or the node that was selected).
Since node views are usually wrapped by either:
1. A `data-node-view-wrapper` OR
2. A react node view renderer element
the positionings for the bubble menu could be mixed up when several positioning methods were used.
In the example of #1313 `float` was used to position said elements left/right of inline content which caused those wrapper elements to be of full-width, but have a height of `0`.
This PR now resolves this by checking the selected node - if the selected node contains a `data-node-view-wrapper` or is a node view wrapper, the **first child** of the node view will be picked as a reference …
=> Handle NodeViews in BubbleMenu positioning

demos/src/Experiments/IsolatingClear/React/index.jsx, demos/src/Experiments/IsolatingClear/React/index.spec.js, demos/src/Experiments/IsolatingClear/React/styles.scss, demos/src/Experiments/IsolatingClear/content.ts, packages/core/src/extensions/keymap.ts
This fix will solve the issue that when a cursor is **inside an isolating** node and the isolating node is empty, the nodes inside are not cleared similar to how they are cleared on the document.
Inside the `keymap.ts` we also check for the current textNodes parent (or direct parent if it is not a textNode) and if said parent is `isolating`. If we are inside an isolating node, we use the relative parentOffset to check that we're at the start of a node.
- Used an isolating node to test the behavior, nodes were cleared correctly
- Used it directly in the document: nodes were still cleared correctly
1. Create an isolating node
2. Add content
3. Make this content a headline
4. Use backspace to completely remove the content
5. Use backspace again to clear the headline and turn it back into a …
=> fix: clear nodes when cursor at start of empty isolating parent

.vscode/settings.json, demos/package.json, package-lock.json, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
This PR should close #3953 via checking if changes were made to the doc/selection and exiting before clearing the callback timeout.
Add a simple check before clearing debounced timeouts if the doc was changed.
I created a local demo with collab/cursors and a bubble menu and tested to create selections on both clients - worked fine, also with collab and collab cursors. the bubble menu delay was also working fine.
Follow the same steps as above
The additional file changes were made to:
1. Test yjs via webrtc locally
2. Add auto formatting for eslint in js/jsx files
- #3953
=> fix(bubble-menu): fix debounce not working with collab

packages/extension-link/src/helpers/autolink.ts
This PR changes the autolink behavior. Before links were always autolinked, even when the autolinked text was already a link. This is weird behavior - as a manually / already set link should always have priority over automatically linked content.
**Example:**
You have a link that has the textContent `mysite.com` but a link mark with a href attr to `https://mysite.com?ref=my-referral-id` the autolink prior to this PR would still autolink to `mysite.com` completely removing any manually set attributes.
Right before the autolink would set the link mark on words with spaces/breaks I added a check to see if the `link.from` and `link.to` already has a link mark inbetween. If so we just avoid autolinking to keep the already existing link.
- Local link demo
1. Check out this PR
2. Open the Link …
=> fix(link): fix links autolinking when not needed

docs/api/commands/focus.md
Fixes a typo in the focus page of the api documentation
```diff
- too
+ to
```
N/A
N/a
N/A
N/A
=> fix: typo in focus.md

docs/api/commands/toggle-node.md
Fixes a typo/missing word in docs page for toggleNode
```diff
- `toggleNode` will a node with another node.
+ `toggleNode` will toggle a node with another node.
```
n/a
n/a
n/a
n/a
=> fix: missing word in toggle-node.md

docs/api/commands.md
Fixes a typo in the commands doc page
```diff
- change
+ chain
```
n/a
n/a
If this isn't a typo, I apologize, but 'change' doesn't make sense in this context.
n/a
=> fix: typo in commands.md

packages/extension-link/src/helpers/autolink.ts, packages/extension-link/src/helpers/pasteHandler.ts
The link extension mistakenly inserted pasted content at wrong position in rc-4 https://github.com/ueberdosis/tiptap/blob/0e2df9d1f530bc7980a476afa269da29159d5892/packages/extension-link/src/helpers/pasteHandler.ts#L74
This handling was originally reserved for links and not for other types. 
A check has been introduced that dispatches the transaction only for pasting links.
It also prevents processing links in onPaste in code blocks.
Added a condition to only dispatch insert transaction if pasted content is a link fragment.
- Copy and paste any type of content (e.g. text). In RC-4 it got inserted at position -1. This should be fixed now. 
- Paste this into a code block: `<a href="https://www.google.com">Google</a>`
See above and below.
Before: …
=> Fix onPaste handling in link extension in rc.4

packages/core/src/NodeView.ts, packages/core/src/utilities/isAndroid.ts
Applied the same fix on iOS to Android, as Android appears to be having the same issue on enter
Credit to @Slapbox for finding the link to the existing fix made to iOS for the same issue.
N/A
Tested that both the React and Vue custom node view (w/content) examples worked on an Android device (Samsung Galaxy S22; Chrome)  and verified that hitting enter at the beginning, middle, or end of the custom node view works as expected
No tests were written. Doesn't seem reasonable/easy to test with cypress
fixes #2534
=> fix(core) 'enter' behavior on android custom node views

docs/api/editor.md
I added the following editor getters to the docs, since they are currently missing and only discoverable through autocompletion: `isFocused`, `isDestroyed`, `isCapturingTransaction`.
–
–
You can check the docs at `/api/editor` to verify my changes.
–
–
=> Documentation: Add missing editor getters

demos/src/Nodes/TaskItem/React/styles.scss, demos/src/Nodes/TaskItem/Vue/index.vue, demos/src/Nodes/TaskList/React/styles.scss, demos/src/Nodes/TaskList/Vue/index.vue
Changes are applied to usage code sample of TaskList and TaskItem extensions. 
With previous css code given, style of bullet lists and ordered lists which are nested inside of TaskItems were not correct.
By styling
=> Fix nested lists style issue

packages/extension-link/src/helpers/autolink.ts
At [Doist](https://doist.com) we have [extended the Code extension](https://github.com/Doist/typist/blob/main/src/extensions/rich-text/rich-text-code.ts) to allow all marks (e.g., Bold, Italic, and Strikethrough) to coexist with the `Code` mark, which gives a behaviour that more closely resembles GitHub, allowing us to render inline code marks with formatting and links, like this: **[`Typist`](https://typist.doist.dev)**.
However, this created an [issue](https://github.com/Doist/typist/issues/319) for us, where URLs typed inside inline code marks were automatically converted into links, which is not the behaviour we want. Here's a demo of our own editor based on Tiptap exhibiting the issue:
https://github.com/Doist/typist/assets/1322846/5f4d92e2-2293-41f7-9f60-27d1219f6228
Added a filter …
=> fix: Prevent auto-linking when typing URL inside inline code mark

packages/core/src/CommandManager.ts, tests/cypress/integration/core/can.spec.ts
Ensured that chains preserve the parent chain's dispatch state
Simply passed the "shouldDispatch" state down to the next chain that gets built when building command props
Added tests and did basic regression testing of the default editor demo
Verify tests pass and consider any other consequences/regression testing
fixes #4147
=> fix(core) Nested chain not preserving dispatch state

packages/react/src/ReactNodeViewRenderer.tsx
This fix will now correctly update the `props.selected` prop when a React component is inside a selection.
I created a selection update handler that will check if the react node position is inside the current selection.
I used the ReactComponent demo to test those changes.
=> fix(react): update select state when text selection is around

packages/extension-history/src/history.ts
Fix undo/redo don't work with Capslock enabled
Add uppercase matches for existing lowercase keyboardShortcuts
No; it's difficult to test TipTap changes on the fly but if there's some easy way I'd be happy to test it
Turn capslock on and test Mod-Z and Mod-Y behavior
Should resolves #4055 without ill effects
=> Fix mod+z/mod+y failed with capslock

packages/react/src/EditorContent.tsx, packages/react/src/useEditor.ts, packages/react/tsconfig.json
Fix https://github.com/ueberdosis/tiptap/issues/3764
There are two issues:
- The EditorContent is reused even though the instance of the editor has changed.
- The deletion of the editor occurs before the deletion of the EditorContent.
I solved those issues. 
I tested by changing `demos/src/Examples/CustomParagraph/React/index.jsx` below.
<details><summary>Test code</summary>
```jsx
import './styles.scss'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import React, { useEffect } from 'react'
import { Paragraph } from './Paragraph.jsx'
export default () => {
const [data, setData] = React.useState({ content: '' })
useEffect(() => {
const timer = setInterval(() => {
setData({
content: `
<p>
Each line shows the number of characters in the …
```
=> Destroy editor in safe

packages/extension-link/src/link.ts
Without the addAttributes entry, passing the rel attribute doesn't work (tested in 2.0.3)
Add the rel entry
Seeing that my rel attribute wasn't set, i tested with this entry, and it works
Tested locally on 2.0.3
Simply try to pass a rel attribute to setLink, it doesn't work
=> Rel cannot be set

packages/extension-link/src/helpers/clickHandler.ts
This PR prevents opening of links using `window.open` on clicking them in readonly mode. 
When `contenteditable` is `true`, the browser doesn't allow direct link opens on clicking the `a` element. This is why we need to call `window.open` to open our links.
However, when `contenteditable` is `false`, the default browser mechanism for opening links works and there is no need for using `window.open`.
Without this change, TipTap would open 2 new tabs on clicking a link.
By enabling readonly mode and clicking on links.
By enabling readonly mode and clicking on links.
=> fix: do not use window.open for links in readonly mode

packages/vue-3/src/NodeViewContent.ts, packages/vue-3/src/NodeViewWrapper.ts, packages/vue-3/src/VueNodeViewRenderer.ts
Fix component names in Vue 3 devtools
Propogate `__name`, `__file` in `VueNodeViewRenderer`, and add `name` to `NodeViewContent` & `NodeViewWrapper`.
Ran `npm run start` and checked pages that show `NodeViews` with Vue 3
Do the same as I did above. With the Vue devtools installed in the browser.
Fixes #3965
=> Fix component names in Vue 3 devtools

docs/overview/upgrade-guide.md
The docs of Tiptap version 1 are only available via the link in the footer of the website. We want to remove it because version 1 is quite old. Instead, I put a link in the upgrade guide, so everybody can find it there. Tiptap is still available via https://v1.tiptap.dev/ and it's possible to find it with Google.
Add a new paragraph to the upgrade guide close to the top.
n/a
n/a
n/a
n/a
=> add link to version 1 of the docs

packages/core/src/utilities/createStyleTag.ts
Similar to the core of Tiptap, some extensions require basic styles to work. This PR adds the possibility to create CSS styles through extensions.
The `createStyleTag` function optionally receives another suffix parameter which adds another `data-tiptap-style` CSS block to the document.
Added a demo extension that calls `createStyleTag()` inside a PM plugin.
See above.
/
/
=> Register CSS through extensions

docs/api/extensions/collaboration-cursor.md, packages/extension-collaboration-cursor/src/collaboration-cursor.ts
Add support for custom selection builders.
Added new field to the extension options, type and passing along parameter to the `y-prosemirror` extension. Passing by default the existing default value to avoid breaking anything.
Ran the existing collaboration demo locally with the changes applied. Verified that the cursor and selection is shown correctly.
You can clone code and check that the collaboration cursor and selection is not broken.
N/A
- [] Added tests where possible - N/A
=> Add support for custom selection builders

docs/cloud.md
Updated to the documentation of the Cloud to make it more understandable.
Changing the relevant Markdown file.
Preview of Visual Studio Code 😉
Render documentation
n/a
n/a
=> update cloud docs

demos/src/Marks/Strike/React/index.spec.js, demos/src/Marks/Strike/Vue/index.spec.js, packages/extension-strike/src/strike.ts
This PR changes the shortcut for strikethrough to a more standardized version similar to other apps (Notion, Dropbox Paper).
Now the default shortcut is `Mod+Shift+s` for MacOS and `Ctrl+Shift+s` for other operation systems.
See https://defkey.com/search?irq=strikethrough
Changed the addKeyboardShortcuts function
Tested them locally on MacOS and Windows.
Check the deployed demo
nothing
closes #2540
=> fix(strikethrough): update strikethrough shortcut

packages/extension-link/src/helpers/autolink.ts, packages/extension-link/src/helpers/pasteHandler.ts
This PR will fix multiple issues with the current auto linking.
- First fix is that pasteOnLink option was not working anymore
- I'll also fix an apparent issue that content after a pasted link is also autolinked? (wasn't able to reproduce for now)
fixes #4256 
fixes #4258
=> fix(link): Fix autolinking and pasting

packages/core/src/inputRules/nodeInputRule.ts, packages/extension-horizontal-rule/src/horizontal-rule.ts
This PR adds two new options to the `nodeInputRule` function that help with nodeInput replacements. By default, nodeInputRules always try to replace into the current content which caused that extra `<p>` in front of the new `<hr>` because HR's can't be inserted into `<p>` tags and Prosemirror doing it's Schema magic moved the hr below the paragraph.
This change adds the following options:
**blockReplace**
Optional option which will replace the current node instead of inserting into it when set to true
**addExtraNewline**
Adds a new line with the schema's default node for the parent wrapper. (For example in doc that would be a paragraph).
add those options to the nodeInputRule function.
- Tested non-block replacements and block replacements
- Compared behavior with the `setHorizontalRule` …
=> feat(core): added new options for nodeInputRules for block replacements

demos/src/Extensions/TypographyWithOverrides/React/index.jsx, demos/src/Extensions/TypographyWithOverrides/React/index.spec.js, demos/src/Extensions/TypographyWithOverrides/Vue/index.spec.js, demos/src/Extensions/TypographyWithOverrides/Vue/index.vue, docs/api/extensions/typography.md, packages/extension-typography/src/typography.ts
This PR adds the option to replace the output of the inputRules used for the Typography extension.
With this PR users can now do something like this to add overrides to specific characters:
```js
Typography.configure({
oneHalf: "1 / 2", // this will insert "1 / 2" instead of the default "½"
})
```
Instead of just passing static strings, I used callback functions that will return a new inputRule with said override (if it exists)
I added a local test for my change which worked + I tried out the inputRule override manually.
Check out this PR or go to the deployed demo and try out to replace `->` to `=====>` on the TypographyWithOverrides demo page.
/
closes #2598
=> feat(typography): allow overrides of inputRule outputs

packages/core/src/utilities/mergeAttributes.ts
Before this change, the class attribute on `HTMLAttributes` would be duplicated inside the `mergeAttributes` function, because there was no check if a class already exists on the `HTMLAttributes` string (coming from defaultOptions and inputOptions).
This PR fixes this.
Added a check if the className is already included inside the class attribute.
Tested locally in the link demo with normal class and BEM class style
See above
fixes #4282
=> Core: Fix classes being duplicated on mergeAttributes function

packages/core/src/inputRules/nodeInputRule.ts, packages/extension-horizontal-rule/src/horizontal-rule.ts
This PR fixes an issue with the `setHorizontalRule` function placing the selection at non-text positions (for example `doc`) after inserting a HorizontalRule node.
I modified the insert positions of the functions and added a small part of code to determine the next text-node which the cursor can be placed in.
Locally with the HorizontalRule demo.
See above
Nothing
fixes #3003
=> HorizontalRule: fix setHorizontalRule putting cursor at non-text positions

.eslintrc.js, demos/src/Experiments/OnUpdateRerender/React/index.jsx, demos/src/Experiments/OnUpdateRerender/Vue/TiptapComponent.vue, packages/core/src/inputRules/nodeInputRule.ts
This PR fixes an issue introduced in 2.1.0 that caused inputRules to not work correctly if the position was the last position of an isolating block range.
I added better position handling for the inputRule class.
I tested the following extensions locally:
- HorizontalRule
- Image
- Figure
Test the nodeInput behavior on the following demos:
- HorizontalRule
- Image
- Figure
=> hotfix(core): Fix input rules not working if at last position of a block

demos/src/Marks/Link/React/index.jsx, demos/src/Marks/Link/React/index.spec.js, packages/core/src/utilities/mergeAttributes.ts
This PR fixes an issue that caused a crash in `mergeAttributes` when one of the `value` or `mergedAttributes` is not set.
I added checks to the mergeAttribute function that will throw back a fallback value of `[]`.
I tried adding a class in my local demo. I also added a test to check, if the option is set correctly afterwards.
Run the local demo and configure the extension to have a class – it should work without any error throws & the test should run through.
=> fix(core): fix error when merging class attributes

packages/extension-link/src/helpers/autolink.ts
fix autolink issue when code extension is not enabled for the editor. See issue https://github.com/ueberdosis/tiptap/issues/4343 for more details
There is a filter in the auto link handler to avoid auto link in a code block. However, when code is not enabled for a particular editor instance, `schema.marks.code` will be `undefined`. The handler passed it to `rangHasMarks` without any validation, and cause an exception.
To fix the issue, we can just return early from the handler when `schema.marks.code` is a falsy value.
Yes. As the code change is very small, I verified it by applying the same change to my local `node_modules` folder.
To reproduce the issue, just setup an editor instance with `extension-link` included, but without `extension-code` included, typo a URL in the editor, then …
=> fix autolink when code is not enabled for editor

packages/extension-list-keymap/src/listHelpers/findListItemPos.ts, packages/extension-list-keymap/src/listHelpers/getNextListDepth.ts, packages/extension-list-keymap/src/listHelpers/handleBackspace.ts, packages/extension-list-keymap/src/listHelpers/handleDelete.ts, packages/extension-list-keymap/src/listHelpers/listItemHasSubList.ts
This PR fixes a few imports inside the list-keymap extension that were broken because automatic import updates in 2.1.0.
Just fixes those imports
closes #4342
=> fix(list-keymap): fix broken imports causing typescript errors

packages/core/src/types.ts, packages/react/src/ReactNodeViewRenderer.tsx
Added the option `contentDOMElementTag` to the `NodeViewRendererOptions` to allow users to provide as the desired element tag they would like to render.
This allows developers to solve the issue with injected divs inside a `table` when extending the table extension:
- https://github.com/ueberdosis/tiptap/issues/2675
- https://github.com/ueberdosis/tiptap/issues/2892
Added the option `contentDOMElementTag`
In `demos/src/GuideNodeViews/ReactComponentContent/React/Extension.js` we tested it using:
```js
return ReactNodeViewRenderer(Component, { contentDOMElementTag: 'main' })
```
You can see it in action here where we applied the patch via patch-packages: https://github.com/serenity-kit/Serenity/blob/68d7bb29979abf9833116c81f2db27156724a93d/packages/editor/extensions/tableExtension/tableExten …
=> feature: allow to customize the tag of the contentDOMElement

demos/src/Extensions/Placeholder/React/styles.scss, docs/api/extensions/placeholder.md, packages/extension-placeholder/src/placeholder.ts
This PR implements a new option for `@tiptap/extension-placeholder` that will allow users to enable more nodes than just `paragraphs` as empty for the `editor-is-empty` empty check.
Instead of creating an empty doc copy, I'm directly checking the current document childCount, check if the first element is a valid node (as configured or is it not a atom or leaf) and then enable the class for valid nodes found at the first position of the editor.
I used the local development environment for testing.
1. Checkout this PR
2. Go to the Placeholder demo of your choice
3. Add the option `considerAnyAsEmpty: true`
4. Test inside your browser if the empty-editor placeholder will be shown for headlines too
- In the future we could even make this more granular by adding node type filters
- No related …
=> feat(placeholder): allow editor-is-empty class on any node

docs/api/commands.md, docs/api/editor.md, docs/guide/custom-extensions.md, docs/guide/menus.md, docs/guide/node-views/vue.md, docs/guide/output.md, docs/guide/styling.md
This improves copy to introduce example code. Previously it added 'like that:'. In most cases this was just a stop word and can be removed. In other cases the sentence needs to be rewritten for that, or, what I did, replace it with 'like this:' because it refers to an upcoming example, instead of one that was shown before.
n/a
n/a
I double checked my logic here: https://forum.wordreference.com/threads/like-this-like-that.2851037/
n/a
This fixes https://github.com/ueberdosis/tiptap/issues/3747.
=> Improve introducing examples in the documentation

packages/html/src/getHTMLFromFragment.ts
Allows callers of the `generateHTML()` fn to pass their own `document` implementation. This is necessary because `renderHTML()` can return a `DOMElement` as a `DOMOutputSpec`. However, the `renderHTML()` method on nodes doesn't provide access to the `document` used in the render (at least as far as I can tell). 
TipTap assumes that the `document` passed to [DOMSerializer](https://prosemirror.net/docs/ref/#model.DOMSerializer) can always be the `document` that comes from `zeed-dom`. However, `zeed-dom` appears to be incompatible with jsdom. Without the change in this PR, any node that returns an `HTMLElement` created via jsdom is serialized as the string `{}`.
I added an option to `generateHTML()` that allows callers to specify a `document` alternative to `zeed-dom`.
I have this …
=> feature(html): allow caller to specify a `document` implementation in `generateHTML()`

packages/extension-horizontal-rule/src/horizontal-rule.ts
This PR fixes a bug that would try to insert the hr outside of the document range.
I used `Math.max` to set a minimum position of 0.
Tested it locally inside the demo.
Check the demo locally too, try to insert a hr into an empty document.
=> fix(horizontal-rule): fix insertion being broken on empty docs

docs/installation/php.md
The phrase "a PHP package to work with Tiptap content" is repeated twice.
=> fix duplicated text in PHP docs

docs/api/extensions/collaboration.md
Fixes a typo in the collaboration documentation.
=> Fix typo in collaboration.md

packages/extension-link/src/helpers/clickHandler.ts
This code will check whether a clicked node name is 'A'. This will fix the issue when `openOnClick` is enabled, that causes clicking on a selection to open a link that's somewhere within the selection, even though user clicked some other element.
I have tried these changes in our repo that uses Tiptap for our pages editor.
Our QA engineer tested whether this fix solves the issue.
To reproduce the current issue:
1. `openOnClick` must be enabled in link-extension config
2. Add some link somewhere within the paragraph and some other text
3. Select the text and the link
4. Click somewhere, not directly on the link
5. It will open a link
These changes will make click open link only when user clicks on the link itself.
No remarks.
=> prevent opening link when clicking on selection containing a link

docs/installation/react.md
This PR adds a small typo fix for the code block inside the [React installation](https://tiptap.dev/installation/react) page.
=> docs(react): fix typo on React installation code block

packages/extension-link/src/link.ts
Despite `rel` and `class` already being defined as an attribute in `addAttributes()`, the interface was missing these two particular attributes so it wasn't accessible when using TypeScript without workarounds.
I added the missing attributes to the interface
Full disclosure, I haven't tested it yet. This is a quick PR that I made from GitHub's web editor so that I don't forget to test it later and submit a fix properly.
Open a typescript file and try to add a link through
```ts
editor?.value?.chain().focus()?.extendMarkRange('link')
.setLink({
href: 'https://google.es',
class: 'button' // this will give you an error without this PR
})
```
-
=> fix: add missing attributes in extension-link

packages/react/src/ReactNodeViewRenderer.tsx, packages/vue-2/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueNodeViewRenderer.ts
Fix for an issue that caused node-view elements not having the `.Prosemirror-selectednode` class as the vanilla nodeViews and normal atom node blocks receive.
Add according classList modifications to the renderer code.
Locally inside the vue-2, vue-3 and react demos and compared to the vanilla js demo
See above
=> Fix React and Vue NodeView renderers not adding correct selection classes 

demos/src/Nodes/Table/React/index.spec.js, demos/src/Nodes/Table/Vue/index.spec.js, packages/extension-table/src/table.ts, packages/extension-table/src/utilities/createColGroup.ts
Fixes #4280
Added createColGroup function to generate colGroup based on child nodes (imitates `updateColumns` which is used for editor TableView.
`renderHTML` is calling `updateColumns` to get generated `colgroup` element, `tableWidth` and `tableMinWidth` values.
Updated *react* and *vue* e2e tests to assert that there is `colgroup` -element.
#721
=> [Bug]: HTML output of Table is missing colgroup element

packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
Extensions, marks and nodes should keep their original config when they are extended or configured. 
n/a.
Tested locally.
```
import Code from '@tiptap/extension-code'
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import { EditorContent, useEditor } from '@tiptap/react'
import React from 'react'
export default () => {
const editor = useEditor({
extensions: [Document, Paragraph, Text, Code.configure({
HTMLAttributes: {
class: 'my-custom-class',
},
})],
content: `
<p>This isn’t code.</p>
<p><code>This is code.</code></p>
`,
})
if (!editor) {
return null
}
return (
<>
<button
onClick={() => editor.chain().focus().toggleCode().run()}
className={editor.isActive('code') ? 'is-active' : ''}
> …
```
=> Fix: configured/extended extensions should keep their original config

docs/guide/output.md
Fixed what I expect is a typo in the Output documentation, changing the adverb "wildly" to "widely".
N/A
N/A
N/A
N/A
=> change wildly to widely

packages/extension-collaboration/src/collaboration.ts
There is an option called `onFirstRender` in the `CollaborationOptions` type; however, it is not used anywhere. This commit passes the option to the Yjs' sync plugin.
We use this callback together with the HocuspocusProvider to understand when the content is synced and ready on the editor for the first time. Then, we can safely set the cursor to the beginning of the text editor. 
Just used the existing option and correctly passed it to the `ySyncPlugin` function that creates the plugin.
You can pass `onFirstRender` option to the Collaboration extension and see it gets called when the plugin first renders.
- [] The changes are not breaking the editor
- [] Added tests where possible
- [] Followed the guidelines
- [] Fixed linting issues
=> Pass onFirstRender option to ySyncPlugin

package-lock.json, packages/html/package.json
Noticed a bug in `zeed-dom`, a downstream dep of Tiptap. I made [a PR](https://github.com/holtwick/zeed-dom/pull/9) and the maintainer has published a new version.
I didn't notice up front was that it's a minor version ahead of what Tiptap relies on. Using `yarn` resolutions, we've tested our app internally with my fork, and I've run the tests here, and all appears to be fine. But I'll leave it up to the maintainers here to confirm that all is well ✌️ 
Debugged with some logs in Tiptap, isolated to `parseHTML`, replicated in `zeed-dom` and fixed.
We opted to resolve the dep to my branch for now (see [PR here](https://github.com/bluesky-social/social-app/pull/1663)). I also ran any tests that seemed related in Cypress.
Unsure what else you'd like to do, but the e2e suite is extensive by …
=> Bump minor version of zeed-dom to include html parser bugfix

docs/guide/styling.md
Add Tailwind Intellisense configuration to docs
https://github.com/ueberdosis/tiptap/discussions/4359#discussioncomment-6801466
=> Add Tailwind Intellisense configuration to docs

docs/guide/menus.md
Just trying to make the docs read a little bit better and more professionally to a typical English speaker
=> Improve wording of menus.md

packages/extension-font-family/src/font-family.ts
Added CSS.escape to renderHTML. Prevents invalid css when using fonts with numbers in their names, like https://fonts.google.com/specimen/Exo+2
Added CSS.escape() to renderHTML
Tested local 
Before <img width="197" alt="Screenshot 2023-10-18 at 15 07 03" src="https://github.com/ueberdosis/tiptap/assets/2072500/4f9d7680-daf5-4bdf-9b1b-55bbd3abae19">
After
-
=> Added CSS.escape to font-family.ts

docs/api/utilities/suggestion.md, packages/suggestion/src/suggestion.ts
Hey there 👋 we're using Tiptap and the Suggestions plugin to implement hashtags in our editor. Our hashtag validation is a little more complex than what the default `findSuggestionMatch` allows, so I started investigating how I could replace the matching with a custom version. This seemed to be the most straightforward approach.
Disclaimer: this might be more of a conversation starter than a fix, but fwiw it does work for my needs right now. Happy to help improve.
Just added a new property `findSuggestionMatch` to the `Suggestion` plugin, with types that match the built-in function.
Just manually integrating at the moment, but lmk if I can assist with a test suite.
I think it's straightforward.
N/A
=> allow users to pass a custom `findSuggestionMatch` to Suggestion plugin

packages/extension-link/src/link.ts, packages/extension-youtube/src/utils.ts, tests/cypress/integration/extensions/link.spec.ts, tests/cypress/integration/extensions/youtube.spec.ts
Fixes risks outlined in #4600 by verifying that any src urls are valid youtube URLs before rendering as HTML.
Added isValidUrl regex check in renderHTML method
Added unit tests to validate fix. Ran other extension-youtube cypress tests
Verify non-breaking on youtube extension, and ensure the new tests I've added passes
#4600
=> fix(extension-youtube) XSS risk with src tag

packages/extension-youtube/src/utils.ts
Youtube uses /shorts/ for their shorts video. The /embed url works with these id's, the regex did not support them though.
This updates the videoId regex to also support the /shorts/ urls.
Tested with several youtube urls
youtu.be link: https://youtu.be/vwXeKbL_k6w?si=jPPIRP8x_0h1RU71
youtube.com embed link: https://www.youtube.com/embed/vwXeKbL_k6w
for example this short: https://youtube.com/shorts/5toiGG5I9yM?si=N6idQiwCYltCKpDC 
Fixes https://github.com/ueberdosis/tiptap/issues/3582
=> feat(extension/youtube): Allow youtube shorts urls to be embedded

demos/src/Marks/Link/React/index.jsx, packages/extension-link/src/helpers/autolink.ts, packages/extension-link/src/helpers/clickHandler.ts
I am improving on this pull request, which doesnt solve the issue (actually brings another one): https://github.com/ueberdosis/tiptap/pull/4346#event-10276708233 
In the mentioned PR only when the exact A element is clicked, it opens the link. But there are cases, when you have mark Bold or some other on the link text as well. The B / STRONG element is rendered INSIDE the A element, thus the condition nodeName !== 'A' does check and it cancels opening the link. I fixed that.
I iterate all clicked nodes nodeParents till I approach parent DIV node (inline node must be inside block node, so this is logical rule; Link is inline node). If none of those parent nodes are not A node, only then do I cancel the link opening. This handles all other marks (ie STRONG element inside A element etc) …
=> Link click fix

packages/extension-history/src/history.ts
The problem with the shortcuts for undo/redo. the decision is made immediately for z/y.
I will use the abstract Ctrl-Shift-Z to avoid overlapping with tiptap.
I will describe for z:
- when you press Ctrl-Shift-Z, Mod-Z and Shift-Mod-z catch this event, that is, potentially we have two handlers for the same event, but with different functions, and they are not always executed together
- If the undo stack is not empty, then only the Mod-Z handler will be captured, which will execute undo by shortcut Ctrl-Shift-Z, we get a completely diametric behavior, the behavior should have been called redo
- If the undo stack is empty, then Mod-Z will work, saying that it did nothing, and we will run in Shift-Mod-z, finally getting the same redo
Shift-Mod-Z doesn't make sense according to "Modifiers can …
=> fix(history): use correct shortcuts for undo/redo

docs/api/nodes/mention.md, packages/extension-mention/src/mention.ts
Currently the mention extension's `renderLabel` doesn't allow returning HTML and expect returning string, there is a workaround by tricking the typesystem but this breaks when generating text from `JSONContent` (i.e using `generateText` from `@tiptap/core` , this should allow the user to customize the text and html rendering.
This can be very useful when one wants to render and `a` tag instead of just a `span` tag so that it can link to the profile of the mention person
Basically introduced two new functions `renderText` and `renderHTML` 
Yes, tested it on my current project (Laravel with Inertiajs)
It can be tested using the mention demo
N/A
#3325
=> Allow the mention extension to have custom renderHTML

packages/react/src/ReactNodeViewRenderer.tsx
Currently, updates on attributes of `ReactNodeView` are not applied to its renderer element. It's noticeable when you are using elements that depends on its attributes to render correctly like `colspan` in td elements. This PR tries to fix that issue.
Added a loop updating all the renderer element attributes on the update method of the class `ReactNodeView`.
Tested locally.
Add a NodeView to the table cell extension and try to merge them. More details on the linked issue.
Fixes https://github.com/ueberdosis/tiptap/issues/4239
=> React: Fix ReactNodeView renderer element updates not being applied

packages/react/src/ReactNodeViewRenderer.tsx
This PR should fix a performance regression that caused to many React state updates because the new select/deselection fix introduced in #4148
I added checks to make sure those updates are only made when a node was actually affected by the change
=> fix(react): fix performance regression because of select/deselect

demos/src/Extensions/Typography/React/index.spec.js, packages/extension-typography/src/typography.ts
This PR changes the regex for all division replacements to **require** a space after a division. This way dates won't be broken when typing 1/4/2024 for example. See issue #4663
I added a required whitespace after the division regexes.
I added two new tests that will check if those requirements are met.
Check the tests for the Typography demo page
Closes #4663
=> fix(typography): require spaces after divisions to not break dates

packages/extension-table/src/index.ts
Changed to export the `createColGroup` function added in #4281.
The `createColGroup` function is needed when extending the output with `renderHTML()` in `extend()`, so it should be exported.
n/a
Functions can be imported successfully using 
```js
import { createColGroup } from @tiptap/extension-table
```
n/a
#4280, #4281
=> Export createColGroup utility function

packages/react/src/EditorContent.tsx
Allow passing a `ref` to `EditorContent` to imperatively access the underlying `div` element.
My use case is to apply line clamping CSS to the `EditorContent` div based on its height.
1. Forward a ref passed to `EditorContentWithKey` to `PureEditorContent`
2. Attach the ref to the `div` element returned by `PureEditorContent`
Manual testing by rendering `EditorContent` with a ref prop.
Run this code and expect `div` to have a value:
```tsx
<EditorContent ref={(div) => {
console.log('EditorContent ref:', div);
} />
```
`EditorContent` used to accept a ref but it broke in #4000. Prior to #4000 the value of ref was `PureEditorContent`:
```tsx
<EditorContent
ref={(editorContent) => {
const div = editorContent.editorContentRef.current;
}}
/>
```
I simplified the value in this PR to the …
=> Forward `EditorContent` ref

demos/src/Issues/2720/React/index.jsx, demos/src/Issues/2720/React/index.spec.js, demos/src/Issues/2720/React/styles.scss, packages/core/src/commands/insertContentAt.ts, packages/core/src/helpers/createNodeFromContent.ts
This PR fixes the issue described in #2720 which was caused by keeping new lines in string content and using the DOMParser which will add breaks for new lines too.
I strip out `\n` content from the content string so new lines are interpretet by the DOMParser only.
I created a demo where this can be tested. (See [here](https://deploy-preview-4465--tiptap-embed.netlify.app/src/issues/2720/react/))
Test in the demo above
- fixes #2720
=> fix(core): fix insertContentAt keeping new lines in html content

demos/src/Issues/2720/React/index.spec.js, packages/core/src/helpers/createNodeFromContent.ts, packages/core/src/utilities/elementFromString.ts
This PR fixes an issue that adds new lines on the parser level of the browser. It traverses through the actual dom instead of using string replacements removing all newlines added additionally by the parser.
See above
I added a new test to check if newlines are kept in pre tags.
Check out the local demo of Issue #2720
=> fix(core): fix new lines being added via elementFromString

packages/core/src/helpers/getMarksBetween.ts
https://github.com/ueberdosis/tiptap/issues/4785
=> fix: fix bug #4785

demos/package-lock.json, demos/package.json, demos/src/Experiments/CollaborationAnnotation/Vue/extension/AnnotationPlugin.ts, demos/src/Experiments/IsolatingClear/React/index.jsx, demos/src/Experiments/OnUpdateRerender/Vue/TiptapComponent.vue, demos/src/Experiments/OnUpdateRerender/Vue/index.vue, demos/src/Nodes/Youtube/React/index.jsx, demos/src/Nodes/Youtube/Vue/index.vue, package-lock.json, packages/core/src/utilities/elementFromString.ts, packages/extension-collaboration-cursor/src/collaboration-cursor.ts, packages/extension-table/src/table.ts, packages/extension-table/src/utilities/createColGroup.ts
Prepare stable release and fix demos and some obvious issues.
=> Prepare stable release 2.2.0

packages/react/src/useEditor.ts
[Ref](https://github.com/ueberdosis/tiptap/issues/4482)
Thx @prichodko 
To be done …
[add a description of your changes here]
[add a detailed description of how you accomplished your changes here]
[add a detailed description of how you tested your changes here]
=> fix(react): use ref instead of state in useEditor to prevent rerenders

packages/extension-youtube/src/utils.ts, tests/cypress/integration/extensions/youtube.spec.ts
Extended the `YOUTUBE_REGEX` in youtube extension to consider nocookie URL as valid.
Added `youtube-nocookie\.com` into the regex.
Locally via link to my app and added automated tests.
Set content of the editor to e.g.
```html
<div data-youtube-video=""><iframe class="w-full aspect-video" width="640" height="480" allowfullscreen="true" autoplay="false" disablekbcontrols="false" enableiframeapi="false" endtime="0" ivloadpolicy="0" loop="false" modestbranding="false" origin="" playlist="" src="https://www.youtube-nocookie.com/embed/dh72Dz0OqLk" start="0"></iframe></div>
```
=> fix: mark nocookie youtube url as valid when parsing html

packages/extension-bold/src/bold.ts, packages/extension-code/src/code.ts, packages/extension-highlight/src/highlight.ts, packages/extension-italic/src/italic.ts, packages/extension-strike/src/strike.ts
This PR disallows Markdown shortcuts (through typing or pasting) for all marks (`Bold`, `Code`, `Highlight`, `Italic`, and `Strike`) when the **content between the delimiters is only whitespace**.
Changed the input and paste Regex for all the marks mentioned above to keep supporting as much as possible from the current syntax, while only disallowing "empty strings" between the delimiters for the Markdown shortcuts of each mark.
> [!NOTE]
> The regular expression for all marks follows the exact same pattern, the only difference being the delimiter characters for each mark.
I've used both [regex101.com](https://regex101.com/):
And the marks demos to test multiple patterns, here's an example for the `Highlight` extension:
The same way I did above.
=> fix: Disallow only whitespace between markdown shortcuts delimiters

docs/links.yaml
In the utlities/html docs page, the "next page" button now says Suggestions instead of HTML and routes to next page in docs. The changes redirects the api/utilities page to html instead of creating page as if it is the "utilities" page
Just a small change in the links.yaml that redirects to html page when clicking on utilities page
Check to see if the UI is updated with the correct link on api/utilities/html page
Check to see if the UI is updated with the correct link on api/utilities/html page
=> Fix html docs page routing to itself

packages/extension-collaboration/src/collaboration.ts
This change makes it possible to pass ySyncOptions to extension-collaboration, which enabled advanced features such as `permanentUserData` or `colors` and `colorMapping`.
=> Feature/y sync options: allow passing ySyncOptions to extension-collaboration

packages/extension-link/src/helpers/autolink.ts
This PR implements better autolink validation to ensure that only complete and valid text is hyperlinked, preventing cases where a valid top-level domain (TLD) is immediately followed by an invalid character, like a number.
For instance, with the `find` method from [Linkify](https://linkify.js.org/), typing the text `example.com1` would result in `example.com` being linked and the trailing `1` left as plain text:
This behaviour is a bit unexpected, and this PR implements a more comprehensive validation on the input text.
With the `tokenize` method instead of `find`, which allows us to perform a more comprehensive validation on the input text.
> [!NOTE]
> The `find` method uses `tokenize` internally, but it does a much simpler validation.
Used the `Link` extension demo to test multiple …
=> fix(extension-link): Avoid auto-linking partial text for invalid TLDs

docs/api/nodes/mention.md, packages/extension-mention/src/mention.ts
after pr #4082 there is a regression where data attributes don't trickle down to the last render function, this fixes it
I passed the html attributes to the last `renderHtml` by merging
I ran the demo and verified the rendered attributes
run the demo and inspect the mention elements, you should see data attributes render correctly
Not sure if this is the right way to accomplish this since it is mutating the options object, the other fix would be to change the type of `renderHTML` to `  renderHTML: (props: { options: MentionOptions; node: ProseMirrorNode, HTMLAttributes?:Record<string, any>}) => DOMOutputSpec
` and pass the merged attributes
#4082
=> fix for data attributes not rendering after pr #4082

packages/core/src/helpers/getTextBetween.ts, tests/cypress/integration/core/generateText.spec.ts
- resolves: #3392
This issue is causing a number of downstream problems for me as it impacts multiple touch points, namely:
- `editor.getText()` state
- clipboard copy-paste
- reasoning about the selection state of the editor
I had a go at patching it myself and this appears to be the simplest solution - it might raise the question of how deeply nested nodes should be handled but I think it is reasonable to assert that: ***any nodes with a custom text renderer are solely responsible for how their children are rendered***.
=> Fix #3392 - Unexpected renderText() for contentful nodes

packages/react/src/useEditor.ts
Hi! I noticed that editor.destroy() is not being called for each reference that is being created, this should fix the problem.
Cleaning up editor was moved to the return of useEffect that creates a new editor, this way for each editor instantiated there will be a respective cleanup fn.
=> React: fix editor cleanup

packages/suggestion/src/suggestion.ts
Return the invocation of command in order to get access to the return value in rendering component.
This allows one to act on it when for example doing an async action before updating the editor, like getting a suggestion from ChatGPT or fetching a response from an api to be inserted.
return the invocation of `command`
In my own SlashMenu extension based on https://tiptap.dev/docs/editor/experiments/commands where I wanted to render a spinner if the item command function returned a promise.
Return something from the items command function and check the value in the rendering component 
```javascript
// suggestion.js
return [
{
title: 'H1',
command: ({ editor, range }) => {
return new Promise((resolve) => {
setTimeout(() => {
editor
.chain()
.focus()
.deleteRange(range)
.setNode('heading', …
```
=> return invokation of command

docs/api/nodes/youtube.md
Change string booleans (i.e. 'true') into boolean booleans (i.e. true).
I think someone was tired 😪
=> docs: pass valid property values 

demos/src/Commands/InsertContentApplyingRules/React/index.jsx, demos/src/Commands/InsertContentApplyingRules/React/index.spec.js, demos/src/Commands/InsertContentApplyingRules/React/styles.scss, packages/core/src/InputRule.ts, packages/core/src/PasteRule.ts, packages/core/src/commands/insertContent.ts, packages/core/src/commands/insertContentAt.ts
First call to enable the option of applying input and paste rules when using `insertContent`/`insertContentAt`. This is interesting, for example, if streamed content contains markdown characters and characters are added character by character within the editor.
Added `applyInputRules` and `applyPasteRules` to `insertContent`/`insertContentAt` options. Within the InputRule and PasteRule plugin I created some logic to trigger the rules.
I wrote tests and checked a few scenarios by hand.
Check the "InsertContentApplyingRules" demo.
https://deploy-preview-5046--tiptap-embed.netlify.app/src/commands/insertcontentapplyingrules/react/
=> Optionally apply input and paste rules when using insertContent methods

demos/src/Examples/NodePos/React/index.jsx, demos/src/Examples/NodePos/React/index.spec.js, demos/src/Examples/NodePos/React/styles.scss, packages/core/src/NodePos.ts
This PR fixes #4997 and #5003 via fixing the lookup functionality for child nodes in blocknodes.
Removed an unnecessary early return, added tests for various use cases.
See above
See above
fixes #4997
fixes #5003
=> fix(core): fix nodepos child lookup

docs/introduction.md
Changed hocuspocus link to refer to the actual hocuspocus page (https://tiptap.dev/docs/hocuspocus/introduction) instead of the URL https://hocuspocus.dev that redirects to https://tiptap.dev/
n/a
n/a
visually
n/a
n/a
=> Update link of hocuspocus in introduction.md

packages/extension-collaboration/src/collaboration.ts
Fix packing ySyncPluginOptions error,.
change `{...this.options.onFirstRender}` to `{onFirstRender}`
=> Fix packing ySyncPluginOptions error

packages/core/src/inputRules/nodeInputRule.ts
In the pull request: https://github.com/ueberdosis/tiptap/pull/4341 (originally: https://github.com/ueberdosis/tiptap/pull/3859), a fix was implemented for HorizontalRule. This made sure that for this extension/node, which is a block node, it would replace the whole block. This lead to problems in my implementation where I use an inline node. This is why I decided to, instead of overwriting the inputrule handing, fixing the issue in this PR. 
I've looked into previous versions of @tiptap/core to see where this issue first occured, and back-tracked it to the PR's mentioned above. It seemed like this change was made taking into account existing nodes in the TipTap repository, which use NodeInputRule and are block.
From what I could figure out, I don't think you want the replacement of the …
=> fix: only start at block with removing if not an inline node

packages/core/src/extensions/keymap.ts
Prevent running `clearNodes` when there's no nodes to clear to avoid useless history checkpoints
Check if the first node in editor is a paragraph and if so, return `false`
Locally
Locally and checking `editor.state.history$.done.eventCount`
It would be better if there were some `schema.nodes.defaultNode`, but in lieu of that I've assumed `paragraph` is the default.
#5062
=> Prevent history checkpoints during backspace in empty editor

packages/react/src/BubbleMenu.tsx, packages/react/src/FloatingMenu.tsx
`useEditor` return type is `Editor | null` 
But `FloatingMenu` and `BubbleMenu`  's props of `editor` is `Editor | undefined` 
I have solved it.
[add a description of your changes here]
Change `FloatingMenu` and `BubbleMenu`  's props of `editor` from `Editor | undefined`  to `Editor | null`
=> fix: fix ts error for BubbleMenu and FloatingMenu in @tiptap/react

packages/core/src/helpers/getTextBetween.ts
Currently `getTextBetween` function doesn't prepend `blockSeparator` to block nodes without children.
This PR updates it to prepend `blockSeparator` to block nodes in any case (even if block node doesn't have any children).
I have tweaked the implementation to not depend on child nodes of blocks when deciding whether `blockSeparator` should be prepended. 
I used preview link generated by Netlify bot below.
Use preview link generated by Netlify bot below.
Below are before/after examples.
```
Hello!
How are you?
```
Before: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`
After: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`
```
Hello!
How are you?
```
Before: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`
After: `'Hello!'+BLOCK_SEPARATOR+BLOCK_SEPARATOR+'How are you?'` **(it's breaking change, but I …
=> Tweak `getTextBetween` to prepend `blockSeparator` to block node even if block node doesn't have any children 

.husky/commit-msg, commitlint.config.mjs, package-lock.json, package.json
This PR adds commitlint to Tiptap which runs via a husky hook. It should help developers keep conventional commit messages in mind.
1. Added commitlint to the project with the @commitlint/config-conventional template
2. Added a new husky hook `commit-msg` which runs said linting process
I ran `npx commitlint --from HEAD~5 --to HEAD --verbose` to verify that we had faulty commit messages in the last 5 commit messages
Try commit something :)
nothing
no related issues
=> chore: added commitlint for conventional commit linting

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report_pro.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
I updated our Github template files for issues, PRs and the issue configuration page
Updated said files in our `.github` directory.
No testing required
No verification required
Feel free to come back with feedback regarding these.
=> chore: add streamlined github templates

packages/core/src/ExtensionManager.ts
I added a few missing JS Docs to the extension manager to make understanding said class a bit easier.
N/A
N/A
N/A
N/A
=> refactor(core): add jsdoc comments for ExtensionManager

CONTRIBUTING.md, package-lock.json, package.json
This PR adds the `cz-conventional-changelog` CLI to the project allowing developers to easily write **conventional commits** via running `npm run cz` to make work with the new commit linter easier.
I also added a new guideline for commiting to the CONTRIBUTING.md file.
N/A
N/A
N/A
N/A
N/A
=> chore: add cz-conventional-changelog cli & update contributing guides

demos/src/Marks/Strike/React/index.spec.js, demos/src/Marks/Strike/Vue/index.spec.js, packages/extension-strike/src/strike.ts
The tests were failing to run on a macOS machine because the keyboard shortcut for strike was trying to implement it's own platform detection.
Instead of relying on the existing keyboard shortcut code: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/keyboardShortcut.ts#L30-L34
The tests that were being run only ever sent the CTRL key instead of using the platform-independent `modKey`
Simplify the keyboard shortcut handler to utilize the built-in Mod which means CMD on macOS and CTRL on Windows
I ran the demo [src/Marks/Strike](http://localhost:3000/preview/Marks/Strike) and everything worked as expected.
Run the tests on macOS host, and on CI. Verify shortcut on your own
=> test: get tests running on macOS again by leveraging built-in platform detection

packages/core/src/Extension.ts, tests/cypress/integration/core/extendExtensions.spec.ts, tests/cypress/integration/core/extensionOptions.spec.ts
Based on the approach taken by https://github.com/ueberdosis/tiptap/discussions/5136 and validated for appropriate behavior with a barrage of tests.
The gist of what is happening here is that `extend()` will always set the new child's `parent` property to be `this` (establishing a child -> parent relationship).
When doing `.configure()` it is [doing a `.extend()`](https://github.com/ueberdosis/tiptap/blob/8cbd8e237779e7b04c0af297159e1886e26da9f0/packages/core/src/Extension.ts#L458). Doing this directly on an extension (i.e. one that is not already `.extend`'d), as it will create a child -> parent relationship with pretty much the exact same config so it ends up overwriting itself with it's same options.
But what we really want is not a child -> parent relationship, but to just overwrite …
=> fix: configure should use the parent of the current instance, to avoid duplication

packages/extension-link/src/link.ts, tests/cypress/integration/extensions/link.spec.ts
Link href values needs to be sanitized to not result in XSS vulnerabilities.
Link href values only allows whitelisted patterns for url, that are known to not be dangerous.
The link extension spec has been updated to cover both positive and negative tests.
Link extension still functions as expected when testing with valid links, such as relative, absolute, with different schemes etc.
=> fix(extension-link): use whitelist for allowed href values

packages/react/src/EditorContent.tsx
Adds a check to see if the `EditorContent` editor is already destroyed when `init` is called. This can happen due to using `React.StrictMode` where the editor is re-rendered back-to-back automatically by React.
Extended the existing check to include verifying that the editor hasn't already been destroyed.
Manual testing.
Unfortunately, I don't have a clean reproduction available at this time.
This issue is similar to the various problems described in https://github.com/ueberdosis/tiptap/issues/1451 (and other linked issues in that thread) and manifests itself with the same `TypeError: Cannot read property 'matchesNode' of null`.
=> fix: Don't init when editor is destroyed

packages/core/src/EventEmitter.ts
replace the protected `emit` member in `EventEmitter` with public member. Originally posted by @fw6 in https://github.com/ueberdosis/tiptap/discussions/3845_
=> fix: Allow `emit` to be accessed anywhere

packages/suggestion/src/suggestion.ts
Ignore unused parameter in suggestion plugin during typescript build.
Add this typescript compiler option
```
{
"compilerOptions": {
...
"noUnusedParameters": true,
...
},
...
```
Build project, it should build fine with suggested code changed.
```
npm --prefix ./packages/suggestion run build
```
Before the change this results in error:
```
[!] (plugin rpt2) Error: /home/marem/developpement/tiptap/packages/suggestion/src/suggestion.ts(187,32): semantic error TS6133: 'oldState' is declared but its value is never read.
```
After the change build is be ok.
https://github.com/ueberdosis/tiptap/issues/4770
=> fix(suggestion): unused parameter oldState in apply.

packages/core/src/commands/joinItemBackward.ts
"catch {"   should be   "catch (e) {"
[add a description of your changes here]
catch { to catch (e) {
[add a detailed description of how you accomplished your changes here]
Rollup gives unexpected token
[add a detailed description of how you tested your changes here]
=> Fix unexpected token in index.js (Rollup)

packages/html/src/generateJSON.ts
Allows the options to be supplied to the DOM parser which allows one to supply (among other options) `preserveWhitespace: true` to the parser. There is an outstanding bug where whitespace is being stripped when using generateJSON. This makes importing data into tiptap impossible (for me).
Added the parameter as an optional parameter so its entirely opt in.
Ran this on my project and it solved the issue regarding whitespace.
Ran this on my project and it solved the issue regarding whitespace.
https://github.com/ueberdosis/tiptap/issues/4432
=> fix: whitespace being stripped from generateJSON

packages/extension-link/src/helpers/autolink.ts, packages/extension-link/src/link.ts
Also defaults `validate` option to `val => !!val` rather than `undefined`
Fix failure to validate pasted links (#5060)
Add code which was missing to check pasted links are valid like all others
I have not
Probably manually. I assume automated tests do not cover this since this regression was able to sneak into `2.2.0`
Fixes #5060
#5060
=> Fix failure to validate pasted links

docs/installation/php.md
Include minor note to the documentation due to livewire version update.
Works on Laravel Livewire v3.4.12.
=> docs(php): include note on livewire v2 and v3 differences

packages/extension-text-align/src/text-align.ts
TextAlign extension should respects alignments config options, so when you for example copy paste alignment that is not configured, it will insert it as default.
I am just checking if provided value used in parseHTML is from allowed/configured list.
I have not added test, because this is really a small change/fix.
Try to configure text aligns that exclude justify, copy/paste text from website where is justified. On paste it should be left, because justify is not supported by provided config.
(https://github.com/ueberdosis/tiptap/issues/5010)
=> fix: parse only allowed text align alignments

demos/preview/Demo.vue
In our new demo preview frames, the tabs for languages should **always** be visible - even if only one language is available as a demo.
=> fix: don't hide tabs in previews when only one lang is available

docs/api/events.md, docs/api/schema.md, packages/core/src/Editor.ts, packages/core/src/EventEmitter.ts, packages/core/src/commands/insertContentAt.ts, packages/core/src/commands/setContent.ts, packages/core/src/helpers/createDocument.ts, packages/core/src/helpers/createNodeFromContent.ts, packages/core/src/types.ts, packages/react/src/useEditor.ts, tests/cypress/integration/core/createNodeFromContent.spec.ts, tests/cypress/integration/core/onContentError.spec.ts
This PR introduces a basic primitive for handling schema errors. Giving the user a callback to know when the schema was given content that it cannot parse and should probably be read only.
This change introduces two new top-level options to the editor: `enableContentCheck` & `onContentError` for dealing with content supplied that does not match the prosemirror schema generated by the set of tiptap extensions.
`enableContentCheck` allows the app developer to opt into the behavior to check for invalid schemas (this change is otherwise backwards compatible).
When true, this will try to parse the document, and any content that does not match the schema will emit a `contentError` which can be listened to via the `onContentError` callback.
Added new tests for this, most tests were tested …
=> feat: error handling of invalid content for a schema

demos/src/Extensions/FontFamily/React/index.jsx, demos/src/Extensions/FontFamily/React/index.spec.js, demos/src/Extensions/FontFamily/React/styles.scss, packages/extension-font-family/src/font-family.ts
Using `CSS.escape` is the wrong tool for the job here:
- it is meant for CSS selectors and does not handle CSS variables properly.
- you can't use `var(--title)` as a font-family because it was getting escaped to `var\(--title\)`
Instead, this reverts back to the previous behavior and forces the caller to specify an actual valid CSS font-family value.
I was notified that CSS variables don't work as the name.
CSS.escape did not look the right tool for the job.
I considered trying to quote the font-family using [this stack overflow mentioned how to do it](https://stackoverflow.com/questions/7638775/do-i-need-to-wrap-quotes-around-font-family-names-in-css), but I ended up going back on that decision because it is just over complicated and it really should be the caller's responsibility to …
=> fix: revert `font-family` escaping introduced by #4545

docs/api/keyboard-shortcuts.md
Simple PR to fix docs, with regards to the keyboard shortcut for strikethrough text formatting.
Simple markdown editing of `keyboard-shortcuts.md`.
Tested manually with Tiptap editor in React and Next.js projects.
Check the keyboard shortcuts that are defined in [strike extension source code](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-strike/src/strike.ts).
=> docs: Fix keyboard shortcut for strikethrough

packages/extension-bubble-menu/src/bubble-menu-plugin.ts
I think in the `hasValidSelection` boolean expression inside of the Bubble Menu plugin there is no obvious reason for why `$from.pos` and `$to.pos` are used instead of the properties of `selection` object with the same name.
I swapped resolved positions with unresolved ones in `hasValidSelection`.
I compared the values returned by both versions of the expression while tinkering with the menu. Also, as far as I'm aware, the ProseMirror documentation states that they're literally the same.
=> Change to unnecessarily resolved positions

packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts, packages/core/src/commands/insertContentAt.ts, packages/core/src/helpers/getAttributesFromExtensions.ts, packages/core/src/helpers/isNodeEmpty.ts, packages/core/src/types.ts
This adds all of the applied node & mark extensions as available on the `this` binding for the `addGlobalAttributes` function. This is helpful to be able to apply attributes to all installed extensions for example.
Other optimizations that I saw along the way were applied too:
- Use the much faster `.eq` method for determining equality of whether a node is considered empty
- Use a simpler & much faster check to determine if something is a fragment
=> feat: support global attributes for all nodes & marks

demos/src/GuideContent/ReadOnly/React/index.spec.js, packages/core/src/extensions/tabindex.ts
This reverts the initial implementation by providing a method that sets `tabindex` on state change instead of the fixed object.
TypeScript was not happy with the derived return type, so I typed the function the same as in Prosemirror types.
Please check the issue with the detailed description of the problem: https://github.com/ueberdosis/tiptap/issues/5231
Manual testing + added automated tests.
=> fix(core): update tabindex on state change (#5231)

packages/core/src/ExtensionManager.ts
Pull the exitable value from the correct place
https://github.com/ueberdosis/tiptap/pull/4191#issuecomment-1767021524
=> fix(core): make exitable resolve it's value through inheritance

packages/core/src/helpers/getSchemaByResolvedExtensions.ts
Actually send the whitespace value
whitespace was not being sent to the schema when it should have been, per: [#4191 (comment)](https://github.com/ueberdosis/tiptap/pull/4191#issuecomment-1767021524)
=> fix(core): the whitespace value for a node was not being sent to prosemirror

packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts, tests/cypress/integration/core/extendExtensions.spec.ts
As a follow up to #5147
In my previous PR, @634750802 [reminded me](https://github.com/ueberdosis/tiptap/pull/5147#issuecomment-2111518139) that Nodes & Marks both have the configure method as well and have almost the exact same logic as extensions. So I applied the change to Nodes & Marks as well
See $5147
Ran all tests, everything looks good
See above
=> fix: apply #5147 fix to marks and nodes

.changeset/mean-cooks-cheer.md, packages/extension-placeholder/src/placeholder.ts
This resolves a bug where the placeholder extension was not counting a document that contains more complex default content
I did some testing with the placeholder extension, couldn't be bothered to write whole new tests for it:
```diff
diff --git a/demos/src/Extensions/Placeholder/React/index.jsx b/demos/src/Extensions/Placeholder/React/index.jsx
index 970353980..9d5ae3389 100644
--- a/demos/src/Extensions/Placeholder/React/index.jsx
+++ b/demos/src/Extensions/Placeholder/React/index.jsx
@@ -1,5 +1,7 @@
import './styles.scss'
+import { Node } from '@tiptap/core'
+import Document from '@tiptap/extension-document'
import Placeholder from '@tiptap/extension-placeholder'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
@@ -8,7 +10,19 @@ …
```
=> fix: placeholders now check for empty content compared to their "true" empty state

.changeset/five-tigers-kick.md, packages/starter-kit/src/starter-kit.ts
Because blockquote uses `Mod-Shift-b`, and bold uses `Mod-b`, the bold shortcut will override the blockquote shortcut if added to the extensions later.
Fixes #4994
Changed the order in which the `bold`/`blockquote` extensions are added in the starter-kit. This is because plugins added later will override plugins added earlier, because of f8efdf797a10a01235b75091729b15aca076e47a (#1547).
Changed the order in which the `bold`/`blockquote` extensions are added in the starter-kit. I realise that this breaks the alphabetical ordering, but it's more important that the shortcuts work correctly.
Tested locally with the `Examples/Default` editor, which uses `starter-kit`. 
Load the Examples/Default example and check that `Mod-shift-b` (`Control Shift B` / `Cmd Shift B`) toggles Blockquote, and …
=> fix: make blockquote shortcut work in starter-kit

packages/react/src/useEditorState.ts
So that TypeScript will resolve the non-nullable one first, unless the editor is nullable, in which case the other one will resolve.
Related to discussion in #5161 @nperez0111
=> Flip the order of useEditorState's overloads

.changeset/clever-mice-search.md, demos/src/Examples/Performance/React/index.jsx, packages/react/src/useEditor.ts
This forces the editor to re-use the editor instance that existed prior to an unmount and remount of the same component.
This fixes a bug in `React.StrictMode` introduced with the latest performance updates by PR #5161
I made the Performance test playground run in StrictMode and was able to resolve the issue
Checked StrictMode and normal rendering and they seem fine
=> fix(react): `useEditor` should not destroy instances that are still mounted

packages/vue-3/src/VueRenderer.ts
return to using `renderedComponent`'s `ref` method to bind the methods exposed by the component and preserve the compontability of interfacing
=> hotfix(vue-3): backwards compatibility ref exposed methods

.changeset/clean-bugs-rush.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts, tests/cypress/integration/core/extendExtensions.spec.ts
There was a bug where doing a `.configure` on an extension, node or mark would overwrite the extensions options instead of being merged with the default options.
Added tests
=> fix(core): configuring extensions should add to the parent's options not replace them

.changeset/curly-buses-attend.md, packages/react/src/useEditor.ts
This PR changes the editor creation mechanism when dependencies change. Previously, the hook would try reusing an existing instance and applying new options if possible. Now, it always creates a new editor instance.
This fixes a bug where the content synchronisation mechanism wouldn't work in SPA apps when changing the content of the editor based on the client side route change. More specifically, it fixes a scenario where `/document/:id` page would contain a TipTap Collaboration editor and the user would
1. open `/document/1` and collaborate
2. open `/document/2` and collaborate
```ts
const editor = useEditor(
{
// NOTE: Disable immediate rendering to prevent SSR errors.
immediatelyRender: false,
extensions: [
DocumentExtension.extend({
content: 'heading block*',
}),
// ...
// …
```
=> Fix useEditor hook

.changeset/serious-foxes-decide.md, packages/extension-task-item/src/task-item.ts
Using `generateHTML` function from `@tiptap/html` package generates HTML like `<li data-checked data-type="taskItem">`.
However, in other parts of the code, the expected HTML is `<li data-checked="true" data-type="taskItem">`.
Due to this behavior, the selection state is lost when the HTML obtained using the `generateHTML` function is rendered again.
The value set for the `data-checked` attribute can be either `true` or undefined.
I manually tested both cases, using `generateHTML` and not using the `generateHTML` function, and confirmed that everything works correctly.
You can check out this repository to see how it works
https://github.com/baseballyama/tiptap-tasklist-bug-repl
N/A
N/A
=> fix: Address different behavior between `getHTML` and `generateHTML`

.changeset/atom-text-content-in-full.md, packages/core/src/helpers/getTextContentFromNodes.ts, tests/cypress/integration/core/getTextContentFromNodes.spec.ts
Make sure that atoms are used in-full without cutting the content. Node size for atoms is 1 which causes text to be cut unexpectedly.
Just made sure I handle the one exception for not cutting content – atom.
Automated tests for new functionality. Unfortunately there are no existing tests so regression testing is manual.
Try adding atom nodes and copy text. Content should contain full atom content.
https://github.com/ueberdosis/tiptap/issues/5298
=> fix: take atom content in full

.changeset/shy-clouds-smoke.md, packages/vue-3/src/VueNodeViewRenderer.ts
For a non-leaf node with no `NodeViewContent` return `null` instead of `this.dom`, this allows the node view itself to handle rendering the child content, instead of overriding the entire node with its child contents, not allowing to render it at all.
I changed a line of code.
In my own project.
Create a node view that has child `content`, but no `NodeViewContent`.
Fixes #3937
=> VueNodeViewRenderer should return `null` for `contentDOM` for a non-leaf node with no `NodeViewContent`

.changeset/sixty-gifts-dream.md, packages/core/src/Editor.ts
Adds a check before creating node views in the core editor so setProps is not called on a destroyed view.
Added checks in `createNodeViews()` in `Editor.ts`.
This should be no-op for successful use cases. There should not be any reason to call `this.view.setProps` on a view that has been destroyed, and doing so should either be no-op or results in unexpected crashes. This PR fixes this behaviour.
Related to #5333.
=> fix: check that view is not destroyed before creating node views in core Editor

.changeset/cool-steaks-clean.md, package-lock.json, packages/pm/package.json
Updated prosemirror-views & prosemirror-tables to most recent version
Actually I was looking for the prosemirror-model update because there was an XSS issue with version 1.22.0 and below (see https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572) - but it seems we already updated it.
While we're at it why not just bump the other prosemirror versions too.
I ran the tests locally + went through the demos manually to see if any functionality is broken (specially tables).
See above
=> Update prosemirror-view & prosemirror-tables to most recent version

.changeset/hungry-jokes-wash.md, demos/src/Nodes/Table/React/index.spec.js, demos/src/Nodes/Table/Vue/index.spec.js, packages/extension-table/src/table.ts
Change the `minWidth` to `min-width` in table style attribute
By changing the table attributes
Tested in local and already changed the unit tests
You can get the output via `editor.getHTML()` and see if the result changed
- No issues for this, but I found it when I am working with table
=> Fix: resizable table min width

.changeset/tiny-walls-shave.md, packages/core/src/helpers/createNodeFromContent.ts
To insert a node/mark in prosemirror, the schemas needed to be the same instance to be able to create the correct type from raw JSON. This removes a perf optimization & uses the dummy schema only to check for content errors but then recreates the same node afterwards with the editor's schema.
=> fix(core): address enableContentCheck insertion bug

.changeset/smart-rockets-divide.md, packages/core/src/Editor.ts, packages/core/src/helpers/isNodeEmpty.ts, tests/cypress/integration/core/isNodeEmpty.spec.ts
This addresses a bug with `isNodeEmpty` where it was also considering attributes on the node for it's emptiness check.
To address it, I went with a different approach of actually visiting each node to check for emptiness. This is both more performant and will be more accurate since it does not compare other properties like marks & attributes which do not determine emptiness.
I added a bunch of tests to ensure that the implementation not only passes for the previous cases but also considers the different attributes case.
=> fix(core): isNodeEmpty no longer considers attributes for it's checks

.changeset/lemon-files-thank.md, packages/core/src/helpers/getTextContentFromNodes.ts
This fixes a bug where text content was being considered in whole rather than just in slices when extracting the text content. This resolves a bug with input rules and a range error that could occur.
=> fix: do not consider text content as atoms resolve #5405

.changeset/odd-paws-tap.md, demos/setup/vue.ts, demos/src/Examples/InteractivityComponentProvideInject/Vue/Component.vue, demos/src/Examples/InteractivityComponentProvideInject/Vue/Editor.vue, demos/src/Examples/InteractivityComponentProvideInject/Vue/Extension.js, demos/src/Examples/InteractivityComponentProvideInject/Vue/ValidateInject.vue, demos/src/Examples/InteractivityComponentProvideInject/Vue/index.spec.js, demos/src/Examples/InteractivityComponentProvideInject/Vue/index.vue, packages/vue-3/src/EditorContent.ts
Fixes #5394.
Replace usage of `Object.assign` and set `appContext.provides` as-is from current instance `provides`. 
Vue internally uses prototype chain to preserve injects across the entire component chain. Thus should avoid `Object.assign` or spread operator as it won't copy the prototype. All correct provides will be already present on `instance.provides`.
Added new example with cypress test coverage.
=> fix(vue-3): Correctly set editor's appContext.provide to forward full inject chain

.changeset/red-suns-allow.md, demos/src/Examples/Performance/React/index.jsx, packages/react/src/useEditor.ts
React in strict mode can re-render the editor very quickly without unmounting, this makes it so that there cannot be two initalized editor instances active at the same time.
This was causing issues with the collaboration cursor which would infinitely send awareness updates while the editor was focused
=> fix(react): always cleanup old editor instances

.changeset/early-singers-begin.md, packages/core/src/utilities/findDuplicates.ts
I was getting a duplicate extension warning in Chrome because the duplicates array would contain an empty Set object:
```
[tiptap warn]: Duplicate extension names found: ['[object Set]']. This can lead to issues.
```
For whatever reason spreading the Set as a new array isn't always working as intended and causes a false positive regarding duplicates. The issue disappears when using `Array.from`.
Switch from `[...new Set(filtered)]` to `Array.from(new Set(filtered))`
I tested this on my local project. It's pretty straightforward change, so didn't overthink testing here.
Ensure that the duplicate extension warning is not being logged.
=> fix: findDuplicates - use Array.from when converting Set

.changeset/wise-beers-reflect.md, packages/extension-task-item/src/task-item.ts
When I modified the code in response to [the comments](https://github.com/ueberdosis/tiptap/pull/5366#discussion_r1682594145) in PR #5366, somehow I made the wrong modification. I am very sorry.🙏🙏🙏 @nperez0111 
This PR will be correctly amended according to this comment.
I have confirmed that it works correctly with both the REPL created in #5366 and my own product code.
I will take care to avoid similar carelessness.🙏
I tested it by manual. 
https://github.com/ueberdosis/tiptap/pull/5366
=> fix: allow task items to be parsed when only having `<li data-checked` instead of only when `<li data-checked="true"` (re-fix of #5366)

packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
Our [Typist](https://typist.doist.dev/) package (based on Tiptap) is still using `v2.3.0` for now, and while attempting a quick upgrade to the latest version, some type checks started to fail ([ref](https://github.com/Doist/typist/actions/runs/10148455201/job/28061425917?pr=773)).
One of the issues is that calling `Extension.create().configure()` returns `Node<any, any>`, whereas before it would return `Node<Options, Storage>`. This PR fixes that by making sure that when `.configure()` is called for an `Extension`, `Node`, or `Mark`, the correct type is returned.
Would love it if this could be reviewed, merged, and release soon, so that we can upgrade our Tiptap version.
Built Tiptap locally and checked the generated `.d.ts` files, the expected types were there.
Same as above. Build …
=> chore: Use proper types for `configure` methods (Extension/Mark/Node)

.changeset/smooth-rice-obey.md, .eslintrc.js, demos/src/Commands/Cut/React/index.jsx, demos/src/Examples/Performance/React/index.jsx, demos/src/GuideContent/ReadOnly/React/index.jsx, package-lock.json, package.json, packages/react/src/useEditor.ts, packages/react/src/useEditorState.ts, packages/vue-3/src/Editor.ts
This addresses an admittedly minor problem where sometimes the editor would reinitialize itself when it did not have to. This now can reuse editor instances that have been created before & re-apply options continously
=> fix(react): optimize `useEditor` and `useEditorState` to reduce number of instances created while being performant #5432

.changeset/real-kiwis-double.md, packages/core/src/helpers/getMarksBetween.ts
See issue #5401
Tested with this & checked that the cursor position was the same as expected
```diff
diff --git a/demos/src/Marks/Link/React/index.jsx b/demos/src/Marks/Link/React/index.jsx
index 452bb5b4b..99b071c26 100644
--- a/demos/src/Marks/Link/React/index.jsx
+++ b/demos/src/Marks/Link/React/index.jsx
@@ -1,5 +1,6 @@
import './styles.scss'
+import { getMarksBetween } from '@tiptap/core'
import Code from '@tiptap/extension-code'
import Document from '@tiptap/extension-document'
import Link from '@tiptap/extension-link'
@@ -30,6 +31,13 @@ export default () => {
By default every link will get a <code>rel="noopener noreferrer nofollow"</code> attribute. It’s configurable though.
</p>
`,
+    onTransaction: ctx => {
+      console.log(getMarksBetween(
+ …
```
=> fix(core): use correct position for getMarksBetween

.changeset/hungry-poems-bake.md, packages/core/src/helpers/isNodeEmpty.ts, tests/cypress/integration/core/isNodeEmpty.spec.ts
Adds a new option to `isNodeEmpty` to check ignore whitespace present in the node when checking for emptiness.
=> feat(core): add ignoreWhitespace option to isNodeEmpty

.changeset/yellow-rice-collect.md, demos/package.json, package-lock.json, packages/extension-collaboration-cursor/package.json, packages/extension-collaboration-cursor/src/collaboration-cursor.ts, packages/extension-collaboration/package.json, packages/extension-collaboration/src/collaboration.ts
`onFirstRender` was never actually able to be called, this option is now respected.
This updates `y-prosemirror` which shipped a bug in a patch version that caused some documents to fail to sync due to a nodeSize error
=> fix(collaboration): update y-prosemirror, respect `onFirstRender`

.changeset/three-snakes-wink.md, packages/vue-3/src/VueNodeViewRenderer.ts
Enables using Vue 3 class-based components as node views. 
Because of the way `VueNodeView` extends a custom node view,  a class-based component needs to be "unwrapped" before it can be used – a good opportunity to do this seems to be in the `VueNodeViewRenderer` function where the `VueNodeView` is constructed.
Checking and unwrapping is done using the same approach as in the vuejs implementation, see [runtime-core/src/component.ts#L1174](https://github.com/vuejs/core/blob/e0b2975ef65ae6a0be0aa0a0df43fb887c665251/packages/runtime-core/src/component.ts#L1174) for the check and [runtime-core/src/vnode.ts#L580](https://github.com/vuejs/core/blob/e0b2975ef65ae6a0be0aa0a0df43fb887c665251/packages/runtime-core/src/vnode.ts#L580) for the unwrapping code.
Is in use and working in my app.
=> fix(vue-3): custom node views when using class components

.changeset/loud-rockets-film.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts, packages/extension-text-style/src/text-style.ts
The text-style extension should be wrapping other elements like strikethroughs and underlines but because their priority was the same, the visuals would change based on extension order. So we modify the extension to have a slightly higher priority than the default
I noticed that the JSDoc was incorrect on what the defaults were so I modified them to be accurate https://github.com/ueberdosis/tiptap/blob/2ef43e92515c0b9c93aa9471145fab62dfbc09ce/packages/core/src/ExtensionManager.ts#L97
https://github.com/ueberdosis/tiptap/issues/4742
=> fix: bump priority of text-style extension fixes #4742

.changeset/dry-cycles-sleep.md, packages/react/src/Context.tsx, packages/react/src/useEditor.ts, packages/react/src/useEditorState.ts
This updates the typings so that the outer exposed types are from @tiptap/core and the inner types are from @tiptap/react
https://github.com/ueberdosis/tiptap/issues/5459
=> fix(react): update the types to reflect true options #5459

.changeset/rotten-beers-protect.md, demos/src/Examples/CustomParagraph/React/Paragraph.jsx, packages/core/src/Editor.ts, packages/react/src/Editor.ts, packages/react/src/EditorContent.tsx, packages/react/src/NodeViewWrapper.tsx, packages/react/src/ReactNodeViewRenderer.tsx, packages/react/src/ReactRenderer.tsx
This PR significantly improves the performance of React NodeViews in a couple of ways:
- It uses `useSyncExternalStore` to synchronize changes between React & the editor instance
- It dramatically reduces the number of re-renders by re-using instances of React portals that have already been initialized and unaffected by the change made in the editor
We were seeing performance problems with React NodeViews because a change to one of them would cause a re-render to all instances of node views, for an application that heavily relies on node views in React, this is expensive. This should dramatically cut down on the number of instances that have to re-render as well as making each of those re-renders much less costly.
Similar to the performance updates for Tiptap 2.5, React has it's own …
=> fix(react): resolves React NodeView performance issues

.changeset/perfect-dryers-glow.md, packages/react/src/useEditor.ts
This resolves a bug where event handlers were being registered twice
=> fix(react): event handlers called once per event type #5463

.changeset/weak-books-eat.md, package-lock.json, packages/starter-kit/package.json, packages/starter-kit/src/starter-kit.ts
I went ahead and enabled more extensions that I felt made sense in a generic starter kit, I added links, underlines and the list keymap extension since I felt this was core to the tiptap experience
=> feat(starter-kit): enable more extensions in the starter-kit for easier onboarding

.changeset/ordered-list-type-attr-undefined.md, packages/extension-ordered-list/src/ordered-list.ts
#5344 introduced a type attribute for ordered lists. The default value is set to `null` which causes a change in the outputted document when using `editor.getJSON()`. If the user is using strict backend validation of the document, this will cause validation to fail.
Changing to `undefined` removes it from the JSON document, matching previous behaviour.
```json
{
"type": "orderedList",
"attrs": {
"start": 1,
},
"content": [],
}
```
```json
{
"type": "orderedList",
"attrs": {
"start": 1,
"type": null,
},
"content": [],
}
```
#5344
=> fix: Use undefined for type attribute default

.changeset/funny-terms-do.md, demos/src/Extensions/CollaborationCursor/React/index.jsx, packages/react/src/useEditor.ts
`React.StrictMode` has made the way that we create editor instances very strange. There is a tension where React wants for us to create side-effects only within a `useEffect` so the lifecycle that StrictMode goes through is very strange:
- A render pass
- A render pass
- Call useEffects
- Call cleanup on useEffects
- Call useEffects again
This is meant to understand whether the functions are indeed memory safe, which I can appreciate but it is very different behavior from what it actually does at runtime:
- A render pass
- Call useEffects
- Call cleanup on useEffects
- A render pass
- Call useEffects
- Call cleanup on useEffects
So this change makes it safe to run useEditor in StrictMode, our test suite was not previously set up to test StrictMode behavior so it was missed in original …
=> fix(react): always attempt to cleanup editor instances, starting from creation #5492

.changeset/fluffy-bears-remember.md, packages/extension-link/src/link.ts, tests/cypress/integration/extensions/link.spec.ts
When [we fixed a XSS vuln](https://github.com/ueberdosis/tiptap/pull/5160), we inadvertently broke the ability to use custom protocols, this PR resolves that by allowing additional custom protocols to be considered valid and not stripped out
https://github.com/ueberdosis/tiptap/issues/5468
=> fix(link): respect custom protocols #5468

.changeset/purple-bobcats-grab.md, .changeset/shaggy-dolphins-applaud.md, packages/core/src/ExtensionManager.ts, packages/core/src/NodeView.ts, packages/core/src/types.ts, packages/extension-task-item/src/task-item.ts, packages/react/src/ReactNodeViewRenderer.tsx, packages/react/src/ReactRenderer.tsx, packages/vue-2/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueNodeViewRenderer.ts
Following suit from this PR https://github.com/ueberdosis/tiptap/pull/5487
I needed to pull the thread to unravel all of these typings to make them correct & sensible again.
Mostly to do with typings rather than implementation. Although it does add selection handling to vue's implementation too
https://github.com/ueberdosis/tiptap/issues/5483
=> refactor(core): update typings for NodeViews to be accurate to implementation #5483

.changeset/chatty-pumas-cross.md, .changeset/rich-waves-study.md, packages/core/src/Editor.ts, packages/core/src/extensions/keymap.ts, packages/core/src/types.ts
- Adds `preventClearDocument` to the clearDocument plugin to fix the main issue in #5490.
- Allows `enableCoreExtensions` to be an object disabling certain core extensions.
- Replaces the nodesBetween empty doc check with isNodeEmpty as requested.
Regarding the disabling of core extensions, @nperez0111, you suggested using `coreExtensionOptions`, but I thought this made a bit more sense. It's only a bit weird in that passing something like `enableCoreExtensions: { keymap: true }` still enables everything. Only passing `false` will disable an extension (leaving others enabled). But I think that would be the most common use case.
Otherwise what sort of interface did you have in mind?
I'm having a bit of issues running cypress locally. But I see the PRs have github actions.
I also tested it …
=> Fix for #5490 - Adds `preventClearDocument` meta + makes it easier to disable specific core plugins.

.changeset/slow-lies-promise.md, packages/extension-task-item/src/task-item.ts
Fixes https://github.com/ueberdosis/tiptap/issues/5519
=> Prevent onBlur being trigged when task item is toggled

.changeset/mean-pets-unite.md, packages/core/src/helpers/createNodeFromContent.ts, tests/cypress/integration/core/createNodeFromContent.spec.ts
An error will be thrown when the JSON content doesn't match the schema nesting rules, and `contentCheck` is set to true.
I added [check](https://prosemirror.net/docs/ref/#model.Node.check) in `createNodeFromContent`
I added a the test `if 'errorOnInvalidContent' is true, will throw an error, when the JSON content does not follow the nesting rules of the schema`
[#5500](https://github.com/ueberdosis/tiptap/issues/5500#issue-2467718220)
=> fix(core): check schema's nesting rules on contentCheck (#5500)

packages/react/src/ReactNodeViewRenderer.tsx
The goal of this PR is to make the react mounting element a bit more identifiable. This should aid the ability to select and style this element via CSS.
Added a data attribute to the element just after it is created, and is confirmed to exist.
=> feat: Add data attribute on ReactNodeView mounting div to assist styling

.changeset/tender-items-visit.md, packages/suggestion/src/suggestion.ts
See discussion here: https://github.com/ueberdosis/tiptap/pull/4380#issuecomment-2306513901
Suggested by @nperez0111.
I checked that this works with the single room collaboration demo opened in different browsers, and manually tested all the small issues for which I recorded small videos in the commented linked above.
=>  fix(suggestion): dropdown can't be closed with `Esc` (#4380)

.changeset/sweet-ants-lick.md, packages/extension-code-block-lowlight/src/lowlight-plugin.ts
Added support for lowlight v2+ method `registered`
I tried not to remove support for earlier versions of lowlight that was implemented in #3155
I checked that after entering ` ```javascript ` and ` ```jsx ` there was the same formatting result. It can be also checked on other aliases that are listed in [highlight.js Supported Languages](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)
#4651
=> fix(extension-code-block-lowlight): support for lowlight v3 aliases

.changeset/rare-berries-sit.md, packages/core/src/plugins/DropPlugin.ts
Fix error "Cannot find module 'packages/pm/model' or its corresponding type declarations." by updating the import of Slice in DropPlugin.
Use `@tiptap/pm/model` instead of `packages/pm/model`.
=> Fix Slice import in DropPlugin

README.md
Great work! Proud to pitch in w/ support!
Just README
n/a
preview mode in gh
n/a
`none`
=> Add Poggio to sponsors list

.changeset/green-wolves-arrive.md, packages/core/src/types.ts
The type for `getPos` inside of `NodeViewRendererProps` was incorrectly typed to indicate that it always returns a number, when this is not the actual case. It can also return `undefined`.
As per the ProseMirror documentation:
> The third argument getPos is a function that can be called to get the node's current position, which can be useful when creating transactions to update it. **Note that if the node is not in the document, the position returned by this function will be undefined**.
Trusting this function to always return a number has lead to some stability issues in our application, so I believe it's best that the type reflects the actual functionality, even if this may cause some headaches to handle `undefined` cases. 
Update the type to point towards …
=> Update `getPos` type inside `NodeViewRendererProps` to reflect actual functionality

.changeset/bright-apples-reflect.md, packages/react/src/Context.tsx
Add `editorContainerProps` to EditorProvider. This will allow to pass HTML attributes to the EditorContent when using EditorProvider
Related discussion - https://github.com/ueberdosis/tiptap/discussions/5656
=> Add editorContainerProps to EditorProvider

.changeset/eighty-pandas-admire.md, package-lock.json, packages/core/src/Editor.ts
This plugs a memory leak where there is a circular reference between the view's DOM node and the editor instance, to resolve this, before destroying the view we need to delete the reference to the editor instance on the DOM node #5654
=> fix(core): dereference editor from DOM element on destroy #5654

.changeset/calm-bottles-shout.md, packages/extension-character-count/src/character-count.ts
Made `CharacterCount`'s text and word counting logic to accessible from outside, which can solve issues with string containing emoji.
I've just added these two options
```tsx
export interface CharacterCountOptions {
/**
* The text counter function to use. Defaults to a simple character count.
* @default (text) => text.length
* @example (text) => [...new Intl.Segmenter().segment(text)].length
*/
textCounter: (text: string) => number
/**
* The word counter function to use. Defaults to a simple word count.
* @default (text) => text.split(' ').filter(word => word !== '').length
* @example (text) => text.split(/\s+/).filter(word => word !== '').length
*/
wordCounter: (text: string) => number
}
```
and default options
```ts
textCounter: text => text.length,
wordCounter: text => text.split(' …
```
=> feat(CharacterCount): Add counter function to `CharacterCount` extension.

.changeset/thirty-apes-boil.md, package-lock.json, packages/starter-kit/package.json
Adds @tiptap/extension-text-style to @tiptap/starter-kit deps but does not install the extension, since it is only to resolve a peer dep install for list-items
#5691
=> fix: add extension-text-style as a dep of @tiptap/starter-kit #5691

.changeset/nervous-bats-film.md, .changeset/sweet-feet-dream.md, packages/core/src/NodePos.ts
This pull request addresses several issues in the `@tiptap/core` package, particularly focusing on fixing problems related to `NodePos` attributes and child positions. The main changes include bug fixes to ensure correct handling of non-text atoms and improvements to the attribute update mechanism.
Bug fixes:
* [`.changeset/nervous-bats-film.md`](diffhunk://#diff-1424d192cc57f5c8573055e8638e1147fd04a613f075b992926e31b64f3b46beR1-R5): Fixed an issue while updating attributes on a `NodePos` that was not a text.
* [`.changeset/sweet-feet-dream.md`](diffhunk://#diff-2b81d02a2b19bd5bae65c933f5e1d881c1ab8286511bad9e7421b5011885a779R1-R5): Fixed issues with `NodePos` child positions causing wrong positions when used on non-text atoms.
Changes:
* …
=> Fix NodePos logic for child position calculation and attribute changes

.changeset/sweet-masks-smash.md, packages/core/src/helpers/getMarkRange.ts, tests/cypress/integration/core/getMarkRange.spec.ts
This pull request addresses an issue in the `@tiptap/core` package where the `getMarkRange` function did not return the correct range when the cursor was at the start of the specified mark. The changes involve both documentation and code modifications to ensure accurate behavior.
* [`packages/core/src/helpers/getMarkRange.ts`](diffhunk://#diff-e265670b2c081e4c8486eb69ad5c34a81f449ba84871895b072de287ed55ab4bL32-R45): Updated the `getMarkRange` function to correctly handle cases where the cursor is at the start of a text node without the mark, ensuring it looks backward and returns the appropriate range.
You can find out more about my implementation from the comments in code. I basically added a forward, then backward check for marks on the current nodes parent with the parent offset. …
=> Fix getMarkRange not finding marks when at the start of a mark

.changeset/soft-peaches-hang.md, packages/core/src/Editor.ts
This pull request focuses on improving accessibility for the contenteditable field in the editor by adding role and aria-label attributes. These changes enhance screen reader support and mouseless controls.
Accessibility improvements:
* [`packages/core/src/Editor.ts`](diffhunk://#diff-9b7c004a70a95a9e7b2b49f3761403a4abfe14fae1490e32c86306794017e27dR355-R362): Added `role="textbox"` and `aria-label="Rich-Text Editor"` attributes to the editor element to improve accessibility.
I added two attributes to the editor's DOM element to allow more screenreaders to understand what kind of element the editor DOM element is. That should help with focus issues in a few instances.
Testing was done locally
1. Use a screenreader (MacOS Voice Over or Windows Narrator for example)
2. Visit a demo locally …
=> Improve accessibility on the editor DOM element

.changeset/calm-carpets-smile.md, packages/extension-bold/src/bold.ts, packages/extension-italic/src/italic.ts
Resolves https://github.com/ueberdosis/tiptap/issues/5585
Adds parse rules to bold & italic that remove marks from their parent styles.
This is a port of `prosemirror-schema-basic`. When parsing a `font-weight=400` or `font-style=normal` style, use the `clearMark` directive to clear the bold or italic marks respectively.
https://github.com/ProseMirror/prosemirror-schema-basic/commit/6521792c10edbaad4d2d10a0b21baa1b56364e82. 
I tested my changes in the demo application. I asserted that HTML inserted into the editor are now parsed as expected, both from the clipboard & directly via `commands.setContent`
Ensure that HTML that nest `font-weight` & `font-style` tags are styled as expected.
**Input**
```html
<p style="font-weight: 700;">
<span style="font-weight: 700;">I am Bold</span>
<span …
```
=> Add clear mark parse rules to bold & italic marks

.changeset/lemon-onions-walk.md, packages/extension-mention/src/mention.ts
Pressing Enter key when using the mention in a bullet list / ordered list would create a new list item instead of adding the mention. Updated the mention extension's priority to fix it.
Update mention extension's priority to 101
https://github.com/user-attachments/assets/0ea45fd8-8b4a-4644-9221-5f68fe3817f1
Fixes #5680
=> Update mention extension's priority

.changeset/blue-poems-camp.md, demos/src/Commands/InsertContent/React/index.spec.js, packages/core/src/commands/insertContentAt.ts
insertContentAt, setContent, and insertContent commands now respect the editor's pre-defined parseOptions configuration if the command does not specify it's own parseOptions
Added Tests
=> fix(core): respect the editor's parseOptions

.changeset/loud-maps-work.md, packages/react/src/useEditor.ts
Updated editable option to be preserved across re-renders
https://github.com/ueberdosis/tiptap/issues/5547
=> fix(react): preserve editable option across renders

.changeset/gorgeous-lizards-roll.md, .changeset/modern-dogs-tie.md, demos/src/Commands/InsertContent/React/index.jsx, demos/src/Commands/InsertContent/React/index.spec.js, demos/src/Demos/CollaborationSplitPane/React/Editor.jsx, demos/src/Demos/CollaborationSplitPane/React/index.jsx, packages/core/src/Editor.ts, packages/core/src/commands/insertContentAt.ts, packages/extension-collaboration/src/collaboration.ts, tests/cypress/integration/core/onContentError.spec.ts
This enables content checking for changes made by the collaboration plugin.
The changes made by the collaboration plugin are outside of the usual flow of content provided on initialization.
So, we need to handle it separately by filtering out the transactions where it occurs
=> feat: in a collab setting, disable transactions that are trying to sync invalid content

demos/src/Commands/SetContent/React/index.spec.js, packages/core/src/commands/insertContent.ts, packages/core/src/commands/insertContentAt.ts, packages/core/src/commands/setContent.ts, packages/core/src/helpers/createDocument.ts, packages/core/src/helpers/createNodeFromContent.ts
I don't know how this has been missed before. Really easy to support this.
Added tests
https://github.com/ueberdosis/tiptap/issues/5764
=> feat(core): allow nodes and fragments to be inserted into the editor using insertContentAt command #5764

packages/core/src/PasteRule.ts, packages/core/src/inputRules/markInputRule.ts, packages/core/src/inputRules/nodeInputRule.ts, packages/core/src/inputRules/textInputRule.ts, packages/core/src/inputRules/textblockTypeInputRule.ts, packages/core/src/inputRules/wrappingInputRule.ts, packages/core/src/pasteRules/markPasteRule.ts, packages/core/src/pasteRules/nodePasteRule.ts, packages/core/src/pasteRules/textPasteRule.ts
Correct the link in the docstrings of InputRules, PasteRules and those related.
=> docs: update link in input and paste rules docstrings

.changeset/serious-coins-fail.md, demos/src/Nodes/Mention/React/styles.scss
Implemented a zero-width space (\u200B) after `.mention` elements to improve cursor positioning and prevent selection issues.
=> fix: add zero-width space to resolve cursor selection issue

.changeset/five-mice-turn.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
The internal implementation of `shouldShow` is using `this.element`.
The user cannot reuse the internal implementation and add some logic, because the `element` parameter is missing.
Add the `element` parameter to `shouldShow`.
Not really tested.
Implements your own `shouldShow`:
```ts
import { isTextSelection } from "@tiptap/core";
import { BubbleMenuPluginProps } from "@tiptap/extension-bubble-menu";
export const bubbleMenuShouldShow: Exclude<BubbleMenuPluginProps["shouldShow"], null> =
({ editor, element, view, state, from, to }) => {
const { doc, selection } = state;
const { empty } = selection;
const isEmptyTextBlock = !doc.textBetween(from, to).length && isTextSelection(state.selection);
const isChildOfMenu = element.contains(document.activeElement);
const hasEditorFocus = …
```
=> Add element to shouldShow in BubbleMenuPlugin

.changeset/witty-olives-protect.md, demos/src/Marks/Link/React/index.jsx, demos/src/Marks/Link/React/index.spec.js, packages/extension-link/src/helpers/autolink.ts, packages/extension-link/src/link.ts
Added a new `shouldAutoLink` function to control the auto-linking of URLs based on specific criteria, such as disallowed domains, and enhanced the existing `validate` function to handle URLs more robustly.
- Created tests to verify that shouldAutoLink does not auto-link URLs with disallowed domains and correctly auto-links valid URLs.
- Updated integration tests for validate to ensure URLs are correctly validated with or without protocols. Verified that URLs with disallowed protocols and domains are not linked.
#5564
=> refactor: adjust validate and add shouldAutoLink to improve URL handling

.changeset/chatty-monkeys-hear.md, packages/extension-list-keymap/src/listHelpers/handleBackspace.ts
Fixes #4368
I figured that just checking if selection's `to` and `from` doesn't match, default backspace behavior will result in expected behavior. So I added check to [handleBackspace.ts](https://github.com/ueberdosis/tiptap/pull/5810/files#diff-15ca0926de038c0b181f99b43c4af4614ecb69b3fe559da219a9001d606bf750R17).
N/A
1. Start development environment and navigate to `/preview/Extensions/ListKeymap`. 
2. Create a list with one or multiple list items, and paragraph underneath. 
3. Select all and hit backspace.
If you created list with one list item there will be no error in console. If you created list with multiple list items, the behavior will be as expected. Compare this with previous behavior either of tiptap's `develop` or [live …
=> List Keymap: Fix backspace behavior when selection is not collapsed

demos/src/Marks/Link/React/index.jsx, packages/extension-link/src/link.ts
As a follow up to this: https://github.com/ueberdosis/tiptap/pull/5808
Adds `isAllowedUri` which handles XSS protections,
deprecates `validate` in favor of the new `shouldAutoLink` which is a better name for what it does
=> fix(link): add backwards compat by deprecating validate and using isAllowedUri instead

.changeset/shy-pigs-exercise.md, packages/core/src/Node.ts, packages/core/src/helpers/getSchemaByResolvedExtensions.ts, packages/extension-hard-break/src/hard-break.ts
- Support the [linebreakReplacement](https://prosemirror.net/docs/ref/#model.NodeSpec.linebreakReplacement) property on Nodes
- Set the `hardBreak` node as the `linebreakReplacement` node, by default.
- Followed the way other properties are defined, such as `whitespace`
- Added the property to hardBreak and verified in the local React CodeBlock example (http://localhost:3000/preview/Nodes/CodeBlock) that toggling from a codeBlock to a normal paragraph visually keeps the line breaks.
**Before:**
https://github.com/user-attachments/assets/4de1753d-6268-402b-b2ff-c8920a5a5f9f
**After:**
https://github.com/user-attachments/assets/cd0177e8-1586-498a-bdf6-09cd672ab20d
- In the CodeBlock example (`tiptap/demos/src/Nodes/CodeBlock/React/index.jsx`) add the `HardBreak` extension
- Run and load the …
=> Add Node linebreakReplacement support and enable on hardBreak nodes

.changeset/long-pears-wash.md, packages/react/src/useEditorState.ts
useLayoutEffect instead of useEffect, to commit changes to page in one pass instead of two
=> fix(react): useLayoutEffect instead of useEffect to cut down on reflow

.changeset/pink-avocados-stare.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
Fixes an issue where the bubble and flaoting menus on blur would remount
https://github.com/ueberdosis/tiptap/issues/3471
Although I do question this one: https://github.com/ueberdosis/tiptap/issues/3471#issuecomment-1782622093
=> fix(bubble-menu): avoid bluring if event is on the editor #3471

.changeset/tiny-buckets-behave.md, demos/src/Extensions/FontFamily/React/index.jsx, demos/src/Extensions/FontFamily/React/index.spec.js, packages/extension-font-family/src/font-family.ts
Font-family extension: Prevent removal of quotes in `parseHTML`
Removing quotes in `font-family` parsing can result in invalid HTML when using font names that contain both spaces and numbers (e.g., "Exo 2").
Initially attempted to add quotes in `renderHTML`, but realized the issue originated in `parseHTML`, where quotes were being removed automatically. Addressed this issue in https://github.com/ueberdosis/tiptap/commit/1af78299247e967a76b400f5db8adf8e28c5e5f2  The reason for this behavior in `parseHTML` is unclear, so further investigation may be required.
All existing tests pass. Added a new test specifically for `font-family` values with both spaces and numbers.
Run the test suite to confirm no regressions.
Verify that fonts with spaces and numbers in their names, like "Exo 2", are …
=> Font-family extension: Prevent removal of quotes in parseHTML

.changeset/wicked-meals-shop.md, packages/core/src/helpers/getMarkRange.ts, tests/cypress/integration/core/getMarkRange.spec.ts
getMarkRange would greedily match more content than it should have if it was the same type of mark, now it will match only the mark at the position #3872
=> fix(core): getMarkRange match only the current mark of a type #3872

.changeset/seven-hats-thank.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
Our sentry is full of "Cannot read properties of null (reading 'dataset')" which point to [this place](https://github.com/ueberdosis/tiptap/blob/2ea807d1db03c44a2af8fea9d176e9cbb5b71800/packages/extension-bubble-menu/src/bubble-menu-plugin.ts#L269) in the `getReferenceClientRect` for tippy in the `BubbleMenu` extension. This PR just adds an additional nullability check.
=> Prevent null pointer exception in `BubbleMenu`

packages/extension-link/src/helpers/clickHandler.ts
Fix the type assertion of file [packages/extension-link/src/helpers/clickHandler.ts](https://github.com/ueberdosis/tiptap/blob/87d63d8d1761138add50e05d584e6f24d99daf9c/packages/extension-link/src/helpers/clickHandler.ts#L35)
> The HTMLLinkElement interface represents reference information for external resources and the relationship of those resources to a document and vice versa (corresponds to [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) element; not to be confused with [a](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), which is represented by [HTMLAnchorElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement)). This object inherits all of the properties and methods of the …
=> fix(link): change type HTMLLinkElement to HTMLAnchorElement

packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
It seems that updating types is a catch-22 and I don't have the time to be resolving this, will reopen #5768 and let someone else implement this at another time
- **revert: "fix(core): update the typings to be that options and storage are partials on an extended config #5852 (#5854)"**
- **revert: "fix(core): update the typing of `addOptions`, `addStorage` to have an optional parent #5768 (#5770)"**
=> fix: revert type changes introduced with 2.10 #5859

.changeset/chilled-pigs-drum.md, packages/extension-character-count/src/character-count.ts
Fixes #5851
https://github.com/user-attachments/assets/48554ff9-308e-482a-a083-1164d3ffe4ef
=> fix: #5851 - While setting content directly while using CharacterCount with limit is not obeyed

demos/src/Extensions/FontFamily/React/index.jsx
This PR aims to fix the [Font Family extension](https://tiptap.dev/docs/editor/extensions/functionality/fontfamily#page-title) demo
Correctly make use of the returned value from the `textStyle` API
Demo is correctly working
Will update the docs with additional information for the users about the returned value from `textStyle` API so they don't get confused it this happens to them while setting the plugin
=> fix: font family extesion demo

demos/src/Extensions/FontFamily/React/index.jsx, demos/src/Extensions/FontFamily/React/index.spec.js
Remove an unused test since we do already check for font family with spaces in a previous test and we already have a documentation pointing out how you should expect the font family to be checked
`N/A`
`N/A`
`N/A`
`N/A`
https://github.com/ueberdosis/tiptap-docs/pull/71
https://github.com/ueberdosis/tiptap/pull/5880
=> fix: remove unused spec for font family extension

.changeset/unlucky-ravens-build.md, packages/extension-link/src/link.ts
Prosemirror replaces zero-width non-joiner characters with Object Replacement Character from unicode. Therefore, linkifyjs does not recognize the link properly. We replace these characters with regular spaces to fix this issue.
Special Character Replacement
Tested within the demo with the provided content that produced the issue
`N/A`
`N/A`
https://github.com/ueberdosis/tiptap/issues/5679
=> fix: extension link object replacement caracter sanitization

packages/core/src/commands/focus.ts
When using the `focus` command in a toolbar/menubar element to toggle formatting of the selected text, the editor briefly loses focus then gains it back. This happens only on Android devices and it makes the virtual keyboard flashes (it closes down then shows up again quickly, sometimes not even showing up).
<details>
<summary>Screen recording</summary>
https://github.com/ueberdosis/tiptap/assets/33684291/9b94d45e-495a-4c24-94f8-2407608bd394
</details>
This issue is reported [here](https://github.com/ueberdosis/tiptap/issues/1806) but no one has solved it for Android.
I just modified the `focus` command's code to remove the `isiOS` check so `(view.dom as HTMLElement).focus()` is always executed.
When reading the [reported issue](https://github.com/ueberdosis/tiptap/issues/1806), I found a …
=> Fix losing text selection/focus briefly when using the `focus` command on Android

.changeset/yellow-cats-teach.md, packages/extension-font-family/src/font-family.ts, packages/extension-text-style/src/text-style.ts
We were handling incorrectly the removal of styles by calling `command.unsetMark(this.name)` at the `removeEmptyTextStyle`. This was causing the removal of all of the marks from the node itself and all their descendants and this was causing the loss of all of the inline styles that were applied across the selection.
In order to fix this issue, we were in the need to manually and properly handle the selection and all of the nodes within the selection and check their marks independently to make sure we're not throwing away inline styles that were not related to unsetting the font family or any other unset of marks.
https://github.com/user-attachments/assets/88c1302d-e44e-4837-8b4c-c9f1697e5b71
1. Pull the branch.
2. Access `demos/Extensions/FontFamily/React/index.jsx`
3. Paste the attached …
=> fix: remove empty text style handling

.changeset/itchy-carrots-melt.md, packages/extension-code/src/code.ts
Rewrite the extension-code regex to avoid lookbehind to fix errors in safari versions 16.4 and older.
I tested the regex in regex101 to ensure it continues to work as expected.
I checked to ensure that this actually works in older safari versions.
https://github.com/ueberdosis/tiptap/issues/5889
=> fix(extension-code): support safari versions 16.4 and older

.changeset/empty-seals-join.md, demos/src/Marks/Link/React/index.jsx, packages/extension-link/src/link.ts
This pull request includes changes to improve error handling and validation for links in the `Link` extension. The most important changes include adding error handling in the React component, exporting the `isAllowedUri` function, and validating link protocols before setting or toggling links.
I added checks inside the `setLink` and `toggleLink` commands to see if the link being tried to set is actually valid. If not, we throw an error so the developer can implement error handling outside of the extension.
```js
try {
editor.chain().setLink('javascript:alert("Hello world")').focus().run()
} catch (e) {
if (e.message === 'Invalid protocol') {
alert('Please don\'t put XSS injections into our content please.')
}
}
```
1. Tested it locally on the Link demo (where I also added said check + …
=> Fixed Link extension's commands not respecting XSS prevention via unallowed protocols

.changeset/tame-worms-applaud.md, packages/core/src/Editor.ts, packages/core/src/types.ts
Do not attempt to reapply events which result in the same editor state
https://github.com/ueberdosis/tiptap/issues/4535
=> perf(core): if a transaction is a no-op do not attempt to re-apply it #4535

.changeset/early-parrots-carry.md, packages/react/src/ReactNodeViewRenderer.tsx
This PR addresses a crash in the ReactNodeView implementation that occurs when the handleSelectionUpdate callback is triggered before the renderer is initialized. The issue arises due to the asynchronous nature of JavaScript, where the subscription to the selectionUpdate event (editor.on) is executed before the renderer initialization.
The proposed fix ensures that the renderer is initialized before subscribing to the selectionUpdate event, maintaining the intended execution order.
The subscription to the selectionUpdate event was moved to occur after the initialization of the renderer. This ensures the callback does not execute prematurely and prevents the crash. The implementation adds no new functionality or logic but rearranges the code to avoid the race condition.
The fix was tested …
=> fix: handleSelectionUpdate callback is triggered before the renderer is initialized.

.changeset/silly-wolves-attack.md, packages/vue-3/src/VueNodeViewRenderer.ts
I was trying to follow the step from [render-a-vue-component](https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/vue#render-a-vue-component) section. Everything works except that there was a type error when I pass the customized component to `VueNodeViewRenderer`. After some searchs, now I think some props are missing. Thus adding them on could be a fix if the absence is not on purpose.
add 3 missing props declaration to the `nodeViewProps` object
error resolved after the change
=> fix: add missing node view props to props type object

.changeset/popular-owls-rhyme.md, packages/react/src/useEditor.ts
This does a shallow diff between the current options and the incoming ones to determine whether we should try to write the new options and incur a state update within the editor.
It purposefully is not doing a full diff as several options are known to be problematic (callback handlers, extensions array, the content itself), so we rely on referential equality only to do this diffing which should be fairly fast since there are only about 10-15 options, and this diffs only the ones the user has actually attempted to set.
=> perf(react): do some light diffing to not reset options on every render #6024

.changeset/perfect-pillows-rhyme.md, packages/core/src/extensions/keymap.ts
Fixed the bug reported in #5733. On iOS Safari and WebView, when the document is empty and a decoration is applied, inputting and confirming text using Japanese IME or similar would reset the decoration. This issue has now been resolved.
The clearDocument plugin is now configured not to execute while IME input is active.
1. Clear the document.
2. Apply H1 decoration.
3. Use the iOS virtual keyboard to input text and confirm with the IME.
4. Verify that the decoration is not cleared.
1. Clear the document.
2. Apply H1 decoration.
3. Use the iOS virtual keyboard to input text and confirm with the IME.
4. Verify that the decoration is not cleared.
The decoration is now preserved as shown below.
https://github.com/user-attachments/assets/95207b8b-4405-40e6-8b5c-4e9d605941f3
- #5733
=> fix: Text Formatting Effects Reset After Input Confirmation with Japanese IME on Mobile Browsers (Safari & Chrome)

.changeset/thirty-deers-attend.md, packages/core/src/commands/focus.ts
A change was introduced in v2.11.0 to [fix losing text selection/focus when using the `focus` command on Android](https://github.com/ueberdosis/tiptap/pull/4448/files). This PR effectively reverts this change, while updating the conditional logic to be more narrowly scoped to solve the issue for Android as originally intended.
The previous logic in this function was scoped to just iOS, so I simply added an Android check in the same `if` statement. The removal of the `if` statement altogether introduced new behavior to all implementors of `focus`, which in my case (Chrome, web) led to undesirable behavior of the page jumping to the top of the editor.
No testing done -- no devices to test with
No verification done
I think this is a pretty simple solution when you compare the previous and …
=> fix(core): fix focus issue introduced in v2.11.0

.changeset/moody-geckos-sort.md, .changeset/tidy-fireants-hang.md, demos/src/Commands/SetContent/React/index.spec.js, demos/src/GuideContent/ExportHTML/React/index.jsx, demos/src/GuideContent/ExportJSON/React/index.jsx, demos/src/GuideContent/ExportJSON/Vue/index.vue, demos/src/GuideContent/ReadOnly/React/index.spec.js, demos/src/GuideContent/ReadOnly/Vue/index.spec.js, demos/src/GuideGettingStarted/VModel/Vue/Editor.vue, packages/core/src/commands/clearContent.ts, packages/core/src/commands/setContent.ts
The current setContent command signature was a bit strange, why would it default to NOT emitting updates? Why was the signature a bunch of options as separate arguments.
This cleans up the function signature and uses a better default
=> refactor(core): update setContent command signature for better defaults

.changeset/red-ants-wonder.md, demos/src/Extensions/CollaborationWithMenus/React/index.spec.js, packages/core/src/Editor.ts, packages/core/src/types.ts, packages/core/src/utilities/elementFromString.ts, packages/react/src/EditorContent.tsx, packages/vue-2/src/EditorContent.ts, packages/vue-3/src/EditorContent.ts
This introduces a new behavior for the editor. The ability to be safely run on the server-side (without rendering).
prosemirror-view encapsulates all view related code, and cannot safely be SSR'd, but, the majority of the editor instance itself is in plain JS that does not require DOM APIs (unless your content is specified in HTML).
But, we have so many convenient methods available for manipulating content, that it is a shame that they could not be used on the server side too. With this update, the editor can be rendered on the server-side and will use a stub for prosemirror-view methods. If accessing certain functions on the view, you will encounter runtime errors, so it is important for you to test to see if the methods you call actually work.
This is a step towards being able to …
=> feat(core): introduce new mounting system for SSR

.changeset/yellow-hairs-search.md, packages/extension-text-align/src/text-align.ts
The default value of `defaultAlignment` is `null` in the code. Modify the documentation so that it matches the value in the code.
In the code of the TextAlign extension, the default value of the `defaultAlignment` property is `null`.
However, the documentation of the property says that its default value is `"left"`. The documentation does not match the code. By default, if the `defaultAlignment` property is not configured, the text alignment of a block is unset.
One might argue that, if the text alignment of a block is unset, its alignment is left in practice, but this is not always true. For example, if the parent element of the text editor has right text alignment, the text blocks will have right alignment too.
Modify the documentation
There were no changes to the code, only in the …
=> Modify the TextAlign extension documentation so that the default value of the defaultAlignment option matches the code

.changeset/eighty-gifts-matter.md, demos/package.json, demos/src/Experiments/CollaborationAnnotation/Vue/extension/AnnotationState.ts, demos/src/Experiments/MultipleEditors/Vue/index.vue, packages/extension-collaboration-cursor/package.json, packages/extension-collaboration-cursor/src/collaboration-cursor.ts, packages/extension-collaboration/package.json, packages/extension-collaboration/src/collaboration.ts, packages/extension-collaboration/src/helpers/isChangeOrigin.ts, pnpm-lock.yaml
This pull request focuses on replacing the `y-prosemirror` package with the `@tiptap/y-tiptap` package across various files and configurations. The changes ensure consistency and compatibility with the updated package.
* [`demos/package.json`](diffhunk://#diff-2759f93cee6a28002b544bc4f705b4890d72bbb85eea0d7ff670da00277e70f4R18): Added `@tiptap/y-tiptap` and removed `y-prosemirror`. [[1]](diffhunk://#diff-2759f93cee6a28002b544bc4f705b4890d72bbb85eea0d7ff670da00277e70f4R18) [[2]](diffhunk://#diff-2759f93cee6a28002b544bc4f705b4890d72bbb85eea0d7ff670da00277e70f4L44)
* [`packages/extension-collaboration-cursor/package.json`](diffhunk://#diff-c973c19872ef6828b7fa6f3c72e514c0b787c0dc3aeddbb00fca92b442f85a02L36-R41): Replaced `y-prosemirror` with `@tiptap/y-tiptap` in both `devDependencies` and …
=> use @tiptap/y-tiptap instead of y-prosemirror

.changeset/three-crabs-beg.md, packages/extension-link/src/link.ts
This PR allows numbers in links, especially in emails. Before something like test1@example.com did not work.
=> fix(extension-link): update regex to allow numbers in URI

.changeset/tricky-apples-design.md, package-lock.json, packages/pm/package.json
This PR upgrades prosemirror-tables to 1.6.3 to fix an issue with cells being resizable when the editor is uneditable.
This pull request includes an upgrade to the `prosemirror-tables` dependency to address a specific issue with table cell resizing in the editor. The most important changes include updating the version of `prosemirror-tables` in the package file and documenting the upgrade in the changelog.
Dependency updates:
* [`packages/pm/package.json`](diffhunk://#diff-1ff088f5119ba6763199900bf03abb875b773a3a12c0cec1c463396b60d8243cL143-R143): Upgraded `prosemirror-tables` from version 1.6.1 to 1.6.3 to fix an issue where cells were resizable while the editor was uneditable.
Documentation:
* [`.changeset/tricky-apples-design.md`](diffhunk://#diff-c1379d108abe83650d91dd6076b202a656bcb9a …
=> upgrade prosemirror-tables to 1.6.3

.changeset/shiny-rabbits-invite.md, packages/extension-ordered-list/src/ordered-list.ts
Use `null` for the default type value, instead of `undefined`.
This has no implication on the usual flows, but fixes an issue when exporting & importing the schema as JSON, as `undefined` is not a valid value in JSON.
It would lead to "RangeError: No value supplied for attribute type" when using the exported schema e.g. in `prosemirrorJSONToYDoc` from y-prosemirror.
Used the patched OrderedList in my projects & I've seen no changes in behaviour or issues.
Tested the schema export via this script:
```
const spec = {
nodes: {},
marks: {},
};
schema.spec.nodes.forEach((key, value) => (spec.nodes[key] = value));
schema.spec.marks.forEach((key, value) => (spec.marks[key] = value));
exportedSchema = JSON.stringify(spec);
```
Which now exports the schema correctly & I can use it for e.g. the …
=> fix: use null in ordered list's default type value

packages/starter-kit/package.json, pnpm-lock.yaml
StarterKit fails to load b/c it's missing `extension-list`
=> starter kit: add missing dependency

packages/core/src/Editor.ts
This PR fixes an infinite loop caused by #6233 which lead to an invalid `editor.isDestroyed` value as the `editorView.isDestroyed` value was wrongfully negated.
Removed the negation to make sure `editor.isDestroyed` returns the correct state as otherwise renderers will try to re-create the editor forever.
- Did a manual test on my device
- see above
- N/A
=> Fix invalid editor.isDestroyed value

.changeset/lucky-bears-exercise.md, packages/core/src/Editor.ts
This resolves a minor logic bug, where passing an array of plugins to remove would only remove the last item in the list of plugins to remove.
This resolves the logic error by appropriately filtering out the array at each step (as opposed to continously filtering from the same starting array).
Trivial to understand
This bug is also present in the `next` branch, but I choose to backport the fix & `next` can pull it in later
=> fix(core): allow unregistering multiple plugins

.changeset/spotty-cobras-shake.md, demos/src/Extensions/TextAlign/React/index.jsx, demos/src/Extensions/TextAlign/React/index.spec.js, demos/src/Extensions/TextAlign/Vue/index.spec.js, demos/src/Extensions/TextAlign/Vue/index.vue, packages/extension-text-align/src/text-align.ts
when I write a toolbar component. I found most format can use togglexxx to switch format state. but text align need manual judgment and setting. I add `toggleTextAlign` that can switch align state easily
=> feat(text-align): add toggle command

demos/package.json, packages/extension-collaboration-caret/package.json, packages/extension-collaboration/package.json, pnpm-lock.yaml
This pull request updates the `@tiptap/y-tiptap` package to version `^3.0.0-beta.3` across multiple files and configurations. The update ensures compatibility with the latest features and improvements in the beta release of the package. Below are the key changes grouped by theme:
* Updated `@tiptap/y-tiptap` from `^2.0.0` to `^3.0.0-beta.3` in `dependencies` of `demos/package.json`.
* Updated `@tiptap/y-tiptap` from `^2.0.0` to `^3.0.0-beta.3` in `devDependencies` and `peerDependencies` of `packages/extension-collaboration-caret/package.json`.
* Updated `@tiptap/y-tiptap` from `^2.0.0` to `^3.0.0-beta.3` in `devDependencies` and `peerDependencies` of `packages/extension-collaboration/package.json`.
* Updated the `specifier` and `version` of `@tiptap/y-tiptap` to `^3.0.0-beta.3` in …
=> upgrade y-prosemirror

.changeset/quiet-falcons-study.md, packages/react/src/ReactMarkViewRenderer.tsx
I modified the type of MarkViewContent to allow specifying any HTML element, as it previously only accepted span and undefined.
Fixed MarkViewContentProps as type to use T instead of passing NoInfer<T>.
All tests passed locally.
I have confirmed that tsc passes in local.
However, I could not find a Cypress test for this fix.
https://github.com/ueberdosis/tiptap/discussions/6323#discussioncomment-13105496
=> Allow setting HTML tags other than <span> for "as" in MarkViewContent

.prettierignore, package.json
Do not log all files that are analyzed by Prettier when you run the lint:fix command
Prevent prettier from formatting lockfiles
Modify the lint:fix command
Add a .prettierignore file
Run the lint:fix command
run the lint:fix command
=> Do not log all files when you run the lint:fix command

.changeset/clever-hats-count.md, packages/extension-youtube/src/utils.ts, tests/cypress/integration/extensions/youtube.spec.ts
Start timestamps are currently not embedded with `youtu.be` and `youtube.com/watch` URLs. There are also inconsistencies with how `youtu.be` and `youtube.com/watch` URLs are parsed, and with how search params in the original URL are being handled.
This PR refactors the `getEmbedUrlFromYoutubeUrl` function to use the [native URL object](https://developer.mozilla.org/en-US/docs/Web/API/URL) to create the embed URL. It also converts the start timestamps like `t=10` in `youtu.be` and `t=10s`  in `youtube.com/watch` to `start=10` in `youtube.com/embed` URLs. This should resolve https://github.com/ueberdosis/tiptap/discussions/5765.
As an added bonus, it also appears that Shorts URLs are not embedded correctly. It's fixed in this PR. While I'm at it, I also added support for Live URLs, so this …
=> Support start timestamps, fix Shorts & Live embed URLs

packages/core/package.json
Fixes #6389
This PR adds missing entry `jsx-dev-runtime` (introduced in #5558) to `@tiptap/core` package.
I have added `jsx-dev-runtime` to the `files` list in `package.json`. The directory is currently excluded from the distro because of it.
I did manual testing via `npm publish --dry-run --tag next` to make sure the directory is included in the output.
=> fix(jsx): list jsx-dev-runtime in package.json in files

.changeset/good-trainers-train.md, packages/react/src/ReactRenderer.tsx
This pull request addresses a bug related to `ref` props in React components and introduces improvements to component type checks for better compatibility with React 18 and 19. The most important changes include fixing the bug, adding utility functions to check component types, and updating the logic for handling `ref` props.
* [`packages/react/src/ReactRenderer.tsx`](diffhunk://#diff-5400690d6e1e2a99f31d83216b79a9e77e1f6eb0f0362b6f6c71ddd3e42a043aL30-R78): Added new utility functions `isMemoComponent` and `canReceiveRef` to determine if a component is memoized or can safely receive a `ref` prop. These functions improve the handling of various component types, including class components, `forwardRef` components, and memoized components.
* …
=> fix incorrectly added ref props

.changeset/dry-monkeys-learn.md, packages/static-renderer/src/pm/react/react.ts, tests/cypress/integration/static-renderer/react-string.spec.ts
This pull request addresses a bug in the `@tiptap/static-renderer` package and introduces improvements to attribute mapping for React compatibility. The changes include fixing how inline styles are handled, exporting a utility function for broader usage, and adding a test to ensure the correct functionality of the updated logic.
* **Bug Fix in Inline Styles**: Resolved an issue where inline styles were being parsed as strings instead of objects in React. The `mapAttrsToHTMLAttributes` function now converts style strings into camelCase style objects as expected by React. [[1]](diffhunk://#diff-792896248ab7ccc276c059e2fbadfde637503087c9541b2ad7acf74c80dfd2e8R1-R5) [[2]](diffhunk://#diff-b80b2d335cad7085abdc2238fbeb3205dd0909b6305f9486a472e55afe94a003R25-R41)
* **Exporting Utility …
=> fix react static renderer to parse inline styles as string

.changeset/serious-rings-end.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
This pull request enhances the `BubbleMenuPlugin` and `FloatingMenuPlugin` by adding lifecycle event handlers (`onShow`, `onHide`, `onUpdate`, and `onDestroy`) and improving visibility state management. These changes provide more control over the behavior of the menus and make the plugins more extensible.
* Added new optional lifecycle event handlers (`onShow`, `onHide`, `onUpdate`, `onDestroy`) to the `BubbleMenuPluginProps` interface, allowing users to hook into menu visibility changes.
* Introduced an `isVisible` property to track the visibility state of the bubble menu, ensuring proper handling of repeated show/hide calls.
* Updated the `show`, `hide`, and `destroy` methods to invoke the corresponding lifecycle event handlers (`onShow`, `onHide`, `onDestroy`) when the menu's state …
=> add missing event options for bubble and floating menu

demos/src/Nodes/Mention/React/suggestion.js, demos/src/Nodes/Mention/Vue/suggestion.js
This pull request includes a small but important change to the `onExit` method in two files. The change ensures that the `component.element` is removed from the DOM after the component is destroyed.
* [`demos/src/Nodes/Mention/React/suggestion.js`](diffhunk://#diff-02fe02afccce59e6842070e581311650487b18f84d73f5308c27cc9dce47cdfaR99): Added `component.element.remove()` to the `onExit` method to clean up the DOM.
* [`demos/src/Nodes/Mention/Vue/suggestion.js`](diffhunk://#diff-d8fcfd24bf92a72b66d700da0f205b055ae1bba35efc5b3864a0b84394a8d4e5R103): Added `component.element.remove()` to the `onExit` method to clean up the DOM.
fixes #6350
=> Remove stuck DOM elements after suggestions are removed

.changeset/early-guests-melt.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
This pull request enhances the `BubbleMenuPlugin` in `packages/extension-bubble-menu` by improving the handling of cell selections in the editor. It introduces a utility function to combine DOM rectangles and updates the logic for positioning the bubble menu when a cell selection is detected.
* **Added `combineDOMRects` utility function**: This function calculates a bounding rectangle that encompasses two DOM rectangles, ensuring proper handling of multi-cell selections. (`packages/extension-bubble-menu/src/bubble-menu-plugin.ts`, [packages/extension-bubble-menu/src/bubble-menu-plugin.tsR15-R44](diffhunk://#diff-30fdbcf134f53a22876c93ec1e76674f6afef97f9b6162c7eb39b00bb7eef953R15-R44))
* **Updated `updatePosition` method in `BubbleMenuView`**: Enhanced the logic to detect cell selections …
=> Enhance bubble menu positioning for table cell selections

.github/workflows/publish.yml, package.json
This PR replaces the publish script so it uses `changeset publish`. This only publishes packages that actually were version bumped (or were not published yet) - this helps us to only publish packages that need to be re-published & avoid CI failures.
**Important Note**: `changeset publish` will always use the `pre` tag defined for changesets so after this PR is merged, changes that were previously deployed on `@next` will now be deployed as `@beta` (which objectively will be better **BUT** will require Tiptap users to adjust their dependencies).
This pull request updates the publishing workflow and the `publish` script in `package.json` to improve consistency and streamline the release process. The most important changes involve replacing custom logic for determining the publish tag with …
=> use changeset publish instead of manually publishing via pnpm

.changeset/modern-kangaroos-teach.md, .changeset/silver-roses-joke.md, packages/core/src/utilities/canInsertNode.ts, packages/core/src/utilities/index.ts, packages/extension-horizontal-rule/src/horizontal-rule.ts
This pull request introduces a bug fix for the horizontal rule extension and adds a new utility function to the core package for checking node insertion feasibility. The most notable changes include implementing the `canInsertNode` utility function, integrating it into the horizontal rule extension, and ensuring the `setHorizontalRule` command respects insertion constraints.
* [`.changeset/modern-kangaroos-teach.md`](diffhunk://#diff-120e7c73ab740c536484396991612d508c2362596d5be92a1cf1e86f5e1b7a36R1-R5): Fixed a bug causing the `setHorizontalRule` command to always return `true` when checked via `can()`.
* [`packages/extension-horizontal-rule/src/horizontal-rule.ts`](diffhunk://#diff-4dbed6cc257234c3325bd2f2d58f624d41e50881c51bf5acb92a9736546a2c81R54-R58): Updated the `setHorizontalRule` …
=> Fix horizontal rule `can()` check always returning true

.changeset/wet-rice-suffer.md, packages/core/src/commands/insertContentAt.ts
… would replace the existing one.
This PR fixes an issue that was brought up by a community member.When I add a image, then add a new empty paragraph below and add a new image with the cursor at the first position of the new empty paragraph, the editor replaced the preceding image.
The commit in #5651 did not handle the case where the text content is empty, which could lead to incorrect expansion of the selection. This fix adds a check for empty text content.
manual tests
[](https://github.com/ueberdosis/tiptap/pull/5651)
https://github.com/ueberdosis/tiptap/issues/6401
=> Fix issue where inserting an image below an existing image #6401

.changeset/spicy-horses-smoke.md, packages/core/src/PasteRule.ts
Currently, if a drag and drop operation is performed between two tiptap editors, the content in the source editor is deleted regardless of it's editable property.
With this PR, the source content is only deleted if the source editor is editable.
https://github.com/user-attachments/assets/225f7517-332b-4d93-aae4-1f96cfd19742
I only introduced the editable condition before deleting the source editor's text range.
I reproduced the issue in a sandbox: https://codesandbox.io/p/devbox/compassionate-dhawan-7p3qcy
I checked out the repo locally, made the change, ran the tests and verified the intended behavior
I checked out the repo locally, made the change, ran the tests and verified the intended behavior
-
-
=> On drop: delete selection in source tiptap only if editable

.changeset/silly-hats-doubt.md, packages/core/package.json, packages/core/src/Editor.ts, packages/core/src/types.ts, pnpm-lock.yaml
This PR adds [ProseMirror Devtools](https://github.com/d4rkr00t/prosemirror-dev-tools) as an integration right into the core. I thought about how to build it to make sure this doesn't pollute our users code if it is not needed as we don't want to bundle dev tools with Tiptap.
My conclusion was to lazy-load the dependency and **don't deliver it with Tiptap**. How it's integrated now only installs the devtools as a dev dependency which means users will need to install the prosemirror-dev-tools package manually. There are also no peer or optional dependencies for this.
I'm not the pro when it comes to how build tools bundle and tree-shake code but this should be pretty bulletproof when it comes to the bundle as when the dev tools are not loaded, they will not be imported.
The devtools also …
=> Add lazy-loaded ProseMirror Devtool integration to Core

.changeset/slow-mails-vanish.md, packages/core/src/commands/cut.ts
Fixes a RangeException that is thrown when calling `commands.cut` with `targetPos = 0`, i.e. start of document
Use `Math.max` to ensure that start position of TextSelection is always greater-equal to zero.
Tested in own project by calling `commands.cut` with `targetPos = 0`
Call `commands.cut` with `targetPos = 0` and check for no RangeException to be thrown and content to be inserted at start of document.
-
#6450
=> fix(commands): Fix RangeException on cut to document start

.changeset/five-rules-pull.md, packages/extension-emoji/src/emoji.ts
This PR adds a alt tag to emoji fallback images ensuring better a11y results.
This pull request introduces a minor improvement to the `@tiptap/extension-emoji` package by adding an `alt` tag to the emoji extension, enhancing accessibility.
Accessibility improvement:
* [`.changeset/five-rules-pull.md`](diffhunk://#diff-d3faea9a86577007663296de25356e29b715e4fcb4b00cacee1b0f36560808c9R1-R5): Documented the addition of an `alt` tag as a patch change for the `@tiptap/extension-emoji` package.
* [`packages/extension-emoji/src/emoji.ts`](diffhunk://#diff-49e6b314687626255e0569b417deb0efa514ec2b21fb3f6146e4e8d253801df3R221): Updated the `Emoji` node to include an `alt` attribute with the emoji's name (e.g., "smile emoji") to improve accessibility.
=> add alt attribute to emoji extension for accessibility

.changeset/cyan-starfishes-dream.md, .changeset/stale-ties-press.md, packages/react/src/ReactRenderer.tsx
This PR reverts the change of #6538 because it introduced a lot of problems with async vs sync rendering leading to infinite rendering cycles.
=> revert flushSync removal

.changeset/gorgeous-buses-fly.md, packages/core/tsup.config.ts
Mark prosemirror-dev-toolkit dependency as an external module because otherwise the minified code is not compatible with turbopack
Edit tsup config
Tested that the minified code did not give problems with turbopack anymore.
Install in a Next.js project and run it
=> Mark prosemirror-dev-toolkit library as an external module

.changeset/tidy-humans-join.md, packages/extension-drag-handle/src/drag-handle-plugin.ts
This PR fixes a bug introduced by #6595 that blocks other key handlers from running
I just always remove false from the keydown handler to allow other events to run through
=> fix problems with keydown events being blocked by drag handle plugin

.changeset/grumpy-seals-shake.md, .changeset/two-chefs-lie.md, packages/core/src/jsx-runtime.ts, packages/extension-blockquote/src/blockquote.tsx, packages/extension-bold/src/bold.tsx
This PR fixes a bug introduced by 3.0.0's `jsx-runtime` that caused issues with global React types.
This pull request addresses issues with type conflicts between Tiptap's JSX runtime and React's typings, simplifies type handling in extensions, and improves compatibility when `/** @jsxImportSource @tiptap/core */` is not used. The most important changes include refining JSX type definitions, removing unnecessary type overwrites, and updating extensions to align with the new type system.
* [`packages/core/src/jsx-runtime.ts`](diffhunk://#diff-9e42edb86426415fbe4c3d7f5e359cdd784e7bd454e022600bbaf91ffb1708adL16-R26): Refined Tiptap's JSX runtime types to avoid conflicts with React's typings. These types now apply only when `/** @jsxImportSource @tiptap/core */` is explicitly used.
* …
=> fix global react overwrites via jsx-runtime

.changeset/two-geese-work.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
This PR fixes a Typescript bug where extended configs would lose context to `this` inside functions when any non-function option like `priority` was set.
This pull request introduces improvements to the type definitions for the `extend` method in the `Extension`, `Mark`, and `Node` classes within the `@tiptap/core` package. These changes ensure better overload handling and type safety when extending configurations. Additionally, a changeset file documents the patch version update for this fix.
* **`Extension` class (`packages/core/src/Extension.ts`)**: Added overloads for the `extend` method to support configurations passed as either a function or an object, improving type clarity and flexibility.
* **`Mark` class (`packages/core/src/Mark.ts`)**: Updated the `extend` method with similar …
=> Fix typescript loosing context to "this" when non-function options are set in extended extensions

.changeset/brave-zoos-cheat.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
This PR fixes a problem introduced by #6645
Instead of using overloads creating broken union types for the extend return type which in turn broke chaining we use ThisType to get the correct types for this.
=> fix broken chain types

.changeset/afraid-oranges-smell.md, demos/src/Extensions/BubbleMenu/React/index.jsx, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
This PR fixes a bug with the new menus when the `inline` option is enabled.
This pull request addresses a bug related to virtual elements missing the `getClientRects` method and improves the functionality of the `BubbleMenu` and `FloatingMenu` components. The most important changes include fixing the virtual element issue, updating menu options, and ensuring proper button attributes in the demo.
* [`packages/extension-bubble-menu/src/bubble-menu-plugin.ts`](diffhunk://#diff-30fdbcf134f53a22876c93ec1e76674f6afef97f9b6162c7eb39b00bb7eef953R319-R322): Updated the `BubbleMenuView` class to include `getClientRects` in the virtual element using `domRect`.
* [`packages/extension-floating-menu/src/floating-menu-plugin.ts`](diffhunk://#diff-38847814cfb3e8f7590cb4b22ce7ad8f53915fad16a384d379ddec52a6 …
=> fix broken menus when inline is true

.github/workflows/build.yml, .github/workflows/publish.yml
This PR updates our workflows to only run on main, develop and the publish workflows should only run on main (stable) and release/* for specific release branches like `release/beta` if needed in the future.
=> only run deployments on main & release/* branches

demos/src/Extensions/CharacterCount/React/index.jsx
This is fix for the React demo of CharactersCounts.
I used simple two states to store the characters and words count. I used two events onUpdate and onCreate to correctly handle the update and initial state.
Just run the app locally and go to the demo and see if counting words and characters works.
-
https://github.com/ueberdosis/tiptap/issues/6699
=> dosc: Fixed the React example for CharacterCount extension

.changeset/large-mugs-like.md, packages/static-renderer/src/pm/markdown/markdown.ts
in renderToMarkdown, when rendering links the code was erroneously trying to pick the href from the node. This PR changes to pick it out of the mark instead.
Changed node for mark
I patched tiptap in my project using patch-package with the same change made here and it works.
use renderToMarkdown on a doc with links in, and inspect the markdown to ensure the href is rendered as expected
#6742
=> Use href attribute from `mark` instead of `node` in renderToMarkdown

.changeset/polite-beans-juggle.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-bubble-menu/src/bubble-menu.ts
Add an `appendTo` option to extension-bubble-menu, modeled on [tippy's appendTo option](https://atomiks.github.io/tippyjs/v6/all-props/#appendto).
Add the option following the example of other options, and use it in the one relevant line (show's appendChild call).
Copied the built code into our app and verified that menu was appended to the given element, similar to the 2.x behavior with tippy's appendTo option. In our app, this fixes some z-index issues by portaling the menu into the page's root stacking context.
=> feat: BubbleMenu appendTo option

.changeset/many-timers-argue.md, packages/extension-emoji/src/emoji.ts
This PR fixes an issue where emoji processing interferes with IME (Input Method Editor) composition, particularly affecting Japanese, Chinese, and Korean input methods.
Added a check to skip emoji processing in the `appendTransaction` hook when the editor is in IME composition mode (`editor.view.composing`). This prevents the emoji
extension from interfering with the IME's text conversion process.
- Tested with Japanese IME to ensure emoji characters are not processed during composition
- Verified that emoji conversion still works correctly after IME composition is complete
- Confirmed no regression in regular emoji input without IME
1. Enable an IME (Japanese, Chinese, or Korean)
2. Type text that includes emoji characters during composition
3. Verify that the text is not processed until …
=> 🩹 fix: skip processing when emojis are present during IME conversion

demos/src/Marks/Link/React/index.jsx
Replace direct calls to editor.isActive('link') with a reactive selector via useEditorState so the Set/Unset link buttons reflect the current active state immediately in React demos. Matches Vue behaviour and prevents the 'one render behind' issue reported in #6626.
Fixes #6626
=> use useEditorState in React demo to fix isActive lag (#6626)

packages/html/package.json
This pull request updates the module export configuration in the `packages/html/package.json` file to better support different environments (browser and Node.js). The most important change is the introduction of environment-specific entry points for the ES module import field.
Module resolution improvements:
* Updated the `import` field in `exports` to specify separate entry points for `browser` (`./dist/index.js`), `node` (`./dist/server/index.js`), and a `default` fallback (`./dist/index.js`).
This allows consumers to automatically get the appropriate build depending on their environment.
Create a Node.js script to test server-side HTML generation:
```javascript
// test-server.js
import { generateHTML } from '@tiptap/html'
import { Document } from '@tiptap/extension-document'
import { …
```
=> Fix: generateHTML on server

.changeset/sweet-panthers-decide.md, packages/extension-collaboration/src/collaboration.ts
The current warning in `@tiptap/extension-collaboration` checks for the `undoRedo` extension, 
but the message still references the outdated `@tiptap/extension-history`.
This PR updates the warning to correctly reference `@tiptap/extension-undo-redo`.
- Before: "[tiptap warn]: ... not compatible with @tiptap/extension-history"
- After:  "[tiptap warn]: ... not compatible with @tiptap/extension-undo-redo"
#6869
=> fix(collaboration): correct warning message to reference undo-redo extension

.changeset/moody-trees-rescue.md, .changeset/serious-tools-hear.md, packages/extension-drag-handle-vue-2/src/DragHandle.ts
* Vue2 requires factory functions for defaults for objects and arrays.
* `class` may not be used as prop.
Use a factory function.
Checked that it prevents the warning by building text with it:
> Invalid default value for prop "PluginKey": Props with type Object/Array must use a factory function to return the default value.
Actually testing is cumbersome. Vue 3 seems to have dropped the warning. [I'm still checking](https://github.com/vuejs/docs/pull/3282) if that actually also means it's not an issue anymore.
Checking the code and checking [the docs]( https://v2.vuejs.org/v2/guide/components-props#Prop-Validation) is probably best (search for 'factory function')
I'm still looking into fixing the class reserved name warning.
Initially came up in …
=> fix(drag-handle-vue-2): fix vue2 warnign about objects as default

.changeset/little-cups-play.md, packages/extension-code-block-lowlight/src/code-block-lowlight.ts, packages/extension-code-block/src/code-block.ts
- Introduced options for enabling tab key indentation and setting tab size in CodeBlock.
- Implemented handling for tab and shift+tab key events to manage indentation and reverse indentation.
- Updated CodeBlockLowlight to inherit new options for consistency.
**New Options Added:**
- `enableTabIndentation: boolean` (default: `false`) - Controls whether tab key indentation is enabled
- `tabSize: number` (default: `4`) - Defines the number of spaces to use for each indentation level
**Tab Key Functionality:**
- **Tab**: Adds indentation by inserting spaces (count determined by `tabSize`)
- For single cursor: Inserts indentation at current position
- For text selection: Indents all selected lines
- **Shift+Tab**: Removes indentation by removing up to `tabSize` spaces from the beginning of …
=> add tab indentation support to code blocks

packages/suggestion/src/suggestion.ts
Previously, clientRect was only obtained through decorationNode. If decorationNode could not be obtained, the value of clientRect was assigned to null. This commit adds a new method to obtain clientRect.
If decorationNode cannot be obtained, the coordinates are obtained according to the editor's cursor position, and the cursor position is used to generate a DOMRect.
In scenarios where Chinese IME is used, the value of clientRect is almost always null, which causes the "suggestion" to not render. This commit fixes this issue.
Just type @ when using the Chinese input method and the result will be verified.
=> fix(extension-suggestion): trigger suggestion popup for @ in Chinese input method

.changeset/fair-bananas-smile.md, packages/vue-2/src/BubbleMenu.ts, packages/vue-2/src/FloatingMenu.ts
Fix visibility bug in BubbleMenu and FloatingMenu in the vue2 adaptor.
Same approach as was done in vue3 long time ago: https://github.com/ueberdosis/tiptap/commit/177eed65a4467db511c49f56a31a999e3f611c13
Yes.
Tested in the real app. Works perfectly.
This bug can be reproduced only when you have vue 2 app (2.7 in my case) and your menu can change dynamically (e.g. buttons are reactively highlighted). In this case the hardcoded `visibility: hidden` just hides the menu.
- [ + ] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [ + ] My changes do not break the library.
- [ - ] I have added tests where applicable.
- [ + ] I have followed the project guidelines.
- [ + ] I have fixed any lint issues.
none
=> Fix menus in vue2

.changeset/cuddly-carpets-think.md, packages/extension-drag-handle/src/drag-handle-plugin.ts, packages/extension-drag-handle/src/drag-handle.ts
Add `getReferencedVirtualElement` option to the drag handle extension to customize the position of the drag handle.
=> Add more Floating UI options to Drag Handle plugin

.changeset/fluffy-carrots-hide.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-bubble-menu/src/bubble-menu.ts, packages/react/src/menus/BubbleMenu.tsx
Add `updateBubbleMenuPosition` command to update position of bubble menu. This command lets developers programmatically update the position of the bubble menu in response to certain events (for example, when the bubble menu is resized).
The command emits an event. Then, the event is captured in the prosemirror plugin to trigger the position to recompute.
=> Add command to update the position of the bubble menu

.changeset/strong-mice-allow.md, packages/vue-3/src/menus/BubbleMenu.ts, packages/vue-3/src/menus/FloatingMenu.ts
It will now be possible to set `class` and other properties on `<BubbleMenu>` and `<FloatingMenu>` and they will be passed through to the menu element. Right now, it will pass it implicitly to the `Teleport` which cannot handle them.
This is useful to allow setting `z-index` on the menu as a follow up on https://github.com/ueberdosis/tiptap/pull/6841
Simply got passed them through explicitly by getting `attrs` from `setup` and passing them to the `root` element.
https://github.com/ueberdosis/tiptap/pull/6841
=> Pass `attrs` through to Vue 3 menus

.changeset/merge-nested-span-styles.md, packages/extension-text-style/src/text-style/index.ts
- Fix nested `<span>` style merging in index.ts.
- Merge only immediate child `<span>` styles into each child (instead of re-processing all descendants), preventing exponential work and potential tab unresponsiveness/crashes.
- Add/update merge-nested-span-styles.md documenting the bugfix/perf improvement.
- Replace a descendant-wide/fragile approach with a direct-child-only merge using `element.children` filtered to `<span>` elements.
- Read parent `style` once, merge with each child’s `style` if present, and remove empty `style` attributes.
- Keep the option flag `mergeNestedSpanStyles: true` as default; call the helper only from the `parseHTML` `getAttrs` hook so the parser still applies merged styles during element parsing.
Files changed:
- index.ts - change to `mergeNestedSpanStyles` …
=> fix: optimize merging of nested span styles for improved performance

.changeset/fix-bubble-menu-destroyed-editor.md, packages/extension-bubble-menu/src/bubble-menu-plugin.ts
This pull request addresses a bug in the `@tiptap/extension-bubble-menu` package that could cause an error when the editor is destroyed while the bubble menu plugin is cleaning up. The fix ensures that the plugin checks if the editor is destroyed before proceeding with certain operations.
Bug fix:
* Added a check in the `blurHandler` method of `bubble-menu-plugin.ts` to verify if the editor has been destroyed, and if so, immediately destroys the plugin to prevent errors during cleanup.
Changelog update:
* Added a changeset entry documenting the bug fix for the bubble menu error when the editor is destroyed.
Did a local test with a demo that would destroy the editor which caused the bubble menu to throw an error because `editor.view.dom` would now be non-accessible anymore because the …
=> fix(BubbleMenu): prevent error when editor is destroyed during cleanup

.changeset/fix-bubblemenu.md, packages/react/src/menus/BubbleMenu.tsx
Fixed an issue where the React BubbleMenu didn’t pick up prop changes after initial mount. In particular, updates to options according to issue #6963
The effect that registers the BubbleMenu plugin now includes all relevant configuration in its dependency list.
=> fix(react BubbleMenu): BubbleMenu now reacts to prop changes

.changeset/tame-beans-fly.md, packages/core/src/types.ts
This change is required if the TypeScript option `exactOptionalPropertyTypes` is enabled.
Fixes #6914.
Updated the types.
Checked that the types match using TypeScript compiler.
Ran the TypeScript compiler on a project (see #6914)
-
#6914
=> Update JSONContent to exactly match editor.getJSON()
