ueberdosis/tiptap

packages/tiptap-extensions/src/nodes/TodoList.js
Wanted to do this earlier,and in the meantime you already have fixed one of the wrong class names 😃
=> fix class name

packages/tiptap-extensions/src/plugins/Suggestions.js
This fix enables to use $-char or any special char without infinite cycle :-)
=> Escape Suggestion trigger char

packages/tiptap-extensions/src/nodes/Mention.js
This fix allow to extend Mention class to build own configured mentions.
=> Mention extend

examples/Components/Routes/Placeholder/index.vue
=> Update Placeholder Example

examples/Components/Routes/Embeds/Iframe.js
=> fix pasting in embed example

packages/tiptap-extensions/src/extensions/History.js
Fixes #211.
Let me know if there's something more to do! :smile:
=> Add support to history custom settings

README.md
Fixed misnamed option in the Editor documentation.
=> Fix README.md documentation

packages/tiptap-extensions/src/marks/Link.js
=> fix #275: link click handler no longer open on selection click

packages/tiptap/src/Utils/ExtensionManager.js
- remove duplication of logic
- reduce code lines by half (not the entire module, but the part this refactor is applied to)
If preferred, change the name of new functions `apply` and `handle` as you please.
=> refactor src/Utils/ExtensionManager.js

packages/tiptap-commands/src/commands/markInputRule.js, packages/tiptap-extensions/src/marks/Italic.js
fixes markPasteRules and markInputRules for italic and bold marks.. fixes #284
=> fix pasteRules and InputRules for italic mark

examples/Components/Routes/Tables/index.vue, packages/tiptap-extensions/src/nodes/Table.js
=> adding option to disable resizing of tables

packages/tiptap-commands/package.json, packages/tiptap-commands/src/commands/toggleList.js
I'm not 100% sure that this is the way to go 🙈
fixes #4
=> toggle between unordered_list and ordered_list

packages/tiptap-extensions/src/nodes/Table.js
=> set selection to first cell after table insert

packages/tiptap-extensions/src/nodes/Table.js
The calculation for the offset was wrong.
Will fix #488
=> use last selection + 1 to set table create selection

README.md
https://github.com/Leecason/element-tiptap
I'm continuously working to add in new features.
thanks 😊
=> add element-tiptap to the README

packages/tiptap/src/Plugins/FloatingMenu.js, packages/tiptap/src/Plugins/MenuBar.js, packages/tiptap/src/Plugins/MenuBubble.js
this pull request tries to fix #485
=> set capture to true for mousedown event listener

packages/tiptap/src/Plugins/FloatingMenu.js, packages/tiptap/src/Plugins/MenuBar.js, packages/tiptap/src/Plugins/MenuBubble.js
=> Remove menu event handlers on destroy

README.md
Related projects: quasar-tiptap
=> Add related projects - quasar-tiptap

examples/Components/Routes/Suggestions/index.vue, package.json
Suggested fix for https://github.com/scrumpy/tiptap/issues/749 as projects we have may be using Fuse.js >3
=> update fuse.js to v6 and fix Suggestion mention search

packages/tiptap-extensions/src/extensions/History.js
I am 100% sure that this combination should work. This will make it possible to manage the history on the Russian keyboard.
=> improvement(History extension): support ru keys

examples/Components/Routes/DragHandle/DragItem.js
This partially resolves\ #481.
=> Added comment about data-drag-handle.

packages/tiptap-commands/src/commands/updateMark.js
=> fix: link command on multi cell selections

docs/src/docPages/api/nodes/table-header.md
:wave: I think "optional" is what was meant here.
=> Clarify table header documentation

docs/src/docPages/api/nodes.md
Set 'default extension' for horizontalRule to true in api-nodes documentation.
=> HorizontalRule is included in defaultExtensions

docs/src/docPages/overview/upgrade-guide.md
- Removed extensions with no name change
- Added missing extensions with name change
=> docs: complete list of extensions with changed name

docs/src/docPages/overview/upgrade-guide.md
Just a tiny improvement to the wording used
=> Wording improvement

packages/extension-floating-menu/src/floating-menu.ts
This seems like a mistake but please let me know if I'm missing something...
=> Fix name of FloatingMenu

packages/extension-mention/src/mention.ts
See here: https://github.com/ueberdosis/tiptap/commit/c64761a9e5f2c9cb7c90668abcdb8856c46547f8#commitcomment-52163786
I assume this is necessary. Please confirm this fixes it.
=> Fix parsing of mention nodes

docs/src/docPages/api/nodes/mention.md
=> VueRenderer documentation with version 3

CONTRIBUTING.md
It took me a moment to figure out more detailed contribution instructions where included on the TipTap website. Would be good to link to those.
=> Link to contribution guidelines in CONTRIBUTING.md

packages/extension-table/src/index.ts
I think this can be useful for consumers as well
=> export createTable

docs/src/demos/Nodes/OrderedList/index.spec.js, packages/extension-ordered-list/src/ordered-list.ts
Fixes https://github.com/ueberdosis/tiptap/issues/1586
=> Fix custom start for ordered lists

docs/src/docPages/api/extensions/typography.md, packages/extension-typography/src/typography.ts
- superscriptTwo
- superscriptThree
- oneQuarter
- threeQuarters
=> Additional input rules for typography

packages/extension-typography/src/typography.ts
=> ✨ Add typography trademark

packages/suggestion/src/suggestion.ts
=> Add type for async items on suggestions (fix TS strict types complain)

packages/core/src/Editor.ts, packages/core/src/index.ts, packages/core/src/types.ts
Follow up to https://github.com/ueberdosis/tiptap/issues/1920
=> Add enableCoreExtensions flag

demos/src/Examples/CustomDocument/React/index.html, demos/src/Examples/CustomDocument/React/index.jsx, demos/src/Examples/CustomDocument/React/styles.scss, demos/src/Examples/CustomDocument/Vue/index.html, demos/src/Examples/CustomDocument/Vue/index.spec.js, demos/src/Examples/CustomDocument/Vue/index.vue, docs/examples/custom-document.md, docs/examples/default.md, docs/links.yaml
That’s something a lot of people seem to use, so it’ll probably make a good example. ✨
=> New example for custom documents (to force a heading on the top)

packages/html/package.json, packages/html/src/generateJSON.ts, packages/html/src/getHTMLFromFragment.ts, yarn.lock
Switch to zeed-dom because hostic-dom is not maintained anymore.
This also fixes #2148
=> Switch from hostic dom to zeed dom

docs/api/events.md
=> fix typo in events.md

packages/html/package.json, yarn.lock
As @holtwick did [fix the underlying issue](https://github.com/holtwick/zeed-dom/issues/2#issuecomment-964329350) in zeed dom I thought it would take some weight off of your shoulders if I would prepare the update of that dependency.
=> update zeed dom

packages/extension-color/src/color.ts
Fixes [Issue#2179](https://github.com/ueberdosis/tiptap/issues/2179#issue-1059373098)
=> Export type ColorOptions

packages/extension-font-family/src/font-family.ts
Exports the type `FontFamilyOptions`
=> Export type FontFamilyOptions

docs/installation/vue3.md
Gramatical Error:
You’re probably used to bind your data --> You’re probably used to binding your data
Note: addition of -ing
=> Update vue3.md Grammar Error In Docs

packages/react/src/useEditor.ts
=> Fix state update after component unmounted

docs/api/extensions.md
mentions of community extensions in `extensions.md`
=> docs(extensions): mention community extensions and discussion thread

packages/vue-3/src/NodeViewWrapper.ts
=> fix: vue inject grammar warning

packages/extension-typography/src/typography.ts
=> feat(extension-typography): add servicemark input rule

packages/extension-link/src/link.ts, packages/extension-table/src/utilities/createTable.ts
A small PR to fix some typing errors in the link and table extensions,
=> fix(types): fix link and table type errors

packages/core/src/helpers/getTextContentFromNodes.ts
=> fix(core): InputRules does not work for ranges containing multiple text nodes

docs/guide/node-views.md
=> fix(docs): typo

packages/suggestion/src/suggestion.ts
=> fixes typo in  suggestion.ts

docs/guide/custom-extensions.md
First time making a PR here, please advice if I'm doing anything wrong 🙏 
Just a small typo I found while reading the docs
=> typo: custom-extensions.md completely

docs/guide/typescript.md
Add a forgotten quotation mark in the import and specify the language in md code block
=> fix(typo): typescript.md

packages/extension-youtube/src/utils.ts
Just ran into this issue on our site and thought I'd share the fix.
=> Update regex to exclude channel URL unfurling

packages/vue-3/src/BubbleMenu.ts
This fixes a typescript type for the pluginKey prop in BubbleMenu
=> Fix type for BubbleMenu prop pluginKey

demos/src/Experiments/Tailwind/JS/index.html
I realized that if I use Tailwind's CDN directly, you can have it react to dark mode directly.
=> Use Tailwind CDN direclty?

packages/extension-collaboration/src/collaboration.ts
This PR is a simple forwarding of a very useful callback from the ySyncPlugin.
=> Add onFirstRender callback option

packages/core/src/helpers/createNodeFromContent.ts, packages/react/src/EditorContent.tsx
Fixes #3773 
https://user-images.githubusercontent.com/20477956/221091458-db003903-e32b-4331-b5d3-14b1413b2645.mp4
=> fix: #3773 - Array for content breaks editor

demos/src/Examples/AutolinkValidation/React/index.spec.js, demos/src/Examples/AutolinkValidation/Vue/index.spec.js, tests/cypress.config.js
This PR tries to improve the test reliability to move the forEach out of the assertion and start it's own assertion per array item.
=> fix(tests): add assertion for each valid/invalid link

packages/extension-ordered-list/src/ordered-list.ts
=> fix: Ordered list start support broke in #3541

demos/package.json, package-lock.json
Upgrades @hocuspocus/provider to 2.0.1
=> Updates @hocuspocus/provider to 2.0.1

demos/src/Demos/SingleRoomCollab/React/MenuBar.jsx, demos/src/Demos/SingleRoomCollab/React/MenuBar.scss, demos/src/Demos/SingleRoomCollab/React/MenuItem.jsx, demos/src/Demos/SingleRoomCollab/React/MenuItem.scss, demos/src/Demos/SingleRoomCollab/React/index.jsx, demos/src/Demos/SingleRoomCollab/React/index.spec.js, demos/src/Demos/SingleRoomCollab/React/styles.scss
=> Landingpage demo

docs/guide/node-views/vue.md
Fixes a typo in `vue.md`
Fixed the typo
No test needed
The typo is fixed in the PR
Hope this hasn't been too many PRs to address typos, trying to help out as I go through the docs
N/A
=> chore(docs): Fix typo in vue.md

docs/guide/collaborative-editing.md, docs/installation/react.md
Removed outdated screencasts from docs.
Removed the references to the screencasts from the markdown files.
I built it locally
Have a look at the two markdown files.
n/a
n/a
=> remove screencasts

docs/api/schema.md
Docs typo fix
Through github's web interface
=> Docs tiny typo

docs/guide/styling.md
=> Fix typo in guide

docs/introduction.md
Fix a typo in the docs
The power of typing?
n/a
Visually
n/a
n/a
=> Fix HocusPocus typo in introduction.md

demos/src/Commands/Cut/React/index.jsx
Fixes the demo for the `cut` command.
=> fix demo for cut command

docs/guide/node-views/react.md
This PR adds documentation for #3984 and should be merged with it.
=> docs(react): add documentation for contentDOMElementTag

docs/installation/cdn.md
https://esm.sh.dev -> https://esm.sh
=> Fix esm.sh url

docs/api/commands.md
This PR adds information about position mapping on Prosemirror transactions in the commands documentation. Without this info it's unclear that positions will go off track if chains are used without manually updating the positions.
see #4376
=> docs: add information about transaction mapping in chains

docs/api/nodes/youtube.md
[add a description of your changes here]
[add a detailed description of how you accomplished your changes here]
[add a detailed description of how you tested your changes here]
=> fix youtube node typo in docs

packages/react/src/index.ts
Let those who want to access internals do so
=> Export useReactNodeView

packages/core/src/helpers/combineTransactionSteps.ts, packages/core/src/helpers/createChainableState.ts, packages/core/src/helpers/createDocument.ts, packages/core/src/helpers/createNodeFromContent.ts, packages/core/src/helpers/defaultBlockAt.ts, packages/core/src/helpers/findChildren.ts, packages/core/src/helpers/findChildrenInRange.ts, packages/core/src/helpers/findParentNode.ts, packages/core/src/helpers/findParentNodeClosestToPos.ts, packages/core/src/helpers/generateHTML.ts, packages/core/src/helpers/generateJSON.ts, packages/core/src/helpers/generateText.ts, packages/core/src/helpers/getAttributes.ts, packages/core/src/helpers/getSchemaByResolvedExtensions.ts, packages/core/src/helpers/getSchemaTypeByName.ts, packages/core/src/helpers/getSchemaTypeNameByName.ts, packages/core/src/helpers/getSplittedAttributes.ts, packages/core/src/helpers/getText.ts, packages/core/src/helpers/getTextBetween.ts, packages/core/src/helpers/getTextContentFromNodes.ts, packages/core/src/helpers/getTextSerializersFromSchema.ts
I added a few more JSDocs for Tiptap utilitify functions on core.
N/A
N/A
N/A
N/A
N/A
=> refactor(core): add jsdocs for utility functions

demos/preview/Demo.vue
This PR adds small adjustments to our preview frames on our demo pages to adjust for future documentation page updates.
N/A
N/A
N/A
Does not require any testing since it's just design changes for our demos preview pages.
N/A
=> feat: new demo frame design

demos/src/Marks/Link/React/index.spec.js, demos/src/Marks/Link/Vue/index.spec.js, packages/extension-link/src/link.ts
Makes a link exitable by default
=> fix: make link exitable resolving #3293

packages/core/src/types.ts
Added two `?` to the type def to get rid of typescript errors
=> define keepOnSplit and default optional

packages/vue-3/src/Editor.ts, packages/vue-3/src/EditorContent.ts, packages/vue-3/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueRenderer.ts
Reverts ueberdosis/tiptap#5206
I meant to release this on develop, not main
=> revert: "fix: (vue-3) component rendering"

.changeset/shy-clouds-smoke.md, packages/core/src/Editor.ts, packages/core/src/types.ts, packages/vue-3/src/Editor.ts, packages/vue-3/src/EditorContent.ts, packages/vue-3/src/VueNodeViewRenderer.ts, packages/vue-3/src/VueRenderer.ts
- **revert: "revert: "fix(vue-3): fix editor.state updating too late during a transaction due to reactiveState fixes #4870 (#5252)""**
- **revert: "revert: "fix(vue-3): faster component rendering (#5206)""**
- **fix: backwards compatibility ref exposed methods**
- **fix(vue-3): provide app global (#5354)**
- **fix(vue-3): fix(vue-3): vue's VueNodeViewRenderer should return `null` for `contentDOM` (#3966)**
=> Vue 3 Perf updates

packages/vue-3/src/EditorContent.ts
We use Object.assign() instead spread operator to forward parent chain provides
https://github.com/ueberdosis/tiptap/issues/5394
=> fix(vue-3): copy missing provided parent values

.changeset/wet-terms-fetch.md, packages/extension-placeholder/src/placeholder.ts
- **fix(placeholder): add back `considerAsAny` type but mark it deprecated**
- **chore: wip for another placeholder issue**
=> fix(placeholder): add back-compat to deprecated placeholder functionality

package-lock.json
=> chore: rebuild pjson

.changeset/shaggy-readers-heal.md, package-lock.json, packages/react/package.json, packages/react/src/useEditorState.ts
It is annoying to have to specify your equality function every time you want to actually get the perf benefits from `useEditorState` since most will likely be returning objects and arrays instead of primitives, it is better to just default to deep equal comparisons
=> refactor(react): default to using deep equal comparisons

.changeset/rare-trainers-reflect.md, packages/suggestion/src/suggestion.ts
See discussion here: https://github.com/ueberdosis/tiptap/pull/4380#issuecomment-2299334287
I checked that this works with collaboration in the split pane demo and testing what the original issue was trying to resolve
=> fix(suggestion): sometimes a suggestion would not show up (#4380)

package-lock.json, packages/html/package.json
This updates zeed-dom version to resolve #5352
=> fix: update zeed-dom version for style support #5352

packages/core/src/types.ts
=> refactor: make NodeViewProps an interface again

.changeset/slow-peaches-film.md, packages/core/src/types.ts
Updates the typing for `DecorationWithType`, prosemirror does not expose these types but it at least is more accurate to the concrete object's type
=> docs: update the typings for DecorationWithType to be more accurate

.changeset/light-pens-end.md, package-lock.json, packages/extension-bullet-list/package.json, packages/extension-bullet-list/src/bullet-list.ts, packages/extension-ordered-list/package.json, packages/extension-ordered-list/src/ordered-list.ts
Removes the dependencies completely to resolve #5707
=> fix(lists): bullet-list and ordered-list no longer depend on list-item or text-style extensions #5707

.changeset/happy-vans-smash.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
Updates the typings to be accurate
=> fix(core): update the typing of `addOptions`, `addStorage` to have an optional parent #5768

packages/core/src/Editor.ts
=> feat: accessibility improvements

.changeset/fluffy-panthers-yell.md, packages/core/src/Extension.ts, packages/core/src/Mark.ts, packages/core/src/Node.ts
=> fix(core): update the typings to be that options and storage are partials on an extended config #5852

.github/workflows/build.yml, package-lock.json, package.json, packages/core/src/helpers/getSchemaByResolvedExtensions.ts
=> build: add pkg-pr-new

.changeset/six-islands-breathe.md, packages/core/src/commands/selectAll.ts
Changing the selectAll command
Standard solution from pm
Test on a local
Add a table as the first element in the editor
Select everything using Mod-a
Try to delete everything using the delete key
[Demo](https://deploy-preview-5900--tiptap-embed.netlify.app/preview/Examples/Tables)
[Issues 5516](https://github.com/ueberdosis/tiptap/issues/5516)
=> [ISSUE-5516] Fixing select-all command

.changeset/yellow-cats-teach.md, packages/extension-font-family/src/font-family.ts, packages/extension-text-style/src/text-style.ts
Reverts ueberdosis/tiptap#5905
=> revert: "fix: remove empty text style handling"

package-lock.json, packages/extension-link/package.json, packages/extension-link/src/link.ts
Originally by: https://github.com/ueberdosis/tiptap/pull/5887
=> fix: update linkifyjs to support object-replacement characters

.changeset/fair-jars-shout.md, packages/extension-text-style/src/text-style.ts
https://github.com/ueberdosis/tiptap/discussions/5912#discussioncomment-11716337
=> feat: make text-style non-consuming

.github/workflows/build.yml, demos/src/Commands/Cut/React/index.spec.js
=> build: move cypress cache

demos/vite.config.ts, packages/extension-table-cell/src/index.ts, packages/extension-table-header/src/index.ts, packages/extension-table-row/src/index.ts, packages/extension-table/package.json, packages/extension-table/src/index.ts, packages/extension-table/src/table-kit/index.ts, packages/extension-table/tsup.config.ts
This pull request includes several changes to the `@tiptap/extension-table` package to improve module organization and type handling. The changes primarily involve updating import paths, modifying the `package.json` file, and adjusting the build configuration.
* [`packages/extension-table-cell/src/index.ts`](diffhunk://#diff-20e392237a10cf10c7075b6a8afc6ac56bcb79528285976d58f9111bf982f475L1-R5): Updated import and export paths for `TableCell` to use the new module structure.
* [`packages/extension-table-header/src/index.ts`](diffhunk://#diff-1886426eca3b3c5e108186621982dbda9afe3144e9f809f3c1f832ff64d90c6eL1-R5): Updated import and export paths for `TableHeader` to use the new module structure.
* [`packages/extension-table-row/src/index.ts`](diffhunk://#diff-71d3282a72fd9dbcaf5e26fe78213ccb …
=> refactor(table): re-export the sub-paths, reuse them in old pkgs

packages/core/src/utilities/mergeAttributes.ts
Convert class attribute to string
-
Test on a local
Pass a number into a class attribute
[Issue #5995](https://github.com/ueberdosis/tiptap/issues/5995)
=> fix(core): convert class attribute to string

packages/core/src/extensions/delete.ts, packages/core/src/types.ts
This adds support for mark deletions too
=> feat(core): the delete event can now detect mark deletions too

codemods/tiptap-2-migrate-imports/.codemodrc.json, codemods/tiptap-2-migrate-imports/.gitignore, codemods/tiptap-2-migrate-imports/.prettierrc, codemods/tiptap-2-migrate-imports/README.md, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture1.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture1.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture2.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture2.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture3.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture3.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture4.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture4.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture5.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture5.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture6.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture6.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture7.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture7.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture8.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture8.output, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture9.input, codemods/tiptap-2-migrate-imports/__testfixtures__/fixture9.output, codemods/tiptap-2-migrate-imports/package.json, codemods/tiptap-2-migrate-imports/src/index.ts, codemods/tiptap-2-migrate-imports/test/test.ts, codemods/tiptap-2-migrate-imports/tsconfig.json, codemods/tiptap-2-migrate-imports/vitest.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml
This adds a codemod for changing between the new & old imports
=> feat: add a codemod for transforming imports

.changeset/small-otters-bake.md, demos/package.json, packages/pm/package.json, pnpm-lock.yaml
Update prosemirror-changeset package to support token encoders
Update the package
Check that the existing tests and demos work. No new tests added
Check that libraries and demos that rely on this package work exactly the same.
=> Update prosemirror-changeset package to support token encoders

codemods/tiptap-2-migrate-imports/.codemodrc.json, codemods/tiptap-2-migrate-imports/tsconfig.json, demos/src/Examples/EnterShortcuts/React/styles.scss, demos/src/Extensions/BackgroundColor/Vue/index.vue, demos/src/Extensions/FontFamily/React/index.jsx, demos/src/Extensions/FontFamily/Vue/index.vue, demos/src/Extensions/FontSize/React/index.jsx, demos/src/Extensions/FontSize/Vue/index.vue, demos/src/Extensions/LineHeight/React/styles.scss, demos/src/Extensions/LineHeight/Vue/styles.scss, demos/src/Extensions/Selection/React/styles.scss, demos/src/Extensions/TrailingNode/React/styles.scss, tests/cypress/integration/core/isActive.spec.ts
After modifying the eslint fix command in #6371, apply Prettier and ESLint automatic fixes
run `pnpm run lint:fix`
If I run `pnpm run lint:fix` again, no more automatic fixes are applied.
=> Apply Prettier and ESLint automatic fixes

.changeset/hip-teachers-dream.md, packages/html/src/createSafeParser.ts, packages/html/src/createSafeWindow.ts, packages/html/src/generateJSON.ts, packages/html/src/getHTMLFromFragment.ts, packages/html/src/preserveAndRestoreNodeInternals.ts
This pull request introduces changes to improve the handling of `happy-dom`'s `Window` and `DOMParser` to prevent global `process` modifications, ensuring safer and more predictable behavior in environments without a native `window` object. The changes include creating utility functions for safe `Window` and `DOMParser` instantiation and updating relevant code to use these utilities.
* **New utility functions for safe creation**:
- Added `createSafeParser` in `packages/html/src/createSafeParser.ts` to wrap `happy-dom`'s `DOMParser` instantiation while preserving the original global `process` object.
- Added `createSafeWindow` in `packages/html/src/createSafeWindow.ts` to wrap `happy-dom`'s `Window` creation with the same safety mechanism.
* **Integration of utility functions**:
- Updated …
=> Fix happy-dom overwriting NodeJS process variable

.changeset/good-trainers-train.md, packages/react/src/ReactRenderer.tsx
Integration PR for #6458 into `develop`
=> fix incorrectly added ref props (#6458)

.changeset/five-rules-pull.md, packages/extension-emoji/src/emoji.ts
=> Integration (next to main)

.changeset/stale-ties-press.md, packages/react/src/ReactRenderer.tsx
=> revert flushSync removal

.changeset/eighty-cats-dream.md, packages/html/package.json, packages/html/src/server/generateHTML.ts, packages/html/src/server/generateJSON.ts, packages/html/src/server/getHTMLFromFragment.ts
As discussed here: https://github.com/ueberdosis/tiptap/issues/6454#issuecomment-3047974845
This PR now removes the async import of happy-dom and just makes it a dependency of the package. In most cases tree-shaking should handle not having the dependency imported if it's not used (e.g. only the non-server imports are used).
This pull request introduces several changes to the `@tiptap/html` package to improve its server-side functionality and simplify its codebase. The most significant updates include requiring the `happy-dom` library for server imports, refactoring functions to remove asynchronous behavior, and updating dependencies accordingly.
* [`.changeset/eighty-cats-dream.md`](diffhunk://#diff-1fe232aa2116b5d6ad7f063a4a0c862366365c9446a5930c7e68ae48c9979112R1-R5): Updated the …
=> require happy-dom in html and remove async behavior for server imports

.changeset/silver-adults-fold.md, packages/react/src/ReactNodeViewRenderer.tsx
=> Bdbch/fix nodeview render target (#6600)

.changeset/grumpy-seals-shake.md, .changeset/two-chefs-lie.md, packages/core/src/jsx-runtime.ts, packages/extension-blockquote/src/blockquote.tsx, packages/extension-bold/src/bold.tsx
=> fix global react overwrites via jsx-runtime

.changeset/afraid-oranges-smell.md, demos/src/Extensions/BubbleMenu/React/index.jsx, packages/extension-bubble-menu/src/bubble-menu-plugin.ts, packages/extension-floating-menu/src/floating-menu-plugin.ts
=> fix broken menus when inline is true (#6658)

tests/cypress/integration/static-renderer/md-string.spec.ts
This pull request updates the test for the static markdown renderer to ensure it properly handles empty paragraph nodes in the input JSON structure.
=> fix(tests): fixed integration tests for markdown parser

.changeset/improve-drag-handle-lookup.md, packages/extension-drag-handle/src/drag-handle-plugin.ts, packages/extension-drag-handle/src/helpers/findNextElementFromCursor.ts
This pull request refactors and optimizes the drag handle plugin for the editor, focusing on improving mouse event handling and the logic for finding elements near the cursor. The main changes include switching to requestAnimationFrame for mouse movement processing, cleaning up resources, and updating the element-finding algorithm for better accuracy and performance.
* Mouse movement events now store the latest coordinates and schedule processing using `requestAnimationFrame`, ensuring only one update per frame and reducing redundant work. (`drag-handle-plugin.ts` [packages/extension-drag-handle/src/drag-handle-plugin.tsR351-R377](diffhunk://#diff-e9af7a47f33d820565ba874e0dd2812706a790b67ac7ae3c6d9cc0dd6d306050R351-R377))
* The plugin cleans up scheduled animation frames and pending mouse …
=> fix(drag-handle): optimize mouse coordinate handling and cleanup

README.md
add health badge from Linux Foundation Insights
=> add Linux Foundation health badge

CONTRIBUTING.md
Add CodeSandbox templates to contributing guide, so they are easier to find
=> Add CodeSandbox templates to contributing guide

.changeset/weak-hats-deny.md, packages/extension-table-of-contents/src/types.ts
Infer the storage type for the Table of Contents extension.
Used TypeScript module augmentation to declare `tableOfContents: TableOfContentsStorage` in `@tiptap/core`
type `editor.storage.` in IDE. then IDE suggest tableOfContents
as-is
to-be
=> fix(extension-table-of-contents): Improve typings by inferring the storage type.
